### ISSUE TITLE
Functions to get magnetostatic fields from known solutions (infinite wires, circular loops)

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#100]
In addition to the Biot-Savart law solver proposed in #99, we should have a way of calculating the magnetic fields resulting from simple current-carrying wire setups.  This would include the magnetic field from an infinite wire (which has a simple exact solution) and the magnetic field resulting from a circular current-carrying loop (which has a complicated exact solution) for boundary conditions at infinity.  There might be other analytical solutions worth including, but these two are probably the most important ones.

This could perhaps go in the `physics` subpackage in a file called `magnetostatics.py`.

**Comment by namurphy** [comment]
Happy issue/pull request #100, PlasmaPy!

**Comment by golanor** [comment]
Hacktoberfest TLV
Shotgun.
Now that the mandatory announcement is over - I'll start by adding the infinite wire case.

**Comment by SaravananOffl** [comment]
I can work on this!
@namurphy you can assign it to me

**Comment by hzxusx** [comment]
@SaravananOffl @namurphy 
Is any one still working on this feature? I have writen a [Julia script](https://github.com/hzxusx/active-mag-design/blob/master/wires.jl) for this last semester as part of my class project. I can adapt it to python.

I implemented circular wire, (finite) straight wire, general wire(described by parametric equation) types and methods to calculate their magnetic field at any position in 3D Cartesian coordinate. Those non-analytical integrals are done by Gauss-Legendre integration.

**Comment by StanczakDominik** [comment]
As far as I can tell, this is completely stalled. Go for it, @hzxusx!

**Comment by hzxusx** [comment]
Great! I'm happy to contribute. 

A question on your development habit, shall I open a feature branch? You seems use little of branches.

**Comment by StanczakDominik** [comment]
We use a bunch of them, but mostly on our personal forks. Take a look at the code development guide over at docs.plasmapy.org, and if that doesn't clear things up, please say so - I'll be happy to improve those docs!
