### ISSUE TITLE
Add Plasma class wrapper to RemDelaporteMathurin/plasma-boundaries

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#1006]
In #998 I started implementing analytical solutionsto the Grad-Shafranov equation for axisymmetric devices from Freidberg's "Ideal MHD" book. I had a notebook that did some quick SymPy calculations and all that.

Well, turns out https://github.com/RemDelaporteMathurin/plasma-boundaries already implements those, AND in less of an ad hoc, approximatory way, based on [10.1063/1.3328818](https://doi.org/10.1063/1.3328818).

We could add that package as a dependency, then construct a simple wrapper on top of as an instance of the Plasma class - calculating magnetic fields in Cartesian coordinates would be more than enough for now.

Bonus points for reading the paper and producing documentation! ;)

@rocco8773 I think this one qualifies as one of your fabled Project Issues :smile:

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hello @StanczakDominik , This seems like a cool task. Does it require advanced physics knowledge(I have high school physics knowledge and can try to understand equations). If there are any pre req please specify,Im willing to give this a shot.

**Comment by StanczakDominik** [comment]
Hey, sorry, I've already sort of done this in a long running development branch and this is essentially done, just not closed yet. Apologies! I'll close it now.
