### ISSUE TITLE
Implement bot to provide helpful comment on first contributions

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1007]
An idea that was brought up at out last community meeting is to create a bot (presumably through GitHub Actions) that would provide a helpful welcome message as a comment the first time that someone makes a pull request.  

The welcome message should link to our development guide and provide information on or links about:
 - Writing documentation (with links to guides on Sphinx and reStructuredText)
 - Writing tests (with links to pytest, plus our test helpers when they're implemented)
 - pre-commit
 - A guide on git and GitHub
 - The code review process
 - Our communication channels and meetings
 - Our code of conduct

We do want this to provide a warm welcome and an expression of gratitude, of course.  We should also try to be succinct and not provide unnecessary detail.  Thanks!

**Comment by StanczakDominik** [comment]
Taken over by @namurphy in #1095, so I'll unassign myself from this. (Trying to stay on top of my assigned issues more...)
