### ISSUE TITLE
Functions for Maxwellian and kappa distribution functions

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#101]
Particle distribution functions are used pretty commonly in plasma physics, and there are analytical expressions for [Maxwell-Boltzmann](https://en.wikipedia.org/wiki/Maxwell-Boltzmann_distribution) and [kappa](https://arxiv.org/pdf/1003.3532.pdf) distributions.  It would be great to create functions for these distributions in the `physics` subpackage.

**Comment by antoinelpp** [comment]
Hi, I'd like to take care of this one.
I'll try to implement :
* functions with arg {T, V_dift, v} which return f(v) (add $\kappa$ for the Kappa function)
* A generator, creating a particle which velocity corespond to the discribution function

I'm not sure if I can do it all by myself... We'll see ! :)

**Comment by StanczakDominik** [comment]
Awesome! For the particles, could you also try to tie it to that PIC
`species` class and try to make it return velocities for multiple
particles? I'll try to help out as I can :)

12.09.2017 09:51 "antoinelpp" <notifications@github.com> napisał(a):

**Comment by lemmatum** [comment]
Anyone want to add Kappa distributions so we can close this one out? Or got any tips about Kappa distributions and what they're supposed to do? (I've never used them).

**Comment by lemmatum** [comment]
I sorted out the kappa velocity distribution functions (both 1D and 3D). This issue is nearly done.

**Comment by lemmatum** [comment]
I believe #141 and #171 close this issue. Subsequent testing and verification for the kappa distribution should fall under #186
