### ISSUE TITLE
Change subpackage name from "analytic" to "math"

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#102]
The `analytic` subpackage originally contained plasma parameter as well as mathematical functionality.  The plasma parameter functions were moved to the `physics` subpackage, so `analytic` contains only the plasma dispersion function and its derivative.  Renaming the `analytic` subpackage to `math` would clarify the purpose of this subpackage.  This would involve changing the directory name, modifying this in `__init__.py` files in different directories, and changing `test_dispersion.py`.

**Comment by LudovicoGitHub** [comment]
Hey! This is my first time trying to contribute, I would like to tackle this problem.

**Comment by StanczakDominik** [comment]
@LudovicoGitHub awesome, hit that pull request button! :D

**Comment by namurphy** [comment]
Resolved by #108.  Thank you!
