### ISSUE TITLE
Computation of gyroradius from Plasmapy, in case of missing temperature should return NaNs instead of ValueError

### ISSUE THREAD

**Issue by qudsiramiz** [PlasmaPy/PlasmaPy#1022]
## Feature request

At present if I do the following, a ```ValueError``` is raised:
```python
>>> from plasmapy.formulary.parameters import gyroradius
>>> gyroradius(5 * u.nT, particle='p+', T_i=numpy.nan * u.K)
ValueError: Must give Vperp or T_i, but not both, as arguments to gyroradius
```
which is the wrong kind of error being raised. Error arises because temperature (```T_i```) data is NaN and not because the user is providing both ```T_i``` and ```Vperp```., as the text accompanying the error claims.

Another problem with this is that if we are trying to calculate gyroradius from a spacecraft data and at at any specific time, if both the magnetic field and (```B```) and ```T_i``` or ```Vperp``` data are missing, it raises the ```ValueError``` and stops the code from executing.

If instead of doing that, the code has the option to just set such values of gyroradius to ```numpy.nan``` (as is already happening when ```B``` is ```numpy.nan```), it increases its functionality and doesn't force the user to feed clean data.

I have also attached a screenshot of the error!
![gyroradius_error](https://user-images.githubusercontent.com/25327981/108413585-0d055b80-71e0-11eb-9902-9c679e974805.png)

**Comment by qudsiramiz** [comment]
I ran into this issue today, again! And spent 10 minutes wondering why it is giving `ValueError`. Then I realized it is an on open issue and hasn't been solved yet!

**Comment by alfkoehn** [comment]
Hi, I just wanted to look into this and was trying to wrap my head around those if-else clauses in the source code. If I understood you correctly, and please correct me if I'm wrong, you suggest that the function simply returns a `np.nan` if `T_i=np.nan` or (and) `Vperp=np.nan`.

In addition, you were suggesting that if the magnetic field is `np.nan` a `np.nan` should be returned. That is already the case as long as either `Vperp` or `T_i` is a finite value (but should also be the case if all input parameters were `np.nan`.

Am I understanding that correctly?

**Comment by qudsiramiz** [comment]
Yes, that is kind of what I am saying, apart from the fact that the code raises wrong kind of error. As I mentioned in my first comment based on the example I gave, "Error arises because temperature `(T_i)` data is `NaN `and not because the user is providing both `T_i `and `Vperp`., as the text accompanying the error claims."

And yeah I also suggested that the behaviour code has for `B=np.nan` should be replicated for `T_i=np.nan`, thus if someone inputs one or more values, as long as inputs are syntactically correct, the code should give `np.nan` as an output and not raise an error!

**Comment by alfkoehn** [comment]
thanks for clarifying, will try to look into that this evening (or tomorrow, as I have a full schedule today).
