### ISSUE TITLE
Improve readability of elements.py and isotopes.py

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#104]
At present, the `atomic` subpackage stores data for elements and isotopes as dictionaries that are coded into `elements.py` and `isotopes.py`.  I did this as a way to get the functionality done quickly, but this does not strike me as the best way to go about this.  I am wondering if it would be better to store the atomic data in HDF5 form and then to use `pytables` or `h5py` to access the information.  It would also be helpful to include more information on the provenance of the data (i.e., pointing out which databases the information came from).  During this process, the functions within `atomic.py` will need to be revised as well.

I'll assign myself to this since I still have the methods to create `elements.py` and `isotopes.py` somewhere (I hope!).

**Comment by antoinelpp** [comment]
Hi,
Putting data outside of the code seams good to me, however, `HDF5` seems a bit too much to me... I would consider `JSon` for informations like mass, charge, Inonization energy, and so on.
The only data that may require `HDF5` would be the cross sections, but I'm not sure it is worth it.

Json is very similar to a dictionary, but the library [JsonPickle](https://jsonpickle.github.io/) allow to load and dump python objects directly.

**Comment by StanczakDominik** [comment]
Antoine does have a point. It might be overkill, given that you're not
really doing any writing during usage and the data you're reading is sparse
(by which I mean, not arrays but maybe a few numbers with different
conceptual meaning per element or isotope). You don't really need lighting
fast data access for this one. I kind of like the json idea - but in all
honesty, given we already kind of have a dictionary for this one... I'm not
one hundred percent sure this needs changing.

12.09.2017 10:21 "antoinelpp" <notifications@github.com> napisał(a):

**Comment by namurphy** [comment]
All good points!  JSON seems like a good choice if we decide to do this, so I updated the title.  Since it's in an adequate format now, we can wait to do this until later.
