### ISSUE TITLE
Include half-life data for all isotopes with a known half-life

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#105]
Half-life data is presently included for only a subset of isotopes, since I wasn't able to find an easily usable database of nuclide stability.  We still need to include half-life data for all nuclides with known half-lives.  It would probably be helpful to include information on the uncertainty of each half-life, and information on the source of each half-life.  

This is related to #104 since the half-life data would go in the HDF5 file containing isotope data.  I'll assign myself to this, but would be happy to work with someone else.

If you have a good, recent table on the stability of nuclides, please post it here!

**Comment by namurphy** [comment]
These could be good sources for half-life and other atomic/nuclear data:
- [NUBASE 2016 reference](https://www-nds.iaea.org/amdc/ame2016/NUBASE2016.pdf) 
- [NUBASE 2016 ASCII formatted table](https://www-nds.iaea.org/amdc/ame2016/nubase2016.txt)
- [Nuclear Wallet Cards](http://www.nndc.bnl.gov/wallet/)

**Comment by namurphy** [comment]
A good first contribution would be to add the half-lives for some isotopes (especially important ones).  It would be a major effort to add all of them.

**Comment by misupova** [comment]
I searched for issues marked as "Good first contribution", and this one attracted my attention. As I am new to contributing, I want to clarify some things.

So as I understood, the first step is to add half-life information in Isotopes dictionary, and then create corresponding function (e.g. isotope_half_life) to retrieve this information, am I getting it correctly?

**Comment by misupova** [comment]
I searched for issues marked as "Good first contribution", and this one got my attention, but I want to clarify some things.

How could I include half-lives for isotopes, for which exact half-life is not known? For example, in one of the the sources we can find >260ns for Al-40, what could be sensible way to include such information in dictionary?

**Comment by StanczakDominik** [comment]
Hey @misupova, that's a pretty good question. I suppose a reasonable solution would be to put in None in that case and return an error saying there's no precisely known half life.

 Or we could put in a "<240ns" string and if the function gets a string instead of a float or quantity, raise an error saying something along the lines of "all we know is it's <240ns, use that as a ballpark estimate if you really need to.".

@namurphy, other suggestions?
