### ISSUE TITLE
collisions.py needs another review

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#1069]
The functionality in `plasmapy/formulary/collisions.py` went through an extensive review in PR #962.  However,  there are some inconsistencies between what is written in the docstrings and what is actually implemented in the associated function.  For example, the docstring for the `coupling_parameter` currently states

```restructuredtext
method : `str`, optional
        The method by which to compute the Coulomb logarithm.
        The default method is the classical straight-line Landau-Spitzer
        method (``"classical"`` or ``"ls"``). The other 6 supported methods
        are ``"ls_min_interp"``, ``"ls_full_interp"``, ``"ls_clamp_mininterp"``,
        ``"hls_min_interp"``, ``"hls_max_interp"``, and ``"hls_full_interp"``.
        Please refer to the docstring of `Coulomb_logarithm` for more
        information about these methods.
```

for the `method` keyword but the function only accepts values of `'classical'` and `'quantum'`.  Since so much was touched by PR #962, we need to read through each function and make sure the docstrings and contained functionality are consistent.

**Comment by rocco8773** [comment]
@namurphy and @Tiger-Du would you two be willing to take this up?

**Comment by Tiger-Du** [comment]
Sorry for the delay.

This is a good catch. I looked through collisions.py just now and did not come across any other inconsistencies like this one. Other files were changed in PR #962, so I will take a look at those files as well and will open a PR to fix this and any other inconsistencies tomorrow.
