### ISSUE TITLE
Document attribute `is_uniform` for AbstractGrid

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#1071]
@pheuer It appears that the `is_uniform` attribute on `AbstractGrid` is semi-public.  How do you feel about making this an actual property of the the class so it appears in the RTD documentation?

**Comment by pheuer** [comment]
Sure, I'm looking into what this would entail right now.

**Comment by pheuer** [comment]
How would you feel about having it be a cached property? It would be very time-intensive for it to be re-evaluated on every call (and right now it isn't).

**Comment by pheuer** [comment]
Alternately, we could have a cached property `_is_uniform` and then a public property `is_uniform` that, when called, re-evaluates the private cached property.

**Comment by rocco8773** [comment]
Not sure if you have to go the whole route of a cached property.  I'd do something like...

```python
class AbstractGrid:
    def __init__(...):
        self._is_uniform = None
        if len(seeds) == 3:
            self._load_grids(...)

    def _load_grids(...):
       self._is_uniform = ...

    @property
    def is_uniform(self):
        if self._is_uniform is None:
            # handle how you like to
            ...
        return self._is_uniform
```

Or just give it a leading underscore and skip the property if you don't want it to be public.  It don't know what the overall usage is, so I'll leave the decision up to you.
