### ISSUE TITLE
Expand notes on change log entries in the documentation, hopefully merge with change log readme

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#1075]
@namurphy @StanczakDominik A few things I realized when doing this PR.  I think we need to be a little more thorough with our review of change logs.  Admittedly this was a bit difficult before having the great live rendering of the change log (Thank you @StanczakDominik!).  There were quite a few entries that just did not make sense a month or two later when the context around the PR was lost.

What I think we should keep an I on going forward...

1. When reviewing a change log entry ask ourselves, "Will the change log still make sense if it is read X time from when the PR was merged?"
2. Use proper `sphinx` syntax so referenced code is properly linked by `intersphinx`.
3. If there are a lot of changes in a single PR, then don't force them all into one change log entry.  This makes the entry very unreadable.  Instead..
    1. Make multiple entries where the file tags `1070.doc.rst`, `1070.feature.rst`, etc. are use for the associated changes.
    2. If there are multiple unrelated, say, feature changes then make multiple entries like `1070.feature.1.rst`, `1070.feature.2.rst`, etc.  Each of these files will show up as a new bullet in the change log.

_Originally posted by @rocco8773 in https://github.com/PlasmaPy/PlasmaPy/pull/1070#issuecomment-798824746_

**Comment by namurphy** [comment]
Thank you for posting this issue — I was about to do the same thing!  It may be worth putting this in the pull request template too.

**Comment by StanczakDominik** [comment]
I think the PR template is overloaded as is...

**Comment by StanczakDominik** [comment]
Handled by #1198
