### ISSUE TITLE
Add feature freeze to release procedure

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1078]
A lesson that came from the release of version 0.6.0 (discussed in #1077) was that it would be helpful to have a moratorium on major changes for a period of time before a planned release date.  To that end, it would be helpful to add a feature freeze to our release procedure.  During that period, no major pull requests would be merged, and changes should be limited to refinements of existing features.  

I'm not sure how long we would want between the feature freeze and the release.  Perhaps a week?

**Comment by StanczakDominik** [comment]
I'm fine with a week!
