### ISSUE TITLE
Create a factory for decorators that process arguments based on annotations

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1079]
So...refactoring `@particle_input` in #1057 is turning out to be a pain, which is an indication that the approach I'm taking is probably less than optimal.  The biggest source of headaches for me is that I keep getting confused due to the decorator logic becoming intertwined with the particle input logic.  It would be helpful to have a way to separate the decorator logic from the "business" logic.  

One possibility would be to create a decorator factory for the generic pattern where arguments and outputs are processed based on annotations and keyword arguments to be supplied to the decorator.  The decorator factory would accept a callable that accepts `(args_to_function, kwargs_to_function, function_annotations, args_to_decorator, kwargs_to_decorator)` and returns (`new_args_to_function`, `new_kwargs_to_function`, and `new_function_annotations`).  There are a couple of possibilities for how to design this, so it'd be worth thinking more about that ahead of time (a habit I should probably get into...).

**Comment by StanczakDominik** [comment]
Another good habit is holding off on proposing solutions until the problem has been thoroughly discussed :D we can discuss that tomorrow at the telecon if you'd like?

**Comment by namurphy** [comment]
Closing this for now for reasons described in #1371.
