### ISSUE TITLE
More examples on documentation main page? 

### ISSUE THREAD

**Issue by pheuer** [PlasmaPy/PlasmaPy#1112]
The documentation main page currently only highlights three notebooks, but we have many more cool notebooks that could be featured here. I'd propose changing up the layout to include a grid of 3x3 examples. The "PlasmaPy is..." text could be larger font and go above them, along with the logo. The remaining table-of-contents is redundant with the sidebar, so I think it's fine for it to be pushed down out of view. I would also add a label "Highlights" or something to make clear that the examples don't represent all of the functionality in the package. 

The goal of this change would be to emphasize the diversity of functionality that already exists, similar to the way retail workers are taught to spread products out and pull them forward on the shelves to make them look really full.

![image](https://user-images.githubusercontent.com/32618747/114892242-95683d00-9dda-11eb-94ae-fb9ac2358233.png)

**Comment by StanczakDominik** [comment]
I agree with the notion of "let's have more room for cool notebooks in there"; that should increase the number of cool notebooks we have ;)
