### ISSUE TITLE
Iteratively enable flake8 checks

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#1116]
#1062 brought back flake8 linter checks, but kept most of them disabled. There are a bunch of them in setup.cfg:

https://github.com/PlasmaPy/PlasmaPy/blob/4a71ade0a7c0e3ef951a7096201f8ab22fc0c7c9/setup.cfg#L96-L185

It'd be nice to have them back. This would mean, for any brave soul willing to undertake this, for every check marked as TODO (and probably some others, too):

- enable the check again by removing it from the exclude list;
- fix all the lint errors that flake8 (in the tests section) starts throwing at you;
- continue down the list for as long as you'd like.

This is, admittedly, not exciting, but quite helpful and simple to execute; would be great for a new contributor.

**Comment by aksalcido** [comment]
Hello Dominik, I emailed you and I would like to work on this :)

**Comment by StanczakDominik** [comment]
Go right ahead! 😄
