### ISSUE TITLE
Overhaul the contributing guide

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#1117]
This is a central issue for our long overdue overhaul of the contributing guide.

- [ ] #1061 
- [x] note on `pre-commit.ci autofix`
- [x] #1086 
- [x] #1075
- [x] #760
- [ ] #706 
- [ ] #685 
- [ ] note that applying pre-commit will usually fix flake8 errors; also note that in the actual check's name

**Comment by namurphy** [comment]
While waiting for this blizzard to pass (and as an excuse to avoid shoveling snow ❄️) I began to think about an overall outline to the contributor guide, which I'm putting below so I don't forget it.  I'm still thinking about it, and of course it's something that I'd be happy to keep discussing.  

 - **Introduction** (welcome, imposter syndrome disclaimer, link to code of conduct, meetings, where to get help, etc.)
 - _**Resources**_ (where to learn Python, using git)
 - **Getting set up to contribute** (i.e. installing PlasmaPy for development, along with tools for pre-commit)
 - **Contribution workflow**
 - Changelog guide
 - **Code guide**
 - _**Package utilities**_ (validators, `@particle_input`, etc.; could be subsumed into code guide; or maybe expanded to include tools)
 - **Clean coding strategies** (or best practices, maybe?)
 - Testing guide
 - Documentation guide
 - **Writing example notebooks**
 - _**Code review guide**_
 - Release guide

The ones in bold would still need a lot of work (writing and/or rearranging).  The ones in bold & italics are ones I'm still debating (which might mean that they're lower priority).  The ones in regular text are approximately done.

**Comment by namurphy** [comment]
For cross-referencing, here are the PRs related to this:
 - #900
 - #961
 - #1156
 - #1163
 - #1178
 - #1198
 - #1205
 - #1217
 - #1264
 - #1305 (split up into multiple smallers PRs)
 - #1316
 - #1359
 - #1373
 - #1478
 - #1584
 - #1605
 - #1649
 - #1650
 - #1651
 - #1655
 - #1657
 - #1658
 - #1659
 - #1660
 - #1662
 - #1667
 - #1673
 - #1674
I think this is a sign that I should create a label.

**Comment by namurphy** [comment]
We've pretty much completed the overhaul of the contributor guide, so happily we can close this!
