### ISSUE TITLE
Raise ImportError when installing/importing with old versions of Python, Astropy, & NumPy

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#112]
We decided that PlasmaPy will only be supported for:
- Python version > 3.6
- Astropy version > 2.0
- NumPy version > 1.13

However, when I try to run:
```ShellSession
python setup.py install
```
from the command line with Python 3.5 then I get a `SyntaxError` for syntax that is new in version 3.6.

When I try to run
```Python
import plasmapy
```
in Python 3.6 with Astropy 1.3.1, then I get an exception since one of the constants imported from Astropy was renamed in 2.0.

We should raise an appropriate exception (probably an `ImportError`) when we try to install or import PlasmaPy with any of the unsupported versions above.  We should also have appropriate and useful error messages for any of these situations.  The pull request to close this issue would involve editing `setup.py`, `requirements/base.txt`, and `plasmapy/__init__.py`.

Thank you!
Nick

**Comment by namurphy** [comment]
Thank you @colbych for bringing up this problem!

**Comment by namurphy** [comment]
There's already a check for the Python version at the bottom of `plasmapy/__init__.py`, but I think that should be moved to the top of the file.  Then I think you can do things like
```Python
from astropy import __version__ as astropy_version
```
and then check to make sure it is recent enough, and then run `raise ImportError(error_message_string)` if it is too old.

I *think* this is the right syntax for `requirements/base.txt` to specify minimum versions.  
```
numpy (>= 1.13)
scipy (>= 0.19)
astropy (>= 2.0)
```

**Comment by colbych** [comment]
With a clean environment I installed plasmapy and verified that it worked. Then I uninstalled plasmapy and astropy. Next I installed astropy==1.3.3 and reinstalled plasma py. On the installation I got
```
(plasmapy)  haggerty@Colbylpt:~/Programing/PlasmaPy:requirements> pip install plasmapy
Collecting plasmapy
  Downloading plasmapy-0.1.dev1.tar.gz
Requirement already satisfied: numpy in /Users/haggerty/anaconda/envs/plasmapy/lib/python3.6/site-packages (from plasmapy)
Requirement already satisfied: scipy in /Users/haggerty/anaconda/envs/plasmapy/lib/python3.6/site-packages (from plasmapy)
Requirement already satisfied: astropy in /Users/haggerty/anaconda/envs/plasmapy/lib/python3.6/site-packages (from plasmapy)
```
So it just skipped over astropy because it was already installed.

Then I updated requirements/base.txt to include the line above from nick and this is what I ended up getting.
```
plasmapy)  haggerty@Colbylpt:~/Programing/PlasmaPy:requirements> pip install plasmapy
Processing /Users/haggerty/Programing/PlasmaPy
Requirement already satisfied: numpy>=1.13 in /Users/haggerty/anaconda/envs/plasmapy/lib/python3.6/site-packages (from plasmapy==0.1.dev1)
Requirement already satisfied: scipy>=0.19 in /Users/haggerty/anaconda/envs/plasmapy/lib/python3.6/site-packages (from plasmapy==0.1.dev1)
Collecting astropy>=2.0 (from plasmapy==0.1.dev1)
  Using cached astropy-2.0.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
```
So including the >= in the requirements takes care of it for the install.

**Comment by StanczakDominik** [comment]
Awesome! Wanna PR that @colbych?

**Comment by colbych** [comment]
>There's already a check for the Python version at the bottom of plasmapy/__init__.py, but I think that should be moved to the top of the file. Then I think you can do things like

Turns out pep8 doesn't like this. In #125 pep8 is yelling at me about the module level import not at top.

```
Line 77:1: E402 module level import not at top of file
Line 78:1: E402 module level import not at top of file
Line 79:1: E402 module level import not at top of file
Line 80:1: E402 module level import not at top of file
Line 81:1: E402 module level import not at top of file
Line 82:1: E402 module level import not at top of file
Line 83:1: E402 module level import not at top of file
```

Do you have thoughts about the @namurphy ?
