### ISSUE TITLE
Append 'dev' plus the commit number to development version numbers

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#113]
So Astropy does this cool thing where if you're using the development version of the code, then you can do this:
```Python
>>> import astropy
>>> astropy.__version__
'3.0.dev19958'
```
That's really cool!  We should implement this for PlasmaPy also.

The relevant code is in [Astropy's setup.py](https://github.com/astropy/astropy/blob/master/setup.py), and we will need to edit [our own setup.py](https://github.com/PlasmaPy/PlasmaPy/blob/master/setup.py).  It seems like we will need to link to the [astropy-helpers](https://github.com/astropy/astropy-helpers/) repository (as is done in [astropy](https://github.com/astropy/astropy/)) which contains the `get_git_devstr` function that is used.  The other functions in astropy-helpers will probably be helpful for us to use as well.

Thank you!
Nick

**Comment by namurphy** [comment]
Oh!  Another thought.  Confusion sometimes arises when you think you're importing an official release of a package, but you instead import an unstable development version.  Does anyone think it would be helpful to print out something like `"Importing PlasmaPy version 0.1.dev351 (last updated on 2017 Sep 13)"` when running `import plasmapy` if `'dev'` is in the version number?  A drawback might be if it is being re-imported multiple times, in which case there'd be a lot of printing of this message.  I wonder if it could be set so that the message is printed just the first time.

**Comment by AarohGala** [comment]
Hey! I'm new to this and I want to contribute to this. Can you tell how can I start contributing?
