### ISSUE TITLE
Edit gyrofrequency function to better indicate that it's not just for ions

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1169]
The code and docstring for [`plasmapy.formulary.gyrofrequency`](https://github.com/PlasmaPy/PlasmaPy/blob/deddb91ea82473ca2a10414cd54dd96d437fdfff/plasmapy/formulary/parameters.py#L983) currently uses notation that assumes the particles are ions, i.e. the `i` in `ω_{ci}` and `m_i`.  This is probably because `gyrofrequency` was originally written as `ion_gyrofrequency` before being made more general.  We should modify the code and docstring within `gyrofrequency` to indicate that it is not just for ions.

**Comment by sou-joshi** [comment]
Would like to work on this!

**Comment by namurphy** [comment]
> Would like to work on this!

Sure, please feel free to!  And thanks!

**Comment by alfkoehn** [comment]
Sticking to the noting as used in some textbooks (should I provide references for this statement), I would like to suggest to write `\omega_{cs}`. Not sure though if that is compatible with your formatting?
