### ISSUE TITLE
Edit gyroradius function to better indicate that it's not just for ions

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1170]
`plasmapy.formulary.gyroradius` has some code within it that indicates that the particle should be an ion.  In particular, one of the inputs is `T_i`.  We should change the code and documentation to show make it more general (i.e. changing `T_i` to `T`).  This would be a backwards incompatible change so we would probably want to put a deprecation warning for `T_i` and let `T_i` continue to be used for one more release.  

This issue is similar to and a bit more complex than #1169.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
If this issue is up for grabs can I work on this one, Please?

**Comment by namurphy** [comment]
@RAJAGOPALAN-GANGADHARAN — yes, please do!  And thank you!
