### ISSUE TITLE
Describe plasma physics behind upper and lower hybrid frequencies

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1172]
The docstrings for `upper_hybrid_frequency` and `lower_hybrid_frequency` in `plasmapy.formulary` should be expanded to include a description of the physics related to these frequencies, including how they fit in with plasma waves.

**Comment by alfkoehn** [comment]
Looking at the format or rather ordering in the docstring, it seems to me that such information should be added to the "Notes" section, is that correct?

**Comment by namurphy** [comment]
> Looking at the format (or rather ordering/"sectioning") in the docstring, it seems to me that such information should be added to the "Notes" section, is that correct?

Yep, a discussion of the physics associated with these frequencies is probably best put in the "Notes" section.  If there's a short definition, it can be included in the first line of the docstring.  Thanks!

**Comment by alfkoehn** [comment]
now I just need to recall what you just told us about how to create a pull-request in your lecture ;-)
