### ISSUE TITLE
Particle objects with reduced mass ratios

### ISSUE THREAD

**Issue by pheuer** [PlasmaPy/PlasmaPy#1177]
Many PIC plasma simulations use an unrealistic mass ratio (eg. m_p/m_e < 1836) to speed up calculations. In these models, all the quantities that depend on the ion mass are also modified (eg. the ion gyrofrequency is closer to the electron gyrofrequency than in reality).

Does it make sense to add an optional "mass_ratio" keyword to Particle objects that defaults to 1836 but, when set, will reduce the proton/neutron masses? 

Pros: 
- Might be useful for PIC users using the formulary?

Cons: 
- Potentially confusing to have Particle objects with different mass ratios floating around?

Paging @namurphy : patron saint of both `Particles` and cost-benefit analysis. 

Inspired by discussion with @bryancfoo

**Comment by namurphy** [comment]
And yeah, the use of unrealistic mass ratios for PIC simulations is definitely a use case that we need to account for!

**Comment by pheuer** [comment]
I think that could be a good solution!

**Comment by namurphy** [comment]
@pheuer — since we have `CustomParticle` and `DimensionlessParticle` now, would it be reasonable to close this issue?

**Comment by pheuer** [comment]
I think so! Closing now.
