### ISSUE TITLE
Consider splitting up tests into multiple ones per function

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#118]
Let's say I'm debugging `physics.Alfven_speed` after making some changes. I run pytest in my trusty old PyCharm and I run into an error on line 69. I fix that one and run pytest again. Now there's an error on line 79, which the previous test run didn't reach as `assert` failure means executing the code within the test function gets stopped. I fix that one and proceed to repeat until there are no tests failing in `test_parameters`.

That's a lot of test runs, and as our tests increase in number and size, it might not be a scalable solution.

Another approach would be to split the tests into multiple test functions (I'm not 100% sure what's the best approach here, maybe you group those into classes or some such thing). That way, we get instant visual feedback on which tests are working, which are failing and where we need to aim our fixes before running the test suite again. The testing process becomes much more granular\incremental that way.

I believe it would also be handy for automated Travis CI tests, decreasing the number of commit pushes necessary.

There is also a little thing called [pytest fixture](https://docs.pytest.org/en/latest/fixture.html) that'd I'd like to implement later wherever it ends up being applicable. Most of our tests check qualitatively different behaviour, but that may also be useful.

One possible disadvantage of the proposed approach is that the size of our test suite will grow by a bunch, but I think it's only a visual increase - we'd essentially be doing the same number of tests, just with separate labels and in parallel.

Here's a reference to Stack: https://softwareengineering.stackexchange.com/questions/7823/is-it-ok-to-have-multiple-asserts-in-a-single-unit-test

**Comment by thomasjpfan** [comment]
`@pytest.mark.parametrize` can be used as well. For example, this snippet:
```python
def test_Alfven_speed():
    with pytest.raises(ValueError):
        Alfven_speed(B_nanarr, rho_arr)

    with pytest.raises(ValueError):
        Alfven_speed(B_arr, rho_negarr)

    with pytest.raises(u.UnitConversionError):
        Alfven_speed(5*u.A, n_i, ion='p')
```
can be refactored to:
```python
# B, density, kwargs, error
alfven_speed_error_test_cases = [
   (B_nanarr, rho_arr, {}, ValueError),
   (B_arr, rho_negarr, {}, ValueError),
   (5*u.A, n_i, {'ion':'p'}, u.UnitConversionError)
]

@pytest.mark.parametrize(
   "B,density,kwargs,error", alfven_speed_error_test_cases)
def test_Alfven_speed_errors(B, density, kwargs, error):
   with pytest.raises(error):
        Alfven_speed(B, density, **kwargs)
```
I'll work on a pull request for this issue.

**Comment by StanczakDominik** [comment]
Nice! I agree they 'pytest.mark.parametrize' should be great here. I
already started work on that general area with refactoring 'physics', but
this kind of change should be easy to merge, so go right ahead!

22.09.2017 15:51 "Thomas Fan" <notifications@github.com> napisał(a):
