### ISSUE TITLE
Directory of Open Source Projects related to plasma analysis and modelling

### ISSUE THREAD

**Issue by jhillairet** [PlasmaPy/PlasmaPy#1185]
There are a few open-source projects related to plasma-related things, but most often not known by potential users. (it takes time to be known!)

As PlasmaPy is destined to be _the_ community package for plasma science, it would worth being the main entry point to list all projects related to plasma science (being PlasmaPy-affiliated or not), as a kind of directory of plasma-related projects. 

A dedicated webpage listing open-source packages (which could be user-contributed) would hence increase the central role of PlasmaPy in the plasma community.

**Comment by rocco8773** [comment]
@jhillairet We do have this as part of our website, https://www.plasmapy.org/affiliates/.  However, it's currently up to the open-source developers to request to be on the list.  Additionally, this [list (json file)](https://github.com/PlasmaPy/plasmapy.github.io/blob/src/data/affiliated_pkgs.json) is maintained on the website repo and not the `plasmapy` repo.

@namurphy I could see an argument for linking to the affiliated pkgs page from the `plasmapy` README.  What do you think?

**Comment by namurphy** [comment]
> @namurphy I could see an argument for linking to the affiliated pkgs page from the `plasmapy` README. What do you think?

Sounds great to me!

**Comment by jhillairet** [comment]
> @jhillairet We do have this as part of our website, https://www.plasmapy.org/affiliates/. However, it's currently up to the open-source developers to request to be on the list. Additionally, this [list (json file)](https://github.com/PlasmaPy/plasmapy.github.io/blob/src/data/affiliated_pkgs.json) is maintained on the website repo and not the `plasmapy` repo.

Well, the idea is to be more ambitious than just listing affiliated packages, but making a directory of all open-source plasma codes, in which any developer could give the name of the code, URL and one-line description.

**Comment by rocco8773** [comment]
@jhillairet Unless I'm missing something, that is exactly what the website is doing.  If you're talking about having a database where all the possible code sources are located, that is not feasible.  Not only do we not have the people power to do that, but we likely won't have the permissions to do that.  That would create a large maintainer overhead.  The idea with the webpage is that all the code is link, so user can go directly to the project's source and get the project's maintain documentation and source.

**Comment by jhillairet** [comment]
@rocco8773 Indeed the website is referencing affiliated packages, which is very fine and normal. I'm thinking about non-affiliated packages (yet), that would like to be referenced in PlasmaPy. But I realized that this is what you call "community" package, I didn't understood the distinction between affiliated and community, my bad.

**Comment by rocco8773** [comment]
@jhillairet That's fair.  I've been struggling with the "affiliated" vs "community" pkgs myself because I don't think the concept is clearly expressed, i.e. it's not readily apparent.  That's on me since I wrote this up. :/ I just haven't thought a new webpage design that expresses this more clearly.
