### ISSUE TITLE
Test against development version of Python

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1215]
When we set up cron jobs for tests against sphinx-dev, numpy-dev, and so on, another one that would be worth adding is a cron job that tests against the development version of Python.  Given the stability of Python, I'd say this one is much lower priority than the others and could be run less frequently, but it'd give us advance notice if we're using anything that gets deprecated or removed.

**Comment by namurphy** [comment]
Argh.  I accidentally clicked on the button to make this an epic and can't figure out how to un-epic it.  This was an epic fail if there ever was one...  And no, I didn't do this just so that I could make that pun, thanks for asking.

**Comment by StanczakDominik** [comment]
You know, on second thought... I don't think there's going to be an easy way to actually automatically do this. There are no "nightly wheels" or anything for the language itself - just release candidates, and even then the setup-python GitHub action probably won't let us grab those.

So I think it's fine to just manually add the new releases as they come.

I'll close this for now, but if anyone comes up with a way to do this, I'll be happy to reopen it!

**Comment by namurphy** [comment]
> I don't think there's going to be an easy way to actually automatically do this.

Yeah, I can't think of a simple enough way to do this without a lot of effort, especially since we'd probably need to build the other packages we depend on too.  It'd make sense to wait until/if there ends up being a good upstream way to handle this.  Right now it seems like high effort/low gain.

**Comment by namurphy** [comment]
Another reason why testing against the alpha/beta/rc releases of Python would be difficult is that chances are that Numba will not yet be compatible with those pre-releases.
