### ISSUE TITLE
Make sure units are not in math mode in formulary docstrings

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1228]
In the recent documentation guide update, we added a guideline that physics units should not be included as math.  For example, if a docstring has
```rst
:math:`m/s`
```
then it'll show up as _m_/_s_ when it should show up as m/s.  The docstrings for `plasmapy.formulary` should be checked to make sure `:math:` is not used to enclose units.

Superscript powers should be like ```m s\ :sup:`-1` ```.

**Comment by sandshrew118** [comment]
Thanks Dom!

Should this issue be closed? Perhaps it should be moved to some sort of guidelines for developers section so it can stay there forever / future reference.

**Comment by StanczakDominik** [comment]
Yup, it should have been! 😅 Thanks for the reminder!
