### ISSUE TITLE
Reduce the number of CI tests for pull requests and make them cron jobs

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1294]
We run tests under a bunch of different environments on every pull request for different versions of Python and on different operating systems.  It's pretty rare for these tests to provide any unique information, and it can be confusing to tell which test failure to look at first. We also now have weekly tests that we can run.  Plus, there are limits on the number of concurrent GitHub Actions that can be run.  

We should be able to reduce the number of testing environments for each pull request and not run into any problems.  We'd probably need to run at least two environments (with code coverage for at least one):
 - The minimum versions of our dependencies and Python, perhaps on Windows
 - The most recent versions of our dependencies and Python, perhaps on MacOS

The remaining environments could be made into cron jobs.  

Some additional possibilities are...
 - Run only the two testing environments when the pull requests are in draft mode
 - Trigger the full test suite upon pull request approval
 - Have a label that would mark that a pull request should have all tests run

**Comment by StanczakDominik** [comment]
Another possibility here is staging. We run only a quick test suite first. If that passes, great - the tests proceed to a larger suite. I imagine we could also stick test coverage in the latter part!

**Comment by StanczakDominik** [comment]
Closed by #1350
