### ISSUE TITLE
Parametrize tests of `ion_sound_speed`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1304]
The [tests of `plasmapy.formulary.parameters.ion_sound_speed`](https://github.com/PlasmaPy/PlasmaPy/blob/9d67396de74776e4a85a7717fd2dd76fbd6b0063/plasmapy/formulary/tests/test_parameters.py#L349) were written before we learned about the [`@pytest.mark.parametrize`](https://docs.pytest.org/en/6.2.x/parametrize.html) decorator.  

The problem with `test_ion_sound_speed` is that it has a long list of `assert` statements.  If one of the `assert` statements fails, then the following tests don't get run.  That would make it look like we have one test failure when in fact we might actually have a lot of failures.  The way it is set up now also makes the tests difficult to maintain.  

It would be really helpful to go back and [parametrize](https://docs.pytest.org/en/6.2.x/parametrize.html) these tests.  
The current test would probably end up being three parametrized tests... one to test the values, one to test the exceptions with [`pytest.raises`](https://docs.pytest.org/en/6.2.x/reference.html?highlight=raises#pytest.raises), and one to test the warnings using [`pytest.warns`](https://docs.pytest.org/en/6.2.x/warnings.html#warns).

Our [testing guide](file:///home/namurphy/Projects/PlasmaPy/docs/_build/html/development/testing_guide.html) now has quite a bit of information on our tests.  There are also some examples of parametrized tests in [`test_parsing.py`](https://github.com/PlasmaPy/PlasmaPy/blob/9d67396de74776e4a85a7717fd2dd76fbd6b0063/plasmapy/particles/tests/test_parsing.py).

This would probably be a good contribution for someone who would want to learn about our tests.

**Comment by seanjunheng2** [comment]
Hi @namurphy, quite new to this and no guarantees... but wondering if I can take a shot at this issue?

**Comment by seanjunheng2** [comment]
@namurphy I can continue working on ion_sound_speed
