### ISSUE TITLE
Enable a local `.plasmapy` configuration direcory

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#1321]
In recent meetings there's been a discussion on how to manage data in `plasmapy`.  Do we package specific datasets? Do we force users to download their own datasets?  If the later, how do we let `plasmapy` know where these local datasets are so users do not have so specify their location with every new notebook.  With this discussion the idea of a local configuration directory `.plasmapy` came up.   In said directory a `config.toml` or `config.cfg` could exist with entries like...

```toml
[data]
plasmapy-pkg='/path/to/packaged/data'
userdata='/path/to/user/data/dir'
``` 

Of course, this configuration directory could be used for more settings than just the one mentioned.  For example, we could have a `cgs` vs `mks` setting for returned variables.

For reference, it does appear astropy has something similar...

https://docs.astropy.org/en/stable/config/index.html

----
Additionally, `astropy` has their configuration directory placed in the user's home directory and it has global settings.  I'm not opposed to this idea myself, but my original intention was to place it in a working directory so settings can be made per project.

**Comment by StanczakDominik** [comment]
> Additionally, astropy has their configuration directory placed in the user's home directory and it has global settings. I'm not opposed to this idea myself, but my original intention was to place it in a working directory so settings can be made per project.

Just to chime in on this point: it'd make sense to have a hierarchy of priorities:

1. current working directory, to allow overriding settings per project
2. a local user configuration directory
3. a global configuration, packaged with the package itself

Now, 2. can be argued about, but as far as I can tell Astropy sticks itself into `~/.astropy`. This is okay, I guess, but for example Julia has a whole debate going about whether they shouldn't maybe obey the XDG spec: see https://github.com/JuliaLang/julia/issues/4630. Astropy does make reference to the XDG spec:

> And you should see the location of your configuration directory. The standard scheme generally puts your configuration directory in $HOME/.astropy/config. It can be customized with the environment variable XDG_CONFIG_HOME in which case the $XDG_CONFIG_HOME/astropy directory must exist. Note that XDG_CONFIG_HOME comes from a Linux-centric specification (see [here](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support) for more details), but astropy will use this on any OS as a more general means to know where user-specific configurations should be written.

Though it still seems to me like they default to `~`, then. Which is weird.

**Comment by pheuer** [comment]
In #1486 I've now changed the data location to `~/.plasmapy`. Ultimately I agree having this be configurable is desirable, but for now it definitely seems nicer than storing data in the same location as the plasmapy installation, which is what I was doing previously.

**Comment by namurphy** [comment]
Since we have this implemented for data downloading, I'll go ahead and close this.

See also #2600 for a possible path forward for customizing the location of stored data, and https://github.com/heliophysicsPy/standards/issues/28 for a possibility for standardizing this across the heliopythoniverse.
