### ISSUE TITLE
Check whether we need to update our doctests on every Astropy.constants update

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#135]
With #129 in the works and given that

* we have a bunch of functions using those values and numerically they do change
* our doctests check for exact results without going through anything like `np.isclose`

we might be setting ourselves up for some future work and bugs. I'm not sure what the best solution would be here.

**Comment by RoberTnf** [comment]
Maybe hardcode the constants that are susceptible of changing in the tests?

**Comment by StanczakDominik** [comment]
Very likely fixed by #230
