### ISSUE TITLE
Implement Sympy expressions for `physics` functions?

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#136]
Here's an idea - given that we have a bunch of functions already done, perhaps there may be a smart way of implementing versions of those for symbolic manipulation using [SymPy](https://github.com/sympy/sympy/) ? We could have a submodule for this.

This could also go into SymPy upstream, where [searching for plasma related code](https://github.com/sympy/sympy/search?utf8=%E2%9C%93&q=plasma&type=) [and issues](https://github.com/sympy/sympy/issues?utf8=%E2%9C%93&q=plasma) proves uneventful.

**Comment by namurphy** [comment]
I really like this idea!  I had been wondering if we could use SymPy as part of an analytic dispersion solver.

**Comment by StanczakDominik** [comment]
Right we're not sure if this is useful/needed but feel free to reopen
