### ISSUE TITLE
Reimplement `Plasma` numerical solvers via Numba for potential speed increases

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#137]
Given we had a speed problem with the solvers in `Plasma`, here's an idea. How about implementing [numba](https://numba.pydata.org/) versions of those? That might speed things up, especially given that there's this little thing called `numba.cuda` we might also be able to leverage... but I suppose going with straight numba first would make debugging any possible cuda version easier later on.

**Comment by AaruranE** [comment]
Hi, I'm going to start working on this issue.

**Comment by StanczakDominik** [comment]
Hey, awesome! This is definitely not one of the simpler ones, I'm really
looking forward to seeing what you end up coming up with!

I believe the most recent version of the plasma simulation capability is
#33. It'd probably be best if you started working based on that one.

**Comment by lemmatum** [comment]
Could also try converting some lower-level, frequently-used functions to Cython. This is what a lot of packages like scipy, numpy, numba, etc. use under the hood. Cython removes all the overhead associated with figuring out input/output types at runtime by using static typing and using compiled code. Cython plays nicely with Python and doesn't have the GIL (global interpreter lock) so you can more effectively do parallelization/concurrency.

So if you guys are serious about these simulation efforts I'd recommend using Cython.

**Comment by AaruranE** [comment]
That's a good idea, I'll definitely use some Cython to investigate some speed improvements.

**Comment by lemmatum** [comment]
Let me know how it goes! I'm considering incorporating some Cython into SpectroscoPy.

**Comment by v2thegreat** [comment]
Hey, I was planning on making some scripts that would Cythonising python code. Would use the modules for this project be a good idea?

**Comment by AaruranE** [comment]
I haven't made much progress lately, but you're welcome to have a try if that's what you want to do

**Comment by StanczakDominik** [comment]
Closed as yes, we're gonna use numba for simulation but we'll need some actual simulation first
