### ISSUE TITLE
Numba jitted functions are tracted by `coverage`

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#1386]
As stated in [comment (PR1145)](https://github.com/PlasmaPy/PlasmaPy/pull/1145/files#r782341157), when testing the c-complied code generated by `numba` is executed instead of the original python function.  This leads to a gap in the coverage report, so we should work out scheme to handle this.

> Note: Since `thermal_speed_lite` is decorated by `numba.njit`, the code that is actually covered by tests is the c-compiled version and thus `coverage` does not recognize if the python code gets hit.
> 
> For now I'm updating the tests such that the following is essentially done...
> 
> ```python
> lite = thermal_speed_lite(**kwargs)
> pylite = thermal_speed_lite.py_func(**kwargs)
> assert lite == pylite
> ```
> 
> The call to `thermal_speed_lite.py_func` calls the original python function and, thus, is calculated in the coverage report. An alternative to this is to add a scheme to the `excluded_lines` in the `[coverage:report]` settings of `setup.cfg` such that anything decorated with `jit` or `njit` is ignored.

**Comment by namurphy** [comment]
Thanks for raising this!  It would be quite helpful to have something set up so that jitted functions get ignored in coverage reports.  I'm curious if there's anything other packages have done about this that we could duplicate.

**Comment by StanczakDominik** [comment]
Jitted functions are... huh. https://github.com/PlasmaPy/PlasmaPy/blob/a624976bba4c8c843c0934e3cb687dc47e4c56d7/setup.cfg#L235-L241

There should be a `@numba.jit` line here...
