### ISSUE TITLE
Make `IonizationState` and `IonizationStateCollection` tests independent of each other

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1398]
I tried running our tests with the pytest extension pytest-randomly, and it turns out that many of the tests in `plasmapy/particles/test_ionization_state.py` and `plasmapy/particles/test_ionization_collection.py` fail when they are run in random order.  This is because the tests depend on each other, which is generally something to avoid, which I only learned recently.  We should modify these tests so that they don't depend on the order of test execution.  That is to say, we should make these tests completely independent of each other.  

I found this out by running these lines in the command line:

```bash
pip install pytest-randomly
pytest --randomly-seed=1235
```

These tests might be a good place to use pytest fixtures.

**Comment by StanczakDominik** [comment]
This is IIRC dealt with in https://github.com/PlasmaPy/PlasmaPy/pull/1369, which I just have to quickly wrap up.
