### ISSUE TITLE
Create GitHub Action to label pull requests based on number of lines changed

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1404]
I happened across a [GitHub Action that will label pull requests based on the number of lines changed](https://github.com/marketplace/actions/add-size-label-to-pr), and I'm thinking that this would be a good one to add to our automated tasks. 

This GitHub Action would be particularly helpful in helping us triage pull requests for code reviews.  For example, if we're hypothetically in the middle of a global pandemic and are dealing with huge amounts of brain blah, we could pick shorter pull requests to review and get in quickly, and then know to set aside a block of time and coffee for reviewing in-depth pull requests.

This would quite possibly be a good first pull request for someone who would like to gain some experience about GitHub Actions.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@namurphy this seems simple and fun if no one else is interested can I give this a shot?

**Comment by namurphy** [comment]
> @namurphy this seems simple and fun if no one else is interested can I give this a shot?

Please do!  We might need to merge the PR before being able to tell if it's working, so this issue might take multiple PRs.  I might also need to create the GitHub labels that get used too.  Thank you in advance!

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@namurphy what do you think about this [Labeller](https://github.com/marketplace/actions/pr-labeler-based-on-multiple-rules) ,it can also label maintainers name based on the files that were modified, plus calculates exclusion based on regex (might be handy when we want to exclude certain type of files judging the weight)
