### ISSUE TITLE
Typo maybe?

### ISSUE THREAD

**Issue by jeandet** [PlasmaPy/PlasmaPy#1406]
Hello, I was reading you conf.py to steal some bits ;) and I came across this:

https://github.com/PlasmaPy/PlasmaPy/blob/2b798b0902c9e38d23102b79a955bfc961e56c9c/docs/conf.py#L151-L152

Looks like a typo and/or a leftover.

**Comment by rocco8773** [comment]
Looks like you're correct. Thanks for pointing it out. Would you be willing to open a pull request to resolve this?
