### ISSUE TITLE
Numpy isnan bug in plasmapy.formulary.parameters.gyroradius()

### ISSUE THREAD

**Issue by sapols** [PlasmaPy/PlasmaPy#1420]
I recently experienced an error during an ion gyroradius calculation: `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`. The problem seems to stem from the line:

`if not np.isnan(T_i):`
 
in

`plasmapy.formulary.parameters.gyroradius()`

It looks like you're expecting `T_i` to be a scalar but in my case it was an array. 

To reproduce, you can run `plasmapy.formulary.parameters.gyroradius(B, 'p', T_i=T_i)` with a `T_i` that's an array.

**Comment by sapols** [comment]
@namurphy

**Comment by rocco8773** [comment]
@sapols I think the quickest think for you to do to get rolling is to switch from using `T_i` to `T`.  `T_i` is being deprecated this `gyroradius` is supposed to be particle agnostic.  The code that's causing your error is in relation to the "deprecation warning code snippet" and not the actual calculation of `gyroradius`.

**Comment by rocco8773** [comment]
@namurphy I think the easiest way to repair the deprecation warning bit is to have the default value for `T_i` be `None` instead of `np.nan * u.K`.

**Comment by sapols** [comment]
@rocco8773 Thanks for the suggestion! Pardon the novice question, but is that as simple as passing my `T_i` to this function's `T` instead of `T_i`? (I.e. `gyroradius(B, 'p', T=T_i)`?) Or should I recalculate a `T` from my data instead of a `T_i`? Only asking because I found this bug in code I didn't write and don't fully grok.

**Comment by rocco8773** [comment]
@sapols That is correct.  The old version of the code used `T_i`, but we recently changed the temperature keyword to `T` so `gyroradius` would be particle agnostic.  This happened in PR #1210.  Internally, the function is mapping `T_i` to `T` and it's that code that giving you the error, so by just doing `T=T_i` you will bypass the code that's giving you issues.

**Comment by rocco8773** [comment]
If you feel like investigating/exploring more, then the culprit code is...

 https://github.com/PlasmaPy/PlasmaPy/blob/30c3435fe759f8e26d733c63890332b02b86b655/plasmapy/formulary/parameters.py#L1408-L1415
