### ISSUE TITLE
Add `pytest-xdist` to "test" package dependencies.

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#1429]
In PR #1083 the `looponfailroots` pytest configuration was added to our `setup.py`.  However, this is not a configuration variable defined by `pytest` but added to the `pytest` configuration by `pytest-xdist`.  By not having `pytest-xdist` installed, `pytest` issues the following warning...

![image](https://user-images.githubusercontent.com/29869348/154864045-af639043-3234-45c6-bae0-1ca3b435293b.png)

@StanczakDominik Thoughts?

**Comment by StanczakDominik** [comment]
Huh. Either that's a recent change or I just didn't notice one more warning among all the others... Sure, let's bring it in!
