### ISSUE TITLE
Decide on behavior of `ParticleList` when it is provided with a string

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1436]
`ParticleList` accepts iterables.  When provided with a `str`, `ParticleList` will attempt to create a `Particle` or `CustomParticle` from each of the individual characters in the string.  This could be a helpful shortcut in some cases, but lead to unexpected behavior at other times.
```Python
>>> from plasmapy.particles import ParticleList
>>> ParticleList("pe")  # potentially useful shortcut
ParticleList(['p+', 'e-'])
>>> ParticleList("He")  # might expect He instead of H and e⁻
ParticleList(['H', 'e-'])
```
We have a few options for how `ParticleList` should behave, including but not limited to:

 1. Keep the current behavior (to be consistent with how `list` behaves)
 2. Make `ParticleList` raise a `TypeError` when provided with a string

If we keep the current behavior, we would also have the options of:

 3. Include an admonition in the docstring for `ParticleList` about this behavior 
 4. Include an example in the documentation so users would know that this could happen  
 5. Issue a warning for cases like `ParticleList("He")` where the whole string is a valid particle representation.  This could be done with something more or less like:
    ```Python
    if isinstance(particles, str) and len(particles) > 1:
        try:
            Particle(particles)
        except InvalidParticleError:
            pass
        else:
            warnings.warn("...")
     ```

**Comment by namurphy** [comment]
Oh...and for particles that can be represented by a single letter, things serendipitously work out as expected:
```Python
>>> ParticleList("p")
ParticleList(['p+'])
```

**Comment by pheuer** [comment]
I came across this while looking at ParticleLists for #974. 

My vote would be for changing the behavior in favor of a third option: if a string is provided, treat it as a single particle in a ParticleList of only one element. If the string is not a valid Particle, let Particle raise that error.  My second choice would be to have ParticleList raise an exception if it's given a string. 

IMO, the biggest risk is the example `ParticleList("He")` you mentioned above. I think interpreting this as a hydrogen-electron plasma is really unintuitive and subtle for users who aren't familiar with the way Python deals with strings.
