### ISSUE TITLE
Write `Hall_parameter` tests (!?)

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#1442]
While decomposing `plasmapy.formulary.parameters`  for issue #1433 I discovered there are not tests written for the `Hall_parameter`.  So, we need some!!

**Comment by MKastek** [comment]
I can work on this!

**Comment by MKastek** [comment]
But I see that test for Hall_parameter are added: https://github.com/PlasmaPy/PlasmaPy/blob/main/plasmapy/formulary/tests/test_parameters.py

**Comment by StanczakDominik** [comment]
Yeah, but if you look closely this just tests that IIRC importing `Hall_parameter` from just `parameters` rather than from `dimensionless`. It could still use a bunch of value tests, how it behaves at edge cases, `nan`, etc.

**Comment by MKastek** [comment]
> Yeah, but if you look closely this just tests that IIRC importing `Hall_parameter` from just `parameters` rather than from `dimensionless`. It could still use a bunch of value tests, how it behaves at edge cases, `nan`, etc.

Ok many thanks for reply and explaining! So should I prepare this tests in this file: https://github.com/PlasmaPy/PlasmaPy/blob/main/plasmapy/formulary/tests/test_dimensionless.py 😅 ?

**Comment by StanczakDominik** [comment]
Yeah, that sound like a good spot for those :)
