### ISSUE TITLE
Migrate `quantum_theta` and write tests

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#1443]
The `quantum_theta` function should be moved from `plasmapy.formulary.dimensionless` to `plasmapy.formulary.quantum`.  I would have no problem still keeping it exposed in the `dimensionless` namespace.

Additionally, the one test written for `quantum_theta` is not a real test, so a full set of tests need to be written.

**Comment by JaydenR2305** [comment]
@rocco8773 Mind if I try this one?

**Comment by StanczakDominik** [comment]
Go right ahead, @JaydenR2305 :)
