### ISSUE TITLE
Add `ParticleList` method to provide the equivalent molecule

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1457]
I'm thinking that it'd be helpful to have a `ParticleList.as_molecule` method that would use `plasmapy.particles.particle_class.molecule` to provide a compound molecule.

At the moment, this would return a `CustomParticle` or `Particle`.  Eventually this could be changed to return a `Molecule` object, should we decide to add a `Molecule` object to PlasmaPy.

(And I may have accidentally created an epic out of this because I clicked on the wrong button...)

**Comment by Quettle** [comment]
Hi, The issue I see with building a molecule from a `ParticleList` is the lack of information on the molecule geometry. The approach of building a `CustomParticle` from a symbol is to have a container for the mass and charge of the molecule for computation while relying on it's symbol for identification of isomers. From a `ParticleList`, only the general formula of a molecule can be deduced and probably without consistently displaying the elements in the same order.
As for a `Molecule` class, it would require a lot of thought to make them unique without relying on a string equality like with the current system. However It might be really helpful to store more data on the species, as `CustomParticle` only has three components. For example I currently use the symbol field to store more information such as the excitation state of a specie.
