### ISSUE TITLE
Turn docstrings into raw strings

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#146]
As seen in #145, it turns out you need to use raw strings (`"this is not a raw string", r"but this is because of the prepended r"`) for docstrings if you want to have LaTeX formulas rendering properly via Sphinx. We could probably use some help with this one - basically, this means going through all the files with some clever regex substitution or something.

**Comment by raajitr** [comment]
Hi, I would like to take this.
Do we have to convert docstrings of all the py files to raw string or only those which have backslash in them?

**Comment by StanczakDominik** [comment]
Heey @raajitr, thanks for offering to deal with this one!

Converting docstrings with LaTeX formulas (and thus backslashes) in them would be enough and much appreciated, we can try to remember to turn the others into raw strings. Converting them all in one sweep would be awesome though, as most of our docs will probably include formulas sooner or later!
