### ISSUE TITLE
Improve CONTRIBUTING.md documentation

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#151]
This is mostly a note to myself to add the notes I've taken on this process to the documentation. Things to include:
* How to setup virtualenv
  * export LD_LIBRARY_PATH when setting up virtualenv on Linux
  * No spaces allowed in path names
  * How to activate virtualenv
  * Installation of plasmapy dependencies in virtualenv
  * `python setup.py develop` command
* How to test/run newly written functions
  * import plasmapy.blah.blah in the virtualenv

**Comment by lemmatum** [comment]
Looks like we have a minor issue in #160 , and then this will be ready to close soon.

**Comment by StanczakDominik** [comment]
Closed by #160, #161 and possibly some more
