### ISSUE TITLE
Create a `RelativisticBody` class

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1539]
Right now it's pretty inconvenient to have a particle and go between velocity, Lorentz factor, energy, and momentum.  It'd be helpful to have a `RelativisticParticle` class that we could use to take one such quantity and make it straightforward to calculate the rest.  I was thinking that this would be best in `plasmapy.formulary.relativistic`.

Some of the input parameters could be `particle`, `V`, `gamma` (for Lorentz factor), `kinetic_energy`, and `momentum`. Some of the attributes could be `rest_mass`, `relativistic_mass`, `total_energy`, `kinetic_energy`, and `mass_energy`.  There could also be an attribute like `v_over_c`, which is often referred to as `beta`, but that could potentially be confused with plasma beta.  

I'm wondering if we could even define the dunder methods for `__add__` and `__subtract__` so that we could do things like...
```Python
>>> cosmic_ray = RelativisticParticle('p+', energy = 100 * u.GeV)
>>> cosmic_ray += 50 * u.GeV  # would increase the energy of the particle by 50 GeV
```

Doing this would make #1538 a lot easier, and it's related to #1537 too.

**Comment by namurphy** [comment]
I'm wondering about the name for this, since `RelativisticParticle` and `Particle` would have very different purposes.  It could be `RelativisticObject` or `RelativisticBody`, which would probably be better than `RelativisticThing`, `RelativisiticStuff`, or even `RelativisticCorporeality`.

**Comment by StanczakDominik** [comment]
I do like `RelativisticBody` for this.
