### ISSUE TITLE
Expand Coulomb logarithm functionality

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#154]
The `Coulomb_logarithm` function in [`transport.py`](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/physics/transport.py) presently uses a classical approach for calculating this quantity.  The outer impact parameter in the derivation is the Debye length, and the inner impact parameter is the larger of either the de Broglie wavelength or the impact parameter corresponding to a deflection of pi/2.  This formulation generally works for situations where the plasma parameter is significantly greater than 1, and fails for strongly coupled plasmas where other formulations are needed.  The calculation for Coulomb logarithm is at best accurate to about 10% to 20%, so refinements of order ~1% will not realistically affect the results.  However, the Coulomb logarithm comes up extremely frequently when describing anything related to collisions in plasmas, so we should make sure to do a good job with this function.

I've been talking with several people who know much more about Coulomb logarithms than I do, and some of the considerations that they have brought up are:

- The most general and accurate way to calculate the Coulomb logarithm is to integrate over both velocity distributions.
- It would be helpful to allow us to specify the inner impact parameters as an input.  In PIC simulations, for example, the inner impact parameter is more realistically the cell size.  It's also important to take into account the particle shape representation
- Likewise, it would be helpful to allow for different outer impact paramters (e.g., for projectile particles with a particular velocity).  It won't necessarily be just the Debye length.
- @lemmatum pointed out that there are six different ways to calculate the Coulomb logarithm for dense plasmas described by [Gericke, Murillo, and Schlanges (2002)](https://link.aps.org/doi/10.1103/PhysRevE.65.036418).  

I am not an expert in plasma transport theory, so I will pose the question: **In what ways should we generalize our calculations for Coulomb logarithms?**

Related: #35, #60

**Comment by lemmatum** [comment]
What else needs to be done towards this issue?

**Comment by namurphy** [comment]
I think we've taken care of everything for this, so I'll close this.
