### ISSUE TITLE
Missing factor of Z in fundamental collision frequency

### ISSUE THREAD

**Issue by ChrisArran** [PlasmaPy/PlasmaPy#1545]
Hi, I think the function `formulary.collisions.fundamental_electron_collision_freq` is calling `collision_frequency` incorrectly by using the electron density `n_e` rather than `n_i`. In the input description for `collision_frequency` it specifies that for electron-ion collisions `n` should be the ion density, and in `fundamental_electron_collision_freq` it explicitly sets the species as `[ion, "e-"]`.

I noticed this problem while checking the Spitzer thermal conductivity and spotting that the Z dependence comes out wrong. The original Spitzer-Harm paper PR 89, 5 (1953) gives the Z dependence in the conductivity K as delta_T * epsilon / Z. In the current implementation, however, the Z dependence in K comes from kappa_hat (giving delta_T * epsilon) and 1/collision_frequency, where it's proportional to n*b_perp^2, which is proportional to n_e*Z^2. That gives a Z dependence of delta_T * epsilon/Z^2, which will go very wrong for high Z. If instead we call `collision_frequency` using n_i=n_e/Z, it should give n_i*Z^2=n_e*Z, giving a final Z dependence of delta_T * epsilon/Z, as required.

https://github.com/PlasmaPy/PlasmaPy/blob/2a138014b5789a816dc89c87859b5107b62ab176/plasmapy/formulary/collisions.py#L1195

**Comment by rocco8773** [comment]
@ChrisArran Welcome, and thank you for submitting this issue (and a corresponding PR #1546)!  This bit of code was written before I joined PlasmaPy, so I'm not too familiar with it.  Give me some time and I'll do some investigation.  What you suggest seems reasonable though.
