### ISSUE TITLE
Fix math in docstrings so that it shows up correctly on Read the Docs

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#155]
Several mathematical expressions were included in docstrings before we had completely set up the [PlasmaPy Read the Docs page](http://plasmapy.readthedocs.io/en/latest/).  Some of these untested docstrings are rendering incorrectly on the documentation page.  We will need to go through and change the docstrings so that they do show up correctly.  The following pages look like they require fixes:

- [Math](http://plasmapy.readthedocs.io/en/latest/math/index.html) from [`math.py`](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/math/math.py)
- [Physics](http://plasmapy.readthedocs.io/en/latest/physics/index.html) from [`parameters.py`](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/physics/parameters.py), [`quantum.py`](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/physics/quantum.py), [`relativity.py`](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/physics/relativity.py), and [`transport.py`](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/physics/transport.py)

Thank you!

**Comment by jasperbeckers** [comment]
I'll tackle this, seems like a good opportunity to get my GitHub set up correctly and get familiar with the code. Is there any way to build and view the Docs locally?

**Comment by StanczakDominik** [comment]
If this kind of bug pops up anywhere else, it's probably best to reopen this issue rather than start a new one :)
