### ISSUE TITLE
Unexpected behaviour in 'Particle' when the argument has a trailing space

### ISSUE THREAD

**Issue by Quettle** [PlasmaPy/PlasmaPy#1553]
## Reporting a bug

- [x] I am using the latest released version of PlasmaPy (most recent is visible in
 the release notes (http://docs.plasmapy.org/en/stable/about/release_notes.html).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I have noticed a strange behavior when a 'Particle' is created from an atom symbol with a trailing space, the result is a negative ion. For example:

```python
>>>import plasmapy
>>>plasmapy.particles.Particle("He ")
Particle("He 1-")
```
I think the issue is in _parsing.py::extract_charge and could easily be fixed.
I suppose this case should raise an exception as it is the case with `Particle("e ")`.

**Comment by Quettle** [comment]
It seems that an empty string is a valid roman numeral. the issue is caused in _parsing.py line 186 (on main). Possibles fix are either changing the regex that validates roman numerals, or catching the issue earlier by detecting trailing spaces in the argument validation function.

**Comment by rocco8773** [comment]
Thank you for bring this up!  I agree this looks like it's an issue in `_parsing.extract_charge()`.  Specifically I think it's a "bigger" issue related to how that if clause your referenced is splitting the string based on `" "`.  For example, you also get errors doing `"Ar +1"` (2 blank spaces between `Ar` and `+1`) while you'd expect it to default back to `"Ar +1"` (1 blank space).
