### ISSUE TITLE
`plasma-calculator` does not launch on a Windows 10 system

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#1612]
Original comment...https://github.com/PlasmaPy/PlasmaPy/pull/1610#discussion_r912220976

The `plasma-calculator` does not launch when using a Windows 10 system...

> Also, I get an error when trying to run the calculator on my windows machine...
> 
> ![image](https://user-images.githubusercontent.com/29869348/176960605-65eb86ed-4d28-4236-938f-f545927b70f8.png)
>
> My suspicion is whatever functionality is generating the file path is ignorant of a windows file separator, since the path and file name are mashed into one without a separator.

**Comment by namurphy** [comment]
Here are the [lines](https://github.com/PlasmaPy/PlasmaPy/blob/ddc38b0f6cd0f019de7048a38bd8320231752bf0/plasmapy/utils/calculator/__init__.py#L37) that are getting the module path:
```Python
    module_path = os.path.dirname(os.path.abspath(__file__))
    computed_calculator_path = os.path.join(module_path, "plasma_calculator.ipynb")
```
I can't find any issues with it, but I'm wondering if it needs to be made into a raw string or something.  My mini-computer with Civilization IV as an operating system also has a dual boot with Windows 11...but the fan broke so I won't be able to test it locally.

**Comment by rocco8773** [comment]
Not sure.  It'd likely just modify the code to use `pathlib` functionality instead, since `pathlib` is smart to the OS.

**Comment by namurphy** [comment]
One would have hoped that `os` was smart to the OS too, but alas!  I'll attempt to use `pathlib` for this now, though let me know if you've already started to work on it.

**Comment by rocco8773** [comment]
I've dug into this a little bit...it's not an issue with building the path but with `shlex.split()`.  Specifically with the `posix` keyword.
