### ISSUE TITLE
Set up `setuptools_scm` in `pyproject.toml` rather than `setup.py`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1618]
The use of `setuptools_scm` in `setup.py` has been deprecated, and now the [recommended way](https://github.com/pypa/setuptools_scm/#pyprojecttoml-usage) is to use `pyproject.toml`.

**Comment by rocco8773** [comment]
[It is already setup in our `pyproject.toml`](https://github.com/PlasmaPy/PlasmaPy/blob/144c99f7513003d5253bf45e4922daac805435a5/pyproject.toml#L1-L4), but without the `[toml]` option.

**Comment by namurphy** [comment]
By gum, you're right!  I got confused by the `use_scm_version` keyword in `setup` in `setup.py`.
