### ISSUE TITLE
Use `importlib.metadata` to get package version instead of `pkg_resources`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1620]
Now that we're using Python 3.8+, we should switch to using `importlib.metadata` to get our version at runtime in `plasmapy/__init__.py`.  We're using `pkg_resources` right now, but that has a "[significant runtime cost](https://github.com/pypa/setuptools_scm/#retrieving-package-version-at-runtime)".

**Comment by MKastek** [comment]
I can work on this! 😄
