### ISSUE TITLE
Set up nightly wheels using GitHub Actions

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1629]
Following up on #1628, it'd be helpful to build our own nightly wheels that downstream packages can use for tests against the development version of PlasmaPy.  We would hopefully be able to adapt the code that Astropy uses to create these wheels, so I'm hoping this won't require a huge amount of effort.

**Comment by rocco8773** [comment]
I'm not opposed to this idea, but I'm not sure how many packages out there actually depend on us.  I would prioritize something like a fortnightly `beta` release over this.

**Comment by namurphy** [comment]
Agreed.  I think it'll be helpful to do the nightly (weekly?) wheels eventually since it'll make it easier for other packages to depend on PlasmaPy, but this is low priority at the moment.  Tests using nightly wheels would be useful to include in a template for affiliated packages, but that's also for the future.

**Comment by namurphy** [comment]
Closing this since it's probably not worth the effort anytime soon.  I'll add a label to revisit this in a few years and possibly reopen it.
