### ISSUE TITLE
Functions for x-ray matter interactions

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#164]
I'm thinking something like a web interface for pulling down filter transmissions from Henke's [site](http://henke.lbl.gov/optical_constants/). Or get our hands on the data/functions and implement the calculations ourselves.

**Comment by wtbarnes** [comment]
I think [this package](https://github.com/ehsteve/roentgen) from @ehsteve is probably relevant. Not a web interface, but an API for x-ray interactions with matter.

**Comment by lemmatum** [comment]
Looks potentially useful. Not much in the way of contributors though, eh?

**Comment by ehsteve** [comment]
hello, yes I did also grab all of that information already. I'd be happy for this work to get incorporated into a package that might be less niche (and therefore get more users).

**Comment by ehsteve** [comment]
I also tried to make the file with the data easily usable by others so it could just be slurped up by plasmapy if you'd rather go that route.

**Comment by lemmatum** [comment]
@ehsteve So are you pulling this data from Henke or do you have equations built-in for calculating transmission curves?

**Comment by lemmatum** [comment]
This can probably be moved to SpectroscoPy.
