### ISSUE TITLE
Collisions and Transport

### ISSUE THREAD

**Issue by samurai688** [PlasmaPy/PlasmaPy#166]
Hi all,

I've been reading through the code and trying to learn about git and style guides and testing and so forth. It looks great!

In terms of content, I think some good additional features for the package could be: 
- some functions to calculate classical transport coefficients, e.g. Spitzer / Braginskii conductivities
- to add functionality from pages 31-34 of the plasma formulary, to do with collisions and transport

The above are useful but annoying to calculate, would be nice to have wrapped up in a code package such as this one. I'm hoping I'll be able to contribute these once I'm up to speed with how to write code that doesn't make your eyes bleed.

Thoughts? Should they go in the existing transport module? I was thinking maybe the transport module since the collisions stuff all needs coulomb log.

Sam

**Comment by lemmatum** [comment]
@samurai688 , I think this is covered by #35

**Comment by samurai688** [comment]
Oh, yeah indeed that looks like it covers the Braginskii theory.  I don't think that one explicitly mentions like the coulomb collisions stuff though, so like ion slowing times, temperature equilibration, and such.
