### ISSUE TITLE
Make `Lorentz_factor` accept & return NaN values

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1672]
Right now, `plasmapy.formulary.relativity.Lorentz_factor` does not accept a velocity with a magnitude of [`np.nan`](https://numpy.org/doc/stable/reference/constants.html#numpy.nan) (i.e. if we set `V = np.nan * u.m / u.s` or have `nan` in a `Quantity` array with the appropriate units).  The desired behavior would be for `Lorentz_factor` to accept `nan * u.m / u.s` value and then return `nan`, including when `nan` shows up in an array.  The reason is that we sometimes might want to perform a calculation on an array with bad data or with some elements undefined.

**Comment by StanczakDominik** [comment]
For bonus points, ensure that the following work (in other words, that Lorentz_factor behaves like a numpy ufunc):
```pycon
>>> Lorentz_factor(1 * u.m/u.s)
... (numerical)
>>> Lorentz_factor(np.nan * u.m/u.s)
np.nan
>>> Lorentz_factor(1)
... (numerical with warning that m/s is assumed)
>>> Lorentz_factor(np.array([np.nan, np.nan]) * u.m/u.s)
np.array([np.nan, np.nan])
>>> Lorentz_factor(np.array([1, np.nan]) * u.m/u.s)
np.array([... (same as before), np.nan])
```
