### ISSUE TITLE
Create physics exceptions and warnings

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#168]
Several of the exceptions and warnings that come up in PlasmaPy result from when we try to violate the laws of physics.  Most of the time these violations cause a `UserWarning` or raise a `ValueError`, but these are pretty generic and don't give much insight into the cause of the problem.  To help with exception handling, I propose that we create new exceptions and warnings, such as `PhysicsError` and `PhysicsWarning`.  We could additionally be more specific and also have `RelativityError` and/or `RelativityWarning`.  One possibility would be to put these in a new file called `plasmapy/utils/exceptions.py`.

This would be a good first contribution for someone who is somewhat familiar with Python.  Here's documentation on [user-defined exceptions](https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions.  Thank you!

**Comment by samurai688** [comment]
I think I could give this a shot.  I was actually meaning to ask about the warnings situation, right now whenever I calculate a maybe-relativity-is-important parameter it gives me a UserWarning that will stop execution if I don't catch it. It seems a bit aggressive, would we rather generate / display these warnings in a non-halting way?

**Comment by namurphy** [comment]
Good catch!  A while ago I had put in some `raise UserWarning` statements.  We decided afterwards change them to use `warnings.warn` because of the problem you're bringing up, but it looks like we missed a few in `plasmapy/utils/checks.py` and maybe elsewhere.  That would be a good thing to fix too!
