### ISSUE TITLE
Move from `setup.py` and `setup.cfg` to `pyproject.toml`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1680]
The Python community has been converging on using [`pyproject.toml`](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/). The old way of doing it with `setup.py` and `setup.cfg` is [now considered legacy](https://pip.pypa.io/en/stable/reference/build-system/setup-py/).  The Python Packaging User Guide's tutorial on [packaging Python projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/) now includes `pyproject.toml` and doesn't include `setup.cfg` or `setup.py`.

We should move away from using our [`setup.cfg`](https://github.com/PlasmaPy/PlasmaPy/blob/main/setup.cfg) for configuration and packaging stuff when we have the option to, and instead use our [`pyproject.toml`](https://github.com/PlasmaPy/PlasmaPy/blob/main/pyproject.toml) file.  We should also drop our [`setup.py`](https://github.com/PlasmaPy/PlasmaPy/blob/main/setup.py`) and have `pyproject.toml` handle those responsibilities.

We are also currently using `setup.cfg` for configuring `flake8`, `pytest`, `coverage`, and `codespell`.  We should move the configurations out of `setup.cfg` and into `pyproject.toml` or elsewhere, probably splitting this up into multiple smaller pull requests to make each individual chunk more manageable.

This isn't high priority, but it would be good to do this in the next year or two.

**Comment by StanczakDominik** [comment]
I've taken the liberty of adjusting the labeling here a little - this can essentially be done by trial and error, which is how I'm gonna tackle it if nobody wants to try in the meantime 😄

**Comment by namurphy** [comment]
I looked into using `pyproject.toml` for flake8, and found that flake8 doesn't support `pyproject.toml`, and is unlikely to support it in the next few years (see https://github.com/PyCQA/flake8/issues/234). However, we could use [Flake8-pyproject](https://pypi.org/project/Flake8-pyproject/) in order to switch to `pyproject.toml`.

**Comment by Cadair** [comment]
Cross posting from wtbarnes/fiasco#189:

Note that not having a setup.py file present in the repo requires a (at the time of writing) very new version of pip to support development installs.

Having a two line setup.py file and moving everything else in to the other config files is what I would currently recommend.

**Comment by namurphy** [comment]
That's an important point.  Doing `pip install -e .` with a project containing `pyproject.toml` but not `setup.py` requires pip ≥ 21.3, which was released about 1.7 years ago.  

With pip 21.2, it gives the following error along with a warning to upgrade pip...thought the warning does not say that upgrading to the newest pip would allow editable installs.  

```console
$ pip install -e .
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/namurphy/Projects/PlasmaPy
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
WARNING: You are using pip version 21.2; however, version 22.3.1 is available.
You should consider upgrading via the '/home/namurphy/miniconda3/envs/old_pip_editable_installs/bin/python -m pip install --upgrade pip' command.
```

Adding `pip >= 21.3` to the requirements in `pyproject.toml` didn't work either (though I wasn't really expecting it to).   

Whenever we do remove `setup.py`, we should add a note in the contributor guide to update pip to the newest version.

**Comment by StanczakDominik** [comment]
Eeeeeh, I personally don't consider, for a new contributor, `pip install --user --upgrade pip` to be that big of an ask! But I tend to want to move fast on these issues and take such things for granted, so I'm fine with the two-line setup.py solution.

**Comment by namurphy** [comment]
> Eeeeeh, I personally don't consider, for a new contributor, `pip install --user --upgrade pip` to be that big of an ask! But I tend to want to move fast on these issues and take such things for granted, so I'm fine with the two-line setup.py 

Thinking back to the reasoning in [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), it's probably best to have a two-year window for things like this.  though I am quite eager to offer a kind goodbye and thank you to `setup.py`.

**Comment by Cadair** [comment]
I don't think this is a massive issue, mainly because it only affects people who want to do development installs. That being said, depending on how you installed Python upgrading pip isn't always the easiest thing. On the other side, keeping a two line setup.py file around is hardly tragic :wink:
