### ISSUE TITLE
Switch to using `pathlib` instead of `os.path`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1684]
In newer Python code, it's generally recommended to use [`pathlib`](https://docs.python.org/3/library/pathlib.html) instead of `os.path`.  There are [a few places where we use `os.path`](https://github.com/PlasmaPy/PlasmaPy/search?q=os.path+-plasmapy_sphinx) where we should switch to `pathlib`. 

There are also [places where we are using `pathlib`](https://github.com/PlasmaPy/PlasmaPy/search?q=pathlib&type=code) which could be used as examples.  

We shouldn't make this change in `docs/plasmapy_sphinx` since that's being moved to another package (#1643).

Thanks!

**Comment by MKastek** [comment]
I can work on this issue :)!
