### ISSUE TITLE
Replace fundamental collision frequencies with CollisionFrequencies

### ISSUE THREAD

**Issue by pheuer** [PlasmaPy/PlasmaPy#1699]
I think the functions `plasmapy.formulary.collisons.fundamental_ion_collision_freq` and `plasmapy.formulary.collisons.fundamental_electron_collision_freq` are closely related to the `collision_frequency` function, which is set to be deprecated in favor of the new `CollisionFrequencies` class introduced by #1676.  When that happens, these other functions will also need to be rewritten in terms of the new `CollisionFrequencies` class.

**Comment by JaydenR2305** [comment]
I think its natural that I should give this one a try

**Comment by JaydenR2305** [comment]
![image](https://user-images.githubusercontent.com/109694185/187036250-77101aa1-8308-4fb1-8d46-75f48b422e5e.png)

@pheuer Doesn't this mean we can just deprecate those functions as well since they are just special cases ?

**Comment by pheuer** [comment]
@JaydenR2305 I think they are almost identical. but isn't the factor of 4/3sqrt(pi) additional here? I think this has to do with some averaging? The Callen book may have more detail.

**Comment by pheuer** [comment]
Reading the docstring for the existing functions, yes this is just a special case of the general CollisionFrequency but with this averaging term. I think it should be implemented as another attribute, just like you did with Lorentz_collision_frequency. I do not know enough transport theory to explain in what cases this is the relevant frequency... @namurphy or @StanczakDominik ?

In terms of tests, it might make sense to test it against the formula in the NRL formulary (pg. 33) noted in the docstring of the original function.

**Comment by StanczakDominik** [comment]
Good question :(

I'd definitely agree with deprecating the existing ones and providing a simple wrapper like with `Lorentz_collision_frequency`.
