### ISSUE TITLE
Remove upper limit on version of `towncrier`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1711]
Version 22.9.0 of [towncrier](https://towncrier.readthedocs.io/en/latest/) was just released, and it started causing some documentation build errors like:

```
/home/runner/work/PlasmaPy/PlasmaPy/docs/whatsnew/dev.rst:3: CRITICAL: render_fragments() got multiple values for argument 'top_underline'
/home/runner/work/PlasmaPy/PlasmaPy/docs/whatsnew/index.rst:11: WARNING: toctree contains reference to document 'whatsnew/dev' that doesn't have a title: no link will be generated
```

In #1710, there was an upper limit placed on towncrier.  We should update PlasmaPy so that it becomes compatible with the newest release of towncrier, in particular since upper limits on versions increase the likelihood of a version conflict.

**Comment by ConorMacBride** [comment]
This issue should be resolved when https://github.com/OpenAstronomy/sphinx-changelog/pull/14 is released.
