### ISSUE TITLE
Fix errors in `CODEOWNERS`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1738]
GitHub is saying that there's an error in [`CODEOWNERS`](https://github.com/PlasmaPy/PlasmaPy/blob/main/CODEOWNERS), which we need to fix.  I'm not sure what the error is though.

**Comment by StanczakDominik** [comment]
Test closure as wontfix

**Comment by StanczakDominik** [comment]
Actually Erikfix'd
