### ISSUE TITLE
Equations of state

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#175]
Having a few common equations of state could be handy, especially for simulations. I believe there are also some EOS that relate things like incident laser energy to shock strength, which would be handy for experimentalists. 

The implementation would need some thought. Do we create a separate Python function for each parameter in an EOS? Do we create one function representing a single EOS, take the unknown parameter as argument, and then return a function for that parameter (probably using closures)?

Easy place to start is with the ideal gas law. Then we could include plasma specific EOS based on virial theorem.

**Comment by samurai688** [comment]
EOS would be great. I agree, ideal gas is the place to start.

To get fancier than that, my favorite general-purpose EOS is this "QEOS" based on this [paper by More et. al](http://aip.scitation.org/doi/abs/10.1063/1.866963). Writing an implementation would be a significant project, I attempted it once and got it kind of working, but had some lingering issues that I never fixed. I know there is a German group that has written an implementation of it called MPQeos and they say on [their website](http://www2.mpq.mpg.de/lpg/grouphp/AKemp/mpqeos.html) that it's publicly available.

There are the [SESAME tables](http://www.lanl.gov/org/padste/adtsc/theoretical/physics-chemistry-materials/sesame-database.php) from Los Alamos. We could engage them about it, I think in theory they have mechanisms to authorize stuff to be out on github, but I have a feeling it might become way more bureaucratic than we are able to handle, and I wouldn't expect anything to happen quickly.

**Comment by lemmatum** [comment]
@samurai688 I was hoping to keep this function based and to avoid tables 😆

**Comment by samurai688** [comment]
Okay, sounds good! Yeah you might like the QEOS one, in that at least it has functions to generate the tables arbitrarily... but yeah, I don't know of anything but ideal-gas type that are reasonable to be run inline.

**Comment by lemmatum** [comment]
Shall we make this into its own file and call it `equationsOfState.py`? We can then have `import equationsOfState as eos` 😁

**Comment by lemmatum** [comment]
Perhaps we can implement an ideal gas function that takes keyword arguments and can figure out what parameter is missing, and then solve that one?

There was a recent [Python Bytes episode](https://pythonbytes.fm/episodes/show/75/pypi.org-officially-launches) which mentioned [this article](https://treyhunner.com/2018/04/keyword-arguments-in-python/) talking about how to use keyword arguments such that attributes are exposed in the documentation. Might be worth a look for implementing the ideal gas function.
