### ISSUE TITLE
Add Python 3.11 to the test suite

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1767]
### Feature description

We will need to add a testing environment for Python 3.11.

### Motivation

Python 3.11 was released yesterday, and there was much rejoicing.

### Implementation strategy

This will have to go in `tox.ini` and/or our `.github/workflows/testing.yml` (or possibly `noxfile.py` if #1734 is merged).

### Additional context

It will probably take a few weeks for NumPy to become compatible with Python 3.11, and probably ∼1–3 months for Numba to become compatible with Python 3.11 too.

**Comment by namurphy** [comment]
An additional thought: since Python 3.11 has [significant performance improvements](https://docs.python.org/3/whatsnew/3.11.html#faster-cpython) compared to older versions, it would probably be worth doing our test documentation builds on 3.11 to save time.

**Comment by StanczakDominik** [comment]
I don't expect those speedups to be that large for our use case because our codebase is mostly numpy-based. For particles, mayhaps a bit. Still, I'll run a comparison just to be sure.

**Comment by namurphy** [comment]
Agreed that the speedups will probably not impact most of our regular tests, with the possible exception of particles that you mentioned.  What I'm mostly wondering is how much 3.11 would (hopefully!) speed up Sphinx, apart from maybe notebooks.

**Comment by sapols** [comment]
@namurphy question: Does PlasmaPy not officially support Python 3.11 yet? I just failed to pip install plasmapy in an environment with 3.11; the pip install failed because plasmapy needed numba which only works for Python versions 3.7–3.10.

**Comment by namurphy** [comment]
Correct, we need to wait until Numba comes out in order for a new version of Python to be supported. Reading through Numba issues, it might still end up being a few weeks before a release of Numba that is Python 3.11 compatible will come out (partially because they were waiting on an upstream task, I think).  We started a branch to switch to Cython instead of Numba exactly because of this issue, but we haven't had the time to finish it yet.

**Comment by sapols** [comment]
All good! Thanks for the quick status update.
