### ISSUE TITLE
Sensible plot defaults

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#177]
It would be useful to have some sensible plot defaults based on matplotlib to visually unify any examples we generate in the documentation.

These could also be used for generating publication quality plots (like for #159 ) and sort through some of the hiccups in matplotlib (e.g. unifying LaTeX rendered fonts with regularly rendered fonts, line plots with shaded regions representing errors, etc.).

**Comment by lemmatum** [comment]
For the plot defaults, we should keep in mind accessibility issues like color-blindness. I would lean towards more pastel colors and textured lines, and avoid red-green and blue-purple combinations. The latest major version of matplotlib has already established improved defaults in this regard.

**Comment by tulasinandan** [comment]
@lemmatum I think based on the discussion on matrix, I agree that we should add a custom matplotlibrc file. Maybe we could start with your file as a starting point? I could help with this.

**Comment by lemmatum** [comment]
@tulasinandan So this depends on what approach we would like to take. In my scripts I don't use a matplotlibrc file, rather I use a python script that I import as a module and that dynamically sets up all the necessary rcParams. Here is a [page](https://matplotlib.org/users/customizing.html) which discusses both techniques.

Thoughts?

**Comment by tulasinandan** [comment]
I would say the second way would be best for PlasmaPy. We could include a plasmaplotdefaults file and import it in our plotting methods.

**Comment by lemmatum** [comment]
Alright, I'll make a PR with my plot defaults file once I finish conference stuff this week.

**Comment by tulasinandan** [comment]
Great!
