### ISSUE TITLE
Add new syntax to represent isotopes?

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#178]
Current, isotopes are represented with strings like `'H-1'`, `'D'`, and `'helium-4'`.  In #169 it was brought up that isotopes can also be represented as something like `'6Li'` in addition to `'Li-6'`.  This can be mostly incorporated by letting `isotope_symbol` in `atomic.py` take in something like `'6Li'` and returning `'Li-6'`.  

One place where this will end up being a bit more complicated is in `nuclear_reaction_energy` since that function currently allows that format where the `'6'` in `'6Li'` would be treated as a multiplicative factor (e.g., six lithium atoms).  The way to resolve this would be by changing the multiplier format to require an asterisk: `'2*Li-6'` or `'2*6Li'`.  There will probably be a few other places that I'm forgetting too.

Thank you!

**Comment by lemmatum** [comment]
`6Li` and `6*Li` look very similar to me and it is not immediately obvious that one refers to an isotope while the other refers to 6 Lithium ions. It is also quite fragile to typos.
Is there are clearer way to distinguish the two, perhaps by forcing `element-number` for isotopes and `number*element` for reaction quantities?
