### ISSUE TITLE
Taking care of people signing off in authors is hard, let's automate it

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#1780]
> Yeah, this part is tough!  I've had to do some manual interventions in the past for commits that were co-authored by a new contributor.  I've been thinking about ways to auto-generate the author list from `CITATION.cff`, in which case it would be really helpful to have a linter check that the GitHub usernames of the authors are in `CITATION.cff`, which would hopefully eliminate the need for manual intervention.

_Originally posted by @namurphy in https://github.com/PlasmaPy/PlasmaPy/issues/1779#issuecomment-1298828655_

This is a great idea and does not sound difficult:

1. get the PR author username via something such as https://github.com/orgs/community/discussions/25502
2. write a script to parse CITATION.cff (it's a yaml, see #1779 for an example of how to do it) to make sure it's in there; `sys.exit(0 if its_in_there else 1)`
3. stick that into a github action, maybe even tied to the first-contributor-comment one? Or linters, or testing? Not sure yet.

**Comment by MKastek** [comment]
I am in :)

**Comment by StanczakDominik** [comment]
Awesome :)

**Comment by MKastek** [comment]
@StanczakDominik is this still available, unfortunately I have not been available lately?

**Comment by namurphy** [comment]
Yes, this is still available if you would like to work on it.  Thank you!

**Comment by namurphy** [comment]
Closed by #2155.
