### ISSUE TITLE
CSS issues with todays release of `sphinx_rtd_theme==1.1.0`

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#1784]
### Description

Today's release of `sphinx_rtd_theme==1.1.0` has changed the wrapping behavior of links, which is creating a poor display of `autosummary` tables.

### < 1.1.0

![image](https://user-images.githubusercontent.com/29869348/199375698-2524fb8d-1c37-4da6-86dd-b77e23d9054f.png)

### == 1.1.0

![image](https://user-images.githubusercontent.com/29869348/199375743-3bd53226-8448-4722-b31a-a14b1f25669b.png)

---

This is a result of them adding the following rule to `theme.css`.

```css
.rst-content p a {
  overflow-wrap: anywhere;
}
```

I believe this was done in https://github.com/readthedocs/sphinx_rtd_theme/pull/1193.

---

I don't have an overriding CSS rule yet.  Maybe something that does not allow wrapping when the content is code.  Not sure.

I think for the time being we should restrict our dependency to `sphinx_rtd_theme<1.1.0`.  @namurphy Thoughts?

**Comment by dolfinus** [comment]
Hi.

I've faced the same issue after upgrading to `sphinx_rdt_theme==1.1.0`, created issue https://github.com/readthedocs/sphinx_rtd_theme/issues/1368
