### ISSUE TITLE
Remove deprecated `T_i` argument from `gyroradius`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1814]
In #1170, we deprecated the `T_i` argument to `plasmapy.formulary.lengths.gyroradius`.  We've had a few releases since then, so it's probably safe to remove this, update the docstring and tests, and add a `breaking` changelog entry.

**Comment by tranqver** [comment]
Hello, I would like to work on this as my first contribution.

**Comment by namurphy** [comment]
@tranqver — That would be great!  Please feel free to do so!
