### ISSUE TITLE
Add weekly test of doc build based on development branch of ipykernel

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1818]
### Description

We had some documentation build errors pop up recently associated with the `6.18.*` releases of ipykernel.  While the problematic releases have been yanked from PyPI, it seems worthwhile to test against the `main` branch of ipykernel. That way, we'd be able to find problems before they make it into releases, and then raise an issue on the upstream repository and/or fix the issue if it's on our end.  This would be advantageous for ipykernel as well, since there's a chance we could catch issues before they make it into releases.  Plus, if it happened once, then there's a chance that it could happen again.

The probably would be worth the effort if it's straightforward to do, but not if it ends up being a headache.  

We might consider having one testing environment for the `main` branches of a bunch of the packages we depend on for documentation, also including nbsphinx, docutils, etc.  We might be able to find cross-package issues and have fewer testing environments to deal with, but with the tradeoff that it would be harder to tell which package caused the error.

**Comment by StanczakDominik** [comment]
As a wishlist item: this is not something that should be poll-based. Breakages like this happen at discrete events in time. It doesn't make that much sense to ask ipykernel weekly "hey, anything new"? Perhaps it might actually make sense to bring back Dependabot for this. I hear it's gotten better at not spamming forks, and we could pin all of our dependencies to "current latest". Then if any of our dependencies, e.g. ipykernel, changes, it'd run the update and we'd know it broke.

But that, then, mean you basically can't install a dev version of a dependency... right? Is that how pinning works?

**Comment by namurphy** [comment]
Closing this since we are pinning dependencies for tests right now, which is helping to mitigate this problem.
