### ISSUE TITLE
Create an object-oriented Particle interface

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#182]
This has been brewing in a bunch of places, including discussion on #171 and [this chat on Matrix](https://matrix.to/#/!hkWCiyhQyxiYJlUtKF:matrix.org/$15130263015090890CUoWY:matrix.org).

Right now, we're calling all our particle-dependent functionality via strings. Those tend to be problematic for fitting in the complete information on those (there's different elements, isotopes, ionization states, @namurphy I'm likely missing a bunch so please correct me here) while keeping them readable.

The idea here is that we could create a class for Particles, keep that information (element type, charge state, isotope) there as fields and do all the calculations and operations on that. This would let us avoid having a bunch of duplicate code in every single place a particle type is necessary.

We'd still like to be able to pass strings in (as before, `particle='e'`), so what @namurphy proposed is a decorator to go through the particle type argument and if a string was passed, turn that string into a Particle and pass that in. This seems reasonable AND it involves using a decorator, so it's totally baller to me.

The whole class setup would have to be figured out - do we want to have the same kind of object for atoms/nuclei and for electrons/other charged leptons (no isotopes for the latter)? What kind of inheritance scheme is best for those? I'm not sure yet, but this is part of figuring this out.

**Comment by lemmatum** [comment]
There is an additional complication. So far all the functions that use ionization have been using an integer value as determined by an individual particle's charge state (e.g. plasma_frequency), but many of these parameters are macroscopic and so they should instead depend on the average ionization state.

We should find a way to allow the user to manually input the average ionization while retaining the current functionality with particles. One way to do this would be to force the user to input the average ionization when they pass a neutral particle and to default to the ion charge state when a charged particle is passed an an average ionization is not passed. For the latter case we could also add a PhysicsWarning message to warn the user of this default behavior.

**Comment by StanczakDominik** [comment]
... crud, partial ionization is a thing. Yeah, that's an issue.

One thing to consider may be to, given that we'd like to have a feature freeze for 0.1 in mid January and release it in February (and I should really send out an email about this, shouldn't I...), postpone doing partial ionization until later. Even "simple" things such as plasma parameters and transport coefficients (I'm probably naive about this :laughing:) can balloon out of proportion if we keep adding complexity into them.

**Comment by lemmatum** [comment]
Yea and if you set a plasma at a certain temperature it is not either Z=10 or Z=11 but a mix of multiple charge states approximated by Saha-Boltzmann. Typically you deal with this by taking an average charge state.

I dunno, I think this is pretty important and quite a large omission for 0.1. It renders a lot of the functions useless for most plasmas unless users hack together some sort of averaging or interpolation.

@namurphy  thoughts?

**Comment by StanczakDominik** [comment]
I'm just saying, it's a possibility to postpone this. I don't quite have a handle myself on how important this  is.
