### ISSUE TITLE
Calculate Thomson Spectral Density given scattering angle

### ISSUE THREAD

**Issue by pheuer** [PlasmaPy/PlasmaPy#1821]
### Feature description

Calculate spectral density given scattering angle directly.

### Motivation

The Thomson scattering spectral density function depends on the scattering angle (angle between the incoming and scattered light). In the current code, this is calculated from provided parameters `probe_vec` and `scatter_vec', which are unit vectors describing the geometry. This is convenient on larger experimental facilities (where the unit vectors of ports and beams are fixed and easy to look up). 

### Implementation strategy

 I've gotten requests to add an additional keyword `scattering_angle` that, if provided, directly provides the scattering angle. This keyword OR the existing probe_vec/scatter_vec keywords should be accepted, but not both at the same time. 

In addition to logic + validation that only one set of keywords is being used, the only line that should need to be updated is 

```
scattering_angle = np.arccos(np.dot(probe_vec, scatter_vec))
```

Where, if the scattering angle is provided explicitly, this can just be set directly rather than calculated.

**Comment by tranqver** [comment]
I'd like to work on this. I assume this would require additional test inputs?

**Comment by tranqver** [comment]
To check my understanding, this feature would only be added to ``spectral_density_lite``? 

In spectral_density_lite, the line ``k_vec = scatter_vec - probe_vec`` would need ``scatter_vec`` and ``probe_vec``. Would these values need to be initialized to their default values when not given?

**Comment by pheuer** [comment]
I would: 

1) Change spectral_density_lite to only take the scattering_angle keyword. 
2) Add scattering_angle to spectral_density (keeping the other two keywords)
3) Add logic inside spectral_density that either takes the scattering angle provided or calculates it from the other keywords,
then passes that through to spectral_density_lite

**Comment by suyashnaikare** [comment]
I would like to work on it

**Comment by pheuer** [comment]
@suyashnaikare Excellent! Please see the ideas above - you can create your own branch of PlasmaPy, start implementing the feature, then open a pull request and request me as a reviewer. Your pull request does not need to be complete - just do what you can then we can discuss and suggest changes then.

**Comment by pheuer** [comment]
Duplicating this comment here from #1831 


@JaydenR2305 and I looked into this, and I'm now thinking adding this keyword isn't such a good idea. The problem is in the lines here 


```python
scattering_angle = np.arccos(np.dot(probe_vec, scatter_vec))
```

```python
    # Compute the wavenumber shift (required by momentum conservation)
    # Eq. 1.7.10 in Sheffield
    k = np.sqrt(ks**2 + kl**2 - 2 * ks * kl * np.cos(scattering_angle))
    # Normal vector along k
    k_vec = scatter_vec - probe_vec
    k_vec = k_vec / np.linalg.norm(k_vec)

    # Compute Doppler-shifted frequencies for both the ions and electrons
    # Matmul is simultaneously conducting dot products over all wavelengths
    # and ion components
    w_e = w - np.matmul(electron_vel, np.outer(k, k_vec).T)
    w_i = w - np.matmul(ion_vel, np.outer(k, k_vec).T)
```

If the only use of `scatter_vec` was to calculate `k`, then the new keyword would make sense. But they are also used to defined `k_vec`, which then allows us to accept vector electron and ion velocity arguments. If vectors for the probe and scattering vector aren't supplied, I don't think we could support flow velocities (or we'd have to assume something about their direction). That seems to me like a significant drawback. 


Unless someone disagrees, I'm inclined to close this issue.

**Comment by twhentschel** [comment]
I just stumbled upon this issue, but after spending a little bit of time on it I think you're right @pheuer : if we only have a relative angle between `scatter_vec` and `probe_vec`, the most we can hope for is to come up with a `k_vec` with a direction relative to one of these other two vectors. The velocities, on the other hand, have absolute directions with respect to some origin.

Like you mentioned,  the `scattering_angle` keyword could be kept if we assume (i.e. add a note to the description of the velocities parameters) that the velocity directions are given with respect to the `probe_vec`, for example. But this might be too confusing.

**Comment by pheuer** [comment]
@twhentschel Thanks! I agree that having the velocities relative to the probe or scatter vector is potentially very confusing.

Seems like we're in agreement: I am going to close this issue and the corresponding pull request.
