### ISSUE TITLE
Add a troubleshooting guide to the testing guide

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1829]
A few recent issues/PRs (#1331, #1752, #1817) addressed adding a troubleshooting guide to the documentation guide.  It would be really helpful to add something similar to the testing guide. 

This will probably be more difficult to do, as there are a lot more things that can go wrong with the tests than with the documentation build.  We probably will want to link to external resources when we reasonably can, including relevant pages in pytest's documentation.

Once the troubleshooting section is created, we could have the `tox` (or `nox`) environments or GitHub Actions for tests print out a link to it on the World Wide Web™.

For the time being, it'd probably be helpful to use this issue to brainstorm the most important things for the troubleshooting guide to include.

Thanks to @StanczakDominik for the idea!

**Comment by namurphy** [comment]
I'm wondering if we'd want to include some troubleshooting for linters too.  That's lower priority, though, and we'd want to suggest that contributors should usually save linter fixes until all other checks are passing, and then mention `pre-commit.ci autofix`.

**Comment by StanczakDominik** [comment]
> This will probably be more difficult to do, as there are a lot more things that can go wrong with the tests than with the documentation build. We probably will want to link to external resources when we reasonably can, including relevant pages in pytest's documentation.

I honestly just meant our testing guide. That's already a pretty good resource.

**Comment by namurphy** [comment]
> I honestly just meant our testing guide. That's already a pretty good resource.

Ah!  That makes sense.  I'll aim to do that in #1734, most likely.  

Perhaps we can keep this issue open and use it as a place to store ideas or FAQs for what would go into a test troubleshooting guide.  If there end up being ideas worth including then we can create it.  If there don't end up being many things worth including, then we can let this issue disappear into the æther.  I'll label this as "on hold" for now.

**Comment by namurphy** [comment]
I'll use and update this comment to brainstorm ideas for what could go into a testing troubleshooting guide.

- Test troubleshooting tips
  - Do a web search for the error message
  - What to do when a test fails for an unrelated reason
- Linters
  - Mention that to get more information about a linter error like `F821`, one could do a search for "flake8 F821".
  - Using `pre-commit.ci autofix` (which we mention elsewhere)

**Comment by namurphy** [comment]
Closing this since the need is mostly filled by the automatic comment on pull requests.
