### ISSUE TITLE
Allow running tests as plasmapy.test()

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#183]
In [this discussion on Matrix](https://matrix.to/#/!hkWCiyhQyxiYJlUtKF:matrix.org/$15124809421223589HCELA:matrix.org) @cadair raised the point of using Astropy's test runner to be able to run tests via

    import plasmapy
    plasmapy.test()

This seems pretty damn handy, and there was no issue for this one just yet so I'm making one.

@SolarDrew took a stab in this general direction, but came upon ~~overpowering enemy force~~ bugs tales of which we have yet to hear.

@SolarDrew, are you going to keep at this? I can try it myself if you'd like.

**Comment by namurphy** [comment]
This has been added recently.

**Comment by SolarDrew** [comment]
It has? Who fixed that?

**Comment by namurphy** [comment]
I was able to do `plasmapy.test()`, except I got an error with the Cython tests.  However, I got that error too when doing just regular old `pytest` (probably because I didn't do the `python setup.py install` thing).  If I delete the Cython test file then I can get the tests to run successfully.

**Comment by StanczakDominik** [comment]
Thanks for the heads up @Cadair! This should be helpful.

**Comment by StanczakDominik** [comment]
I can confirm that this works now! Neat. We should add a note about this to the documentation, and that running this seems to require `pytest-astropy`!
