### ISSUE TITLE
Option to pass 'None' in particles.particle_input()

### ISSUE THREAD

**Issue by pheuer** [PlasmaPy/PlasmaPy#1882]
### Feature description

In a previous version, particle_input had a `none_shall_pass` option that allowed particle=None to go through. I can't figure out how to do this with the new version of the decorator (if it's possible?). I suggest adding an explicit keyword back to do this.

Paging Dr. Particles, @namurphy 

### Motivation

Sometimes you just want to pass None!

**Comment by namurphy** [comment]
We ended up changing it to be more consistent with community conventions for type hint annotations.  The annotation for something that can be `None` should now be `Optional[ParticleLike]`:

```python
@particle_input
def f(particle: Optional[ParticleLike]):
    return particle
```
