### ISSUE TITLE
Rename math submodule

### ISSUE THREAD

**Issue by SolarDrew** [PlasmaPy/PlasmaPy#189]
Namespaces are one honking great idea, so let's not have a submodule that shares a name with [an existing library](https://docs.python.org/3.6/library/math.html). Will require changing the filename, folder name, and purging all instances of it being imported.

Current frontrunner for replacement name is `mathematics`.

**Comment by StanczakDominik** [comment]
github y u no autoclose issue :(
Closed by #190
