### ISSUE TITLE
Move `mass_density` from `misc.py` to `densities.py`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1919]
We currently have a function for `mass_density` in `plasmapy.formulary.misc`. To keep with the scheme where `plasmapy.formulary` functions are broken down by physical type, we might want to move this to `plasmapy.formulary.densities` instead.  

Some things to think about with this:
 - The mass density has a different physical type than number densities
 - Mass density is a bit conceptually different than other formulary functions.  I'd almost describe mass density as a plasma property rather than a plasma parameter.  This might perhaps have been why it ended up going into `misc.py`.

**Comment by ironwod** [comment]
I can take this as my first contribution.
