### ISSUE TITLE
Add documentation build as part of testing?

### ISSUE THREAD

**Issue by dstansby** [PlasmaPy/PlasmaPy#197]
It looks like PlasmaPy doesn't build docs as part of the continuous integration testing. Usually it's a good idea to build the docs to make sure any changes made in PRs don't stop the documentation building.

If there's interest in this I'm happy to take a stab at it. Options are using another travis build slot, or using another CI provider (a couple of projects I contribute to use https://circleci.com/)

**Comment by StanczakDominik** [comment]
YES

I was wondering how to approach doing that! It would be really great if you could do it, if it's not much of a problem for you.

I don't know which way to do this is optimal. Travis is nice, but perhaps having two Travis builds may be confusing? Do you think it would be a better move to run CircleCI or something else?

You're the expert here, so I'd appreciate any advise.
