### ISSUE TITLE
Add a class to describe 1D Harris sheets

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1979]
### Feature description

A Harris sheet is a 1D configuration of the form $B_x(y) = B_0 \tanh(\frac{y-y_0}{\delta})$.  There are also formulas for the out-of-plane current density and plasma pressure. We should have a class that can be used to describe Harris sheet equilibria.

### Motivation

In reconnection research, Harris sheets come up all the time (and then some). They are used as standard simplified initial conditions in cartesian geometry.  Having a Harris sheet class would make the lives of reconnection researchers just a little bit easier.

### Implementation strategy

We could create a `HarrisSheet` class that would accept $y_0$, $\delta$, and $B_0$ upon creation of a `HarrisSheet` object.  The class can then have methods that would provide $B_x(y)$, $J_z(y)$, and $p(y)$.  

### Additional context

We should think about where the best location is to put this class.  I don't think it quite fits in the formulary, but maybe we want to create a `plasmapy.equilibria` or `plasmapy.configurations` subpackage. (That would also be where a Grad-Shafranov solver might go, as in #46.) Edited to add: Or perhaps we could put it in `plasmapy.plasma.equilibria`, at least for now?

We could possibly consider force-free equilibria too, where $\mathbf{J}\times\mathbf{B}=0$, which also sometimes come up in reconnection research.

This issue should be addressed before #1978, since we might learn some lessons that would help us when implementing #1978.

**Comment by StanczakDominik** [comment]
Can you provide a reference, a source for the current density/pressure formulas?

**Comment by namurphy** [comment]
I just added the equations for current density and plasma pressure to the Wikipedia article on [current sheets](https://en.wikipedia.org/wiki/Current_sheet#Harris_current_sheet).

**Comment by namurphy** [comment]
@mohawk811 — here's the sketch that I was mentioning on Zoom.

```Python
class HarrisSheet:
    def __init__(self, B0, delta):
        self.B0 = B0
        self.delta = delta
    def magnetic_field(self, y):
        return self.B0 * np.tanh(y / self.delta)
    def current_density(self, y):
        ...
    def pressure(self, y):
        ...
```

```pycon
>>> import astropy.units as u
>>> harris_sheet = HarrisSheet(B0 = 0.02 * u.T, delta = 5 * u.cm)
>>> harris_sheet.magnetic_field(y = 2.3 * u.cm)
```

Thank you again for working on this!
