### ISSUE TITLE
Update `Coulomb_log` example to use `n_e` instead of `n`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2003]
In [the example section](https://github.com/PlasmaPy/PlasmaPy/blob/8091c31ae3d18c5adebaf15518ef56676921f9b7/plasmapy/formulary/collisions/coulomb.py#L407) of `plasmapy.formulary.collisions.coulomb.Coulomb_log`, the variable used for electron density is `n`, but it should be changed to `n_e` to make it more clear that it should be the electron density.  This issue would be especially good for a first-time contributor.

The origin story of this issue is that it came up in #1986, in the same discussion that led to #2000.

**Comment by mysakli** [comment]
Hi, I would like to take this issue.
