### ISSUE TITLE
Fix path on the getting ready to contribute page

### ISSUE THREAD

**Issue by martha889** [PlasmaPy/PlasmaPy#2036]
### Bug description

Under "installing your clone" of PlasmaPy on the getting ready to contribute page https://docs.plasmapy.org/en/latest/contributing/getting_ready.html. The path appears like this:
![Screenshot 2023-03-23 at 5 53 22 AM](https://user-images.githubusercontent.com/39094506/227067943-ddf9d23d-1ebc-4ed2-bf64-c3367232ec18.png)

Looks like the backward slashes don't show up. The change was added in the commit (bf7cf61654198bafbf81490931b3368a2f162087). Will need to fix this.

### Expected outcome

The path should appear like this: `C:\Users\<username>\repos\PlasmaPy`

**Comment by namurphy** [comment]
Thank you for finding this!  The first thing I'd try would be to stop using the `:file:` role and switch to double back ticks to surround the file path.  Another possibility that might fix it would be to double up the backslashes.
