### ISSUE TITLE
Gyrofrequency can be a signed quantity

### ISSUE THREAD

**Issue by jhillairet** [PlasmaPy/PlasmaPy#206]
The gyrofrequency can be defined a signed quantity, for instance in wave in plasma physics. This means that the frequency is then negative for electron, and positive for ions. 

The `gyrofrequency()` function should support this convention, for example using a optional argument `signed` which can be `False` per default.

**Comment by jhillairet** [comment]
fuck, I've mixed plasma and gyro frequency... I'm corrected it in my PR...

**Comment by StanczakDominik** [comment]
Closed by #207
