### ISSUE TITLE
Use Dawson function for dispersion

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#208]
`plasma_dispersion_func` under `mathematics.py` currently uses `erf()` along with some other terms. This can be simplified to Dawson function, [dawsn](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.dawsn.html), and may even offer some minor speedups if scipy implements it in C code.

**Comment by namurphy** [comment]
I hadn't remembered seeing the [Dawson function](https://en.wikipedia.org/wiki/Dawson_function) used in expressions for the plasma dispersion function before.  I was looking through _Waves in Plasmas_ by T. H. Stix (1992) and saw a formulation for it on page 202.  The Dawson function is:

S(ζ) = exp(-ζ²) ∫<sub>0</sub><sup>∞</sup> exp(z²) dz = -S(-ζ)

where the integral goes from 0 to ∞.  Then the panda dispersion function is:

Z(ζ) = i √π exp(ζ²) - 2 S(ζ)

**Comment by namurphy** [comment]
Looking at this a little further, an expression that looks even simpler is:

Z(ζ) = i √π w(ζ)

where w(ζ) is the complex error function, also known as the Faddeyeva function.  I think that's [https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.wofz.html](wofz) in SciPy.

**Comment by lemmatum** [comment]
I like your Faddeeva idea, and looking at wikipedia wofz is implemented in C, so there may be some speedups.

**Comment by siddharth185** [comment]
Hello. I would like to work on this. Looks like a good first contribution.
