### ISSUE TITLE
Re-implement lite-functions using Rust back-end (alternative to #2104)

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2082]
### Feature description

We should consider re-implementing PlasmaPy's lite-functions using Rust instead of Numba.

### Motivation

We currently use formulary lite-functions for computationally intensive applications.  These functions operate on `np.ndarray` objects rather than `Quantity` objects.  

At present, we use Numba to get compiled speeds.  However, it takes a long time for Numba to get updated for new Python releases.  For example, it's been six months since Python 3.11 was released, but there hasn't been a release of Numba yet that works on Python 3.11 (apart from a recent pre-release). This means that we are preventing downstream packages (i.e. fiasco) from upgrading to Python 3.11.  Users may also run into problems where they install Python 3.11, but have trouble installing PlasmaPy.

There has been a lot of progress and excitement in the last few years about using Rust and Python together, and it looks like enough tooling is in place for us to implement a Rust back-end for our lite-functions.

### Implementation strategy

We could probably use [PyO3](https://pyo3.rs) to do this.

Since the Rust stuff is likely to be a small part of what's in PlasmaPy, we might want to put the Rust stuff in a separate package, and then import the lite-functions separately.  

### Additional context

The main alternatives are:
 - Stick with Numba, which has the downside of needing to sometimes wait 6 months to be able to use the newest version of Python.
 - Use Cython instead of Rust as the back-end.  In one benchmark, [Rust seems to be mostly faster than Cython](https://github.com/timleslie/rust_vs_cython).  Rust also has thread safety built-in.  And, there's more excitement about Rust, which makes it likely that there will be more great things in the future.  It would probably be quicker for Python users to learn Cython than Rust, since Cython is a superset of Python.
 - Use Julia instead of Rust as the back-end.  I've heard of a lot less activity in the Pythoniverse about connecting Julia and Python, so we'd want to make sure there's an active contributor community and that packaging won't be horrible. If we expand beyond lite-functions for Julia/Rust/Cython, Julia would have the advantage of having a whole lot of functionality for scientific computing already in the ecosystem, which doesn't exist yet in Rust.

**Comment by namurphy** [comment]
I'm labeling this as "on hold" since we probably want to look into this more, and also to create a prototype.

**Comment by JaydenR2305** [comment]
> At present, we use Numba to get compiled speeds.

Here's something interesting. Currently, we only use numba for `thermal_speed_lite` and `plasma_frequency_lite` both of which involve calculating the product of a few array_like objects, then taking their square root. I did some profiling and it appears that numpy is able to do these calculations quicker than numba for large arrays.
![image](https://github.com/PlasmaPy/PlasmaPy/assets/109694185/7ff28dd4-d08f-403e-8d3e-3c8d0d900c25)

**Comment by namurphy** [comment]
Closing this for the time being, since we're likely to go with Cython instead of Rust given the available tooling.
