### ISSUE TITLE
Add dispersion relation for MHD waves

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2197]
### Feature description

Add functionality for the dispersion relations for Alfvén, slow magnetosonic, and fast magnentosonic waves.

### Motivation

We currently have some two-fluid dispersion relation solvers, but we don't have anything for plain MHD waves.  Adding functionality for MHD wave dispersion relations would be particularly useful as a tool for pedagogy, and would also be useful as a limiting case for researchers.

### Implementation strategy

We probably want to think carefully about the interface to make sure it is intuitive, in particular for newcomers to plasma physics.

Some of the possibilities would be:

 - Have separate classes for `AlfvenWave`, `FastMagnetosonicWave`, and `SlowMagnetosonicWave` with a method for calculating $\omega$ as a function of $k$ and $θ$.
   - There could be a helper function that would return a namedtuple or that includes an instance of each of the three different types of waves with appropriately named attributes.
 - There could be a single `MHDWaves` class

Overall I'm not sure what the best approach would be.

We might want to add a method for plotting a Friedrichs diagram too.

### Additional context

If I remember right, there's also an entropy mode that doesn't propagate.  We might want to add this too.

**Comment by TrestanSimon** [comment]
I would be very interested in working on this.

> Have separate classes for `AlfvenWave`, `FastMagnetosonicWave`, and `SlowMagnetosonicWave` with a method for calculating ω as a function of k and θ.

Since the two fluid DR solver, for example, is just a function in the [plasmapy.dispersion.analytical](https://docs.plasmapy.org/en/stable/api_static/plasmapy.dispersion.analytical.html#module-plasmapy.dispersion.analytical) subpackage, would it make sense that the MHD wave DR functionality also be implemented in this way? (I have not contributed to PlasmaPy in a while; maybe I am missing something here.)

**Comment by namurphy** [comment]
@TrestanSimon — thank you!

> Since the two fluid DR solver, for example, is just a function in the [plasmapy.dispersion.analytical](https://docs.plasmapy.org/en/stable/api_static/plasmapy.dispersion.analytical.html#module-plasmapy.dispersion.analytical) subpackage, would it make sense that the MHD wave DR functionality also be implemented in this way? (I have not contributed to PlasmaPy in a while; maybe I am missing something here.)

I've been wondering about if there would be a way to improve the user-friendliness of the dispersion functionality.  For the MHD case, I'm wondering if we would want to do something like:

Lately I've been wondering about ways to make PlasmaPy's dispersion functionality more user-friendly, since functions with lots of arguments tend to be more difficult to use and re-use. To go into a bit more detail about the first possibility I mentioned above, one approach would be to have an `AlfvenWave` class that would work something like this: 

```pycon
>>> alfven_wave = AlfvenWave(B=B, n=n, ion="p+")
>>> omega = alfven_wave.angular_frequency(k=k, theta=theta)
```

I've been wondering if an approach like this would make it easier to use.
