### ISSUE TITLE
Cython integration

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#222]
Astropy's template has a way to [integrate Cython and C extensions.](http://docs.astropy.org/en/stable/development/ccython.html) We should get this working so we can have super optimized code for simulations!

**Comment by lemmatum** [comment]
Relates to [spectroscoPy issue](https://github.com/PlasmaPy/SpectroscoPy/issues/16)

**Comment by lemmatum** [comment]
I will take a crack at this as I need to learn Cython for my own simulations anyway.

**Comment by StanczakDominik** [comment]
I've been meaning to learn Cython as well. If you find any neat materials, it would be awesome if you could share them (perhaps here)! :smiley:

**Comment by lemmatum** [comment]
[This](https://stackoverflow.com/questions/20307546/running-cython-code-within-the-interpreter) stackoverflow response has some good links (and reference to His Noodliness). Otherwise I am reading [Cython](http://shop.oreilly.com/product/0636920033431.do) by Kurt W. Smith.

**Comment by lemmatum** [comment]
For distribution, Cython [recommends](http://docs.cython.org/en/latest/src/reference/compilation.html#distributing-cython-modules) to distribute the `.c` files generated by our Cython `.pyx` files so that end users don't need to have Cython to install our package.

I think this means we need to explicitly include the generated `.c` files using the `get_extensions()` function in `setup_package.py` as mentioned in [astropy docs](http://docs.astropy.org/en/stable/development/ccython.html).

**Comment by lemmatum** [comment]
We should include guidelines for inclusion of C and Cython code into plasmaPy. [Here](https://github.com/astropy/astropy/blob/135589ff117042de5ef604889e851ecea760b759/docs/development/codeguide.rst) are astropy's guidelines.

**Comment by lemmatum** [comment]
[Examples](https://github.com/cythonbook/examples) from Cython book.

**Comment by lemmatum** [comment]
[Reference](http://docs.astropy.org/en/stable/development/building.html?highlight=get_extensions) for how I added the `setup_package.py` file in #223 . Adding `.c` files to the build should also be done via the `get_extensions()` function within this file.

**Comment by lemmatum** [comment]
To get the newly built `.c` file to appear next to the original `.pyx` file when building cython modules we need to use `python setup.py build_ext --inplace` instead of `pip install .`

This will only be necessary in development when building new `.c` modules. These then get added to the repo for distribution so end users don't need to do the cythonize step.

**Comment by lemmatum** [comment]
The more I read about Cython the cooler it gets. Apparently the whole `cdef` structure can also be used for creating things that behave like classes, but are actually extensions that work at the Python/C API level, so they're super fast!

**Comment by StanczakDominik** [comment]
Oh yeah, definitely add setup_packages.py to .coveragerc excluded files. It doesn't seem worth testing.

**Comment by lemmatum** [comment]
Once Cython integration is done, we can further optimize dispersion function calculations using `wofz` from [SciPy's Cython API for special functions](https://docs.scipy.org/doc/scipy/reference/special.cython_special.html). Kappa distribution calculations can also be optimized by using `Gamma` from the API.

**Comment by StanczakDominik** [comment]
Oh wow, that sounds pretty cool! Do you think we could get this done by mid February, so the 0.1 release supports cython for a visible reason that's already in the repo? How can we help?

**Comment by lemmatum** [comment]
I think that's doable.
You can take a look at [this](https://github.com/PlasmaPy/PlasmaPy/pull/223#issuecomment-355429621) to do list and see if you can investigate one of these.
Also I've got the nagging feeling that I may not be setting up the Cython integration correctly in `setup.py`, so if you can double check that it would be helpful. At present, I added code to `pop` the list of `.c` and `.pyx` extensions from the dictionary returned by `astropy_helpers` and then I explicitly `cythonize` in `setup()` even though I think the default was to not `cythonize`, but rather just pass this dictionary with all the other additional arguments to `setup()`. I couldn't get that default to work properly, which is why I changed it. Perhaps the astropy template package or someone in the astropy community has some hints on how to do this?
