### ISSUE TITLE
Fix __init__.py files

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#227]
I've come to dislike the star imports in our `__init__.py`. I don't think dumping everything into the same namespace is good Python, while it may make it easier to find stuff.

I think we should figure out ways to break that up.

I dunno, maybe we should replace the star imports with named imports again... I'll look through other libraries, see how they do it.

**Comment by StanczakDominik** [comment]
@siddharth185 , while you're dealing with this... would it be too much to ask you to also take a look at our other subpackages? `atomic` and `math` in particular.

Fair warning, though - there's a decently sized bunch of functions there, though.

**Comment by siddharth185** [comment]
@StanczakDominik Is the PR what you were looking for?

**Comment by StanczakDominik** [comment]
Yeah, it was that exactly :) thanks a bunch, again!

**Comment by siddharth185** [comment]
@StanczakDominik Don't mention it!
