### ISSUE TITLE
Prevent numpy 0.14 from breaking all docstrings

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#229]
This relates to #135 and is the reason why tests are failing for #228 - and everything that's been updated in the last 21 hours.

[Numpy 1.14 has just been released](https://github.com/numpy/numpy/releases/tag/v1.14.0), and within the release notes there's this tidbit:

> "Many changes to array printing, disableable with the new "legacy" printing mode"

So yeah. All our docstrings are broken now, basically. Possible solutions, in order of "from most temporary":
* We could set our tests to run on 1.13 for now. [This is how to implement this](https://github.com/PlasmaPy/PlasmaPy/compare/master...StanczakDominik:doctestplus), and that branch could be merged.
* We could do the legacy printing mode, but that involves adding it to all of our files, I think.
* Eventually we'd probably want to rewrite our docstrings to numpy 1.14 standard.

**Comment by samurai688** [comment]
Sounds like they had us in mind with the legacy mode, huh?  Maybe we could just do that where needed and then we can go back and re-write the doctests at leisure.

**Comment by StanczakDominik** [comment]
Actually I just figured out how to semi-quickly rewrite this in pycharm. I guess I'll just do it up.
