### ISSUE TITLE
Add "force-free" to glossary and apply it in documentation

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2323]
We're using the concept of "force-free" in a few places, but this term will not be familiar to people who are new to plasma physics so we should add it as a term in the glossary (`docs/glossary.rst`) so that it can be referenced with :term:`force-free`.  

The entry should include a link to the [force-free magnetic fields](https://en.wikipedia.org/wiki/Force-free_magnetic_field) page on Wikipedia using `` :wikipedia:`force-free magnetic field` `` role.

It might also be worth adding `` :term:`force-free`\ `` to `docs/_global_substitutions.py` so that in the docs we can use `|force-free|`.  

We could then use the term in the docs for `plasmapy.plasma.cylindrical_equilibria.ForceFreeFluxRope` which is being added in #2289 and maybe what gets added in #2306.

**Comment by Stray235** [comment]
Hi, I am working on this!
