### ISSUE TITLE
Verify correctness of two methods in `MaxwellianCollisionFrequencies`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2333]
After a recent update of pytest that fixed a test collection bug (see https://github.com/pytest-dev/pytest/issues/11237), a couple of doctests started failing in `plasmapy.formulary.collisions.frequencies.MaxwellianCollisionFrequencies` (see below).  Essentially, these doctests were not being run before the pytest update.

It turns out that there is a discrepancy for two properties of `MaxwellianCollisionFrequencies` in `plasmapy.formulary.collisions`: `Maxwellian_avg_ei_collision_freq` and `Maxwellian_avg_ii_collision_freq`.  I'm updating the docstrings in #2332 to be consistent with the new calculated values.

However, because of this discrepancy, it would be worthwhile to double check that these two properties are giving correct results.  

The new doctest errors were:

```
_______________________________ [doctest] plasmapy.formulary.collisions.frequencies.MaxwellianCollisionFrequencies.Maxwellian_avg_ei_collision_freq _______________________________
[gw0] win32 -- Python 3.10.11 D:\a\PlasmaPy\PlasmaPy\.tox\py310-cov-all\Scripts\python.EXE
EXAMPLE LOCATION UNKNOWN, not showing all tests of that example
??? >>> electron_ion_collisions.Maxwellian_avg_ei_collision_freq
Expected:
    <Quantity 2906316911556553.5 Hz>
Got:
    <Quantity 2.80530783e+15 Hz>

D:\a\PlasmaPy\PlasmaPy\plasmapy\formulary\collisions\frequencies.py:None: DocTestFailure
_______________________________ [doctest] plasmapy.formulary.collisions.frequencies.MaxwellianCollisionFrequencies.Maxwellian_avg_ii_collision_freq _______________________________
[gw0] win32 -- Python 3.10.11 D:\a\PlasmaPy\PlasmaPy\.tox\py310-cov-all\Scripts\python.EXE
EXAMPLE LOCATION UNKNOWN, not showing all tests of that example
??? >>> ion_ion_collisions.Maxwellian_avg_ii_collision_freq
Expected:
    <Quantity 79364412.21510696 Hz>
Got:
    <Quantity 1.12238228e+08 Hz>

D:\a\PlasmaPy\PlasmaPy\plasmapy\formulary\collisions\frequencies.py:None: DocTestFailure
```

**Comment by daran9** [comment]
Hello again @namurphy! I would like to work on this if it's available.

**Comment by namurphy** [comment]
Yes, please feel free to!
