### ISSUE TITLE
Should we rename the charge_state function?

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#236]
The `charge_state` function in the atomic subpackage current returns the integer electric charge (e.g., `-1` for `'e-'`, `1` for `'p'`, `16` for `'Fe 16+'`, and so on).  The name `charge_state` is appropriate for ions where it also means the ionization state.  However, it makes less sense to talk about the charge state of electrons, muons, and neutrons, so I'm wondering if we should change it to something else.  

I have been thinking `integer_charge` is intuitive and easy to understand, though it would not be as appropriate for describing quarks if we were to extend the atomic subpackage further.  Are there any other good alternatives?

**Comment by StanczakDominik** [comment]
Come on, let's not start worrying about quarks here! `integer_charge` is good. We can add a note saying that this is `integer charge, as normalized to the charge of the electron`. Thus, we can, if need be for quarks, reasonably output fractions with a note in the docs.
