### ISSUE TITLE
Switch from black to the ruff formatter

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2393]
### Description of improvement

Instead of using [black](https://github.com/psf/black) as our autoformatter, we would switch to using the [ruff formatter](https://astral.sh/blog/the-ruff-formatter).

This would be a good first issue for someone who has some familiarity with pre-commit, ruff, and/or black; or who would like to learn about autoformatters & linters for Python.  

### Motivation

Performance!  The ruff formatter is written in Rust, and it therefore has considerably better performance than black.  It also works on notebooks.

### Implementation strategy

We would need to update `.pre-commit-config.yaml` to replace the pre-commit hook for black with the ruff formatter hook.  We could probably also drop the `nbqa-black` hook, which runs on Jupyter notebooks.

After doing that, we would either need to run `pre-commit run --all-files` locally and commit/push the changes, or comment `pre-commit.ci autofix` on the pull request to apply changes.

### Additional context

The ruff formatter is still in beta, though their blog post indicates that it should be production ready.  The differences with black should be very minor.

**Comment by 0scvr** [comment]
I would like to work on this. Please assign me, thanks.
