### ISSUE TITLE
Broken link of Anaconda navigator in README

### ISSUE THREAD

**Issue by niranjan-kurhade** [PlasmaPy/PlasmaPy#2395]
### Bug description

When we click on the Anaconda Navigator link in the README of this repository -
![image](https://github.com/PlasmaPy/PlasmaPy/assets/97905637/2fd0c04c-8a1b-4bd0-b994-df50c0aec583)

It redirects us to a 404 page of Anaconda Documentation-
![image](https://github.com/PlasmaPy/PlasmaPy/assets/97905637/22d0a4b2-2c19-4314-b6d7-ffd9e2f77a45)

### Expected outcome

When clicking on the Anaconda Navigator, it should redirect to its correct working (latest) link.

**Comment by niranjan-kurhade** [comment]
If this is a valid issue, please assign it to me!

**Comment by namurphy** [comment]
Thank you for reporting this!  I saw that you raised the issue and made the fix before I saw that you wanted to be assigned this issue.  Sorry about that!  Please feel free to look at our other issues labeled "good first issue" for more possibilities.  And thank you again!
