### ISSUE TITLE
Standardize import alias for astropy.units as u

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#241]
There are some places in PlasmaPy where we use:
```Python
from astropy import units as u
```
and other places where we use
```Python
from astropy import units
```
As @StanczakDominik and others have pointed out on Matrix, it would be helpful to have one single alias for `astropy.units` that used uniformly throughout the code so that it's more consistent and readable.  In the discussion on Matrix, the preference from a few people was to use `u` for brevity.  This issue is to go through the code and replace occurrences of `from astropy import units` and `units.` with `from astropy import units as u` and `u.`, including in examples in docstrings.

Thank you!
-Nick

**Comment by nurbu5** [comment]
Hi @namurphy,

Sorry for not announcing I was going to work on this beforehand. I think this PR should update those aliases: https://github.com/PlasmaPy/PlasmaPy/pull/243

Let me know if there are any issues. Also, can you give me any good resources for learning about Plasma physics. I'd like to know a little bit about the domain if I'm going to contribute to some of the tougher issues. Thanks.

**Comment by namurphy** [comment]
Thank you, @nurbu5!  Everything looked good so I merged it.

With respect to resources on learning about plasma physics, I'm most familiar with textbooks like [_Introduction to Plasma Physics_](https://books.google.com/books/about/Introduction_to_Plasma_Physics_and_Contr.html?id=mFg-CwAAQBAJ&printsec=frontcover&source=kp_read_button#v=onepage&q&f=false).  There's also an [edX online course on plasma physics](https://www.edx.org/course/plasma-physics-introduction), though I haven't gone through it myself.

**Comment by StanczakDominik** [comment]
The edx course is neat, I can recommend it. :)
