### ISSUE TITLE
Add AppVeyor continuous integration testing

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#246]
We presently use Travis CI and CircleCI for continuous integration testing.  These tests are performed largely in Linux environments, but we should also add tests for Windows environments so that we can fix any compatibility problems sooner rather than later.  In particular, [AppVeyor](https://www.appveyor.com/) tests builds on Windows virtual machines and thus would be able to mostly fill this gap in our testing.  The goal of this issue is to add AppVeyer to the suite of continuous integration tests that are automatically performed with each pull request.

**Comment by lemmatum** [comment]
More explicitly, we should test Cython since Windows hates GCC.
