### ISSUE TITLE
Cleanup test_transport.py

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#250]
`class Test_classical_transport` is in dire need of some error strings which return the compared values when a test fails. Best to do this with f-strings.

**Comment by Nismirno** [comment]
Hi,
I would like to take up on that issue.

**Comment by StanczakDominik** [comment]
Hey @Nismirno, thanks for the offer ! Would you mind waiting until #191 is merged into master (likely within ~2 days) to start working on this one? It'd be much easier to work based on a shared history when that one's settled!

**Comment by Nismirno** [comment]
Hi @StanczakDominik,
Sure. I have no problems with that.

**Comment by StanczakDominik** [comment]
@Nismirno, I'm pinging you as #191 just got merged! :D
