### ISSUE TITLE
Allow users to set default particle or ion?

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#252]
Most of the plasma parameter functions have arguments or keywords to specify the particle(s) to be used by the function.  For example, `gyrofrequency()` requires knowing what the charged particle is that is being considered.  Many of the functions currently default to protons or electrons, but these defaults are not universally used.  Fusion scientists often assume a default ion of D+ whereas astronomers and heliophysicists often assume protons instead.  Moreover, having functions implicitly assume that a certain particle will be used could lead to mistakes when the user doesn't make the same assumption as the function.

It would probably be useful to allow users to enable a default particle and/or ion to avoid having to repeat entering in the same ion over and over. With such a function or class (perhaps called `set_default_particle` and/or `set_default_ion`), then users could explicitly set their own defaults.

This will need to be done after #242 is finished, as the best place to put this is likely the `@particle_input` decorator, though the `Particle` class created in #239 is also a possibility.  A good place to look at how to do this might be [`astropy.units.set_enabled_equivalencies`](https://github.com/astropy/astropy/blob/master/astropy/units/core.py#L390).

A caveat to the aforementioned approach is that setting a default ion in an instance of the `Plasma` or `PlasmaBlob` class would be a very natural way to do this.  However, a disadvantage to having this only be in a class is that many plasma physicists would end up preferring to take a functional rather than object-oriented approach.

**Comment by StanczakDominik** [comment]
This sounds like a bad idea, I think. Declaring an implicit stateful variable in the backend of the code for the (minor, I think) convenience of not having to do...
```python
p = 'D+'  # or even a `Particle` object
plasmapy.physics.gyrofrequency(p...)
```

I'm pretty sure however you define it, you're not going to be able to turn it on in less than 7 characters. :laughing: And more seriously, the mechanics of possible implementations... not pretty, let me just say.

Voting to close this one.

**Comment by lemmatum** [comment]
I don't think this is such a huge issue... people should read the docs before using the function anyway. There is only so much naivety we can assume.

And I agree with @StanczakDominik , trying to set a global particle default is a bad idea. Global state in general is a bad idea.
