### ISSUE TITLE
Expands examples in docstrings of `HarrisSheet` and its methods

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2530]
Currently, the docstring for `HarrisSheet` ([permalink](https://github.com/PlasmaPy/PlasmaPy/blob/2c1ee2e74e86d9519d1a306a6f78413683ca9a02/src/plasmapy/plasma/equilibria1d.py#L12)) doesn't contain any examples. It would be helpful to add a simple working example that shows how to use it.

One possibility would be to adapt some of the [tests](https://github.com/PlasmaPy/PlasmaPy/blob/2c1ee2e74e86d9519d1a306a6f78413683ca9a02/tests/plasma/test_equilibria1d.py).

**Comment by Panda5130** [comment]
Is this still an existing issue? Can it be assigned to me? Thanks🐼

**Comment by namurphy** [comment]
@Panda5130 — This is still an existing issue, so I just assigned it to you.  Thank you in advance!
