### ISSUE TITLE
Add examples to docstring of `ParticleTracker`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2532]
Currently, the docstring for `ParticleTracker` ([permalink](https://github.com/PlasmaPy/PlasmaPy/blob/2c1ee2e74e86d9519d1a306a6f78413683ca9a02/src/plasmapy/simulation/particle_tracker/particle_tracker.py#L32)) doesn't contain any examples. It would be helpful to add a simple working example that shows how to use it.

The example shouldn't be too computationally expensive because it will be run every time the documentation is built, so I was thinking of perhaps running it for 10–20 steps.

One possibility would be to adapt some of the [particle tracker tests](https://github.com/PlasmaPy/PlasmaPy/blob/2c1ee2e74e86d9519d1a306a6f78413683ca9a02/tests/simulation/test_particle_tracker.py).

**Comment by Spedi** [comment]
Hi!
Can I work on this issue? Could you tell me more about it?

**Comment by s-gerow** [comment]
Hey, saw this hasn't been assigned. I am working on this now.
