### ISSUE TITLE
Split up `_boilerPlate()` in `transport.py`

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#255]
`_boilerPlate()` currently does a few different things like fetching particle data, calculating thermal velocity, tests/checks. Each piece of functionality should be split into its own function.

See #191

**Comment by StanczakDominik** [comment]
And wait for #191 before starting work on this!

**Comment by apooravc** [comment]
@StanczakDominik  Working on this issue since #191 is now merged.

**Comment by StanczakDominik** [comment]
Awesome! Thank you!
