### ISSUE TITLE
Cleanup transport.py docstrings and documentation

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#256]
We need people both familiar and unfamiliar with transport to look through the docstrings and documentation on `transport.py` to see if it is usable and if it makes sense.

**Comment by lemmatum** [comment]
One thing that was mentioned in #191 is the small differences between thermal velocity definitions and how they affect the Coulomb logarithm. This should be incorporated into the documentation explicitly.

Quote:

> 

> The differences between the old code, the current code, and the table of values listed in Chen are due to differences in how thermal velocity is defined.
> Old code: `sqrt(3 k T / m)`
> Current code: `sqrt(2 k T / m)`
> Chen: `sqrt(k T / m)`
> 
> I checked this by quickly replacing thermal velocity in `_boilerPlate` with a 3 instead of 2 for the coefficient. And I get:
> 
> ```
> Expected: (new code)
>     14.545527226436974
> Got: (old code)
>     14.748259780491056
> ```
> 
> The way I work around this when testing the values from Chen in `test_transport.py` is by adding a factor of `np.log(2)` to the Coulomb logarithm values he lists.
> 
> I think the best way to deal with this is just to mention these difference in thermal velocity definitions explicitly in the docstrings.

**Comment by ayush1999** [comment]
@lemmatum @namurphy  I'd love to take this up. Can you please tell me, along with the above mentioned example, what are the other changes needed?

**Comment by lemmatum** [comment]
@ayush1999 I would suggest you just read through the documentation independent of my input and see if it makes sense. Then run the functions based on the knowledge you gained from reading the documentation and see if they run just fine or if there were any stumbling blocks. Come up with a list of things that we might need to clarify, and then we can discuss them here.

The different definitions of thermal velocity are the most glaring implementation detail that needs to be explicitly stated (since most books state it implicitly).
