### ISSUE TITLE
Different return types for `is_category` method of `ParticleList` than `Particle` & `CustomParticle` 

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2595]
The return type of `ParticleList.is_category()` is `list[bool]`, while the return type of each of `Particle.is_category()` and `CustomParticle`.is_category()` is a `bool`.  I think this is a violation of the [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle), at least approximately.

A collection in Python is considered truthy if it contains anything and falsey if it doesn't contain anything.  For example, `ParticleList(["Fe"]).is_category("isotope")` returns `[False]`, but `[False]` evaluates as `True` because the `list` contains an object.  This led to the problem in #2048.  

One possibility to resolve this would be to have `is_category` return a `bool` that is `True` if all of the contents are `True` by default, and then add a keyword argument that would return this particle-wise.  

```Python
>>> particles = ParticleList(["p+", "He"])
>>> particles.is_category("ion")
False
>>> particle.is_category("ion", particlewise=True)
[True, False]
```
This seems a likely way to reduce the chance of errors, but I want to think out the consequences a bit better first.

**Comment by jwreep** [comment]
Thinking a bit about this logic, but isn't this the difference between `np.allclose` and `np.isclose`? 

```
>>> x = [True, False]
>>> np.isclose(x, True)
array([ True, False])
>>> np.allclose(x, True)
False
>>> y = [True, True]
>>> np.isclose(y, True)
array([ True,  True])
>>> np.allclose(y, True)
True
```

Presumably these could be used.

**Comment by jwreep** [comment]
This issue could be closed, presumably.

**Comment by namurphy** [comment]
@jwreep — thank you!  It turns out that one of the less well known ways to help out an open source project is to comment on old issues that can be closed. I do appreciate it!
