### ISSUE TITLE
Create an `atomic.reduced_mass` function from existing `Particle` method

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#262]
The issue is simple. Take https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/atomic/classes.py#L714 this method and turn it into a module level `reduced_mass` function that can be called outside of the object oriented `Particle` interface, like `ion_mass`. Simplify the method by calling the function. Simple and helps out #255 !

**Comment by ritiek** [comment]
I'll give this a shot. :)

**Comment by StanczakDominik** [comment]
Awesome! Thanks!
