### ISSUE TITLE
what is the unit of temperature defined in the Spitzer resistivity

### ISSUE THREAD

**Issue by Dr-yangyangzhang** [PlasmaPy/PlasmaPy#2643]
### Nature of improvement

In the documentation it reads " Temperature in units of temperature." 
This is not clear. Is the unit Kelven or electron volt? Both of them are units of temperatures.

### Location of improvement

https://docs.plasmapy.org/en/stable/api/plasmapy.formulary.collisions.misc.Spitzer_resistivity.html#spitzer-resistivity

**Comment by namurphy** [comment]
Thank you for raising this issue!  We should clarify that the temperature could either be in kelvin or eV (defined using `astropy.units`) and add an example at the bottom of the docstring that shows how to provide the temperature in eV.  It'd also be worthwhile to double check that this ambiguity exists elsewhere in the documentation.  Thank you again!

**Comment by Panda5130** [comment]
Trying this as a first issue. I am unable to exactly locate the code in the repository. I have tried looking for it by following the path on the docs.plasmapy.org webpage. Could you help me out? What is a foolproof way to find blocks you want to edit? Also, could you help with alternatives to nano to use as a text editor?

**Comment by kuchtact** [comment]
The documentation on the PlasmaPy website for this function is automatically generated from the docstrings of the various python functions so in this case, you can find the "temperature in units of temperature" in the `src/plasmapy/formulary/collisions/misc.py` file under the `Spitzer_resistivity` function. After searching through the files this same text appears elsewhere as well! Good things to fix for the future...

I use Visual Studio Code and it has a feature to search through files for specific words/sentences and it is a pretty good editor for me.

**Comment by namurphy** [comment]
Closed by #2729. Thank you for raising this!
