### ISSUE TITLE
Use mypy for static type checking in continuous integration

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#268]
[Mypy](http://mypy.readthedocs.io/en/latest/) uses function annotations to perform static type checking.  Mypy has the potential to help us track down bugs without even running a program.  Lately we've started to add [type hints](https://www.python.org/dev/peps/pep-0484/) to functions and methods in a few of our subpackages (including atomic, for example) where we sometimes make use of the [typing](https://docs.python.org/3/library/typing.html) package as well.  It would be great if we can use mypy in our suite of tests with Travis CI which would involve updating `.travis.yml` (which is also being edited in #264).

A potential problem is that some return annotations are given as units:
```Python
def func() -> u.eV:
```
I am not sure how mypy will handle that situation.  Some function arguments are going to be annotated with the `Particle` class in order for `@particle_input` to know what to do with them.  That may also make mypy grumpy.  Another thing to worry about is that backwards compatibility is not guaranteed for mypy yet, so we might have to make some further adjustments later on.  I personally am inexperienced with mypy, but [projects such as zulip have added mypy to their Travis CI tests](https://github.com/zulip/zulip/issues/635).

Many thanks to whoever ends up working on this!  (And also thanks to @Cadair for letting us know about mypy!)

**Comment by StanczakDominik** [comment]
Probably best to close this one as we hadn't considered mypy and astropy.units clashing?

**Comment by namurphy** [comment]
I just created a "Snoozed" label to add to this since we could potentially address this in the future, but there doesn't seem to be a viable way to address it now.  I'll try to remember to create an issue on Astropy's repository that discusses this problem.

**Comment by namurphy** [comment]
Re-opening this because there now exists a workaround for `Quantity` type annotations that preserve units (see #1413).
