### ISSUE TITLE
Make  `particle` a required keyword to `ParticleTracker.load_particles`? 

### ISSUE THREAD

**Issue by pheuer** [PlasmaPy/PlasmaPy#2725]
### Feature description

Right now this method assumes that the particles being added are protons, but I wonder if that's really a good default? Maybe that keyword should be required, just to be explicit? 

```python
@particle_input
    def load_particles(
        self,
        x,
        v,
        particle: Particle = Particle("p+"), 

```

### Motivation

Avoid anyone accidentally creating particles with the wrong mass/charge

**Comment by namurphy** [comment]
I'm in favor of this!  Having implicit particle defaults makes silent errors more likely.

Related to: #453.

**Comment by JaydenR2305** [comment]
Ok sounds good, should I implement this in #2712 ? Or should this get its own PR

**Comment by pheuer** [comment]
> Ok sounds good, should I implement this in #2712 ? Or should this get its own PR

Maybe make it it's own, small PR, since it is a potential breaking change to the interface.
