### ISSUE TITLE
Clarify docstring style guidelines in development guide

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#273]
Consistent, well thought out docstring styles help improve readability and make it easier for users to access the information that they are seeking.  We need to improve our [style guide for docstrings](http://docs.plasmapy.org/en/latest/development/doc_guide.html) within PlasmaPy.  We should strive for general consensus on these guidelines within our community if at all possible, so whoever undertakes this should bring these questions up on [Matrix](https://riot.im/app/#/room/#plasmapy:matrix.org).

For the most part, we have been using the numpydoc style guidelines.  A related alternative is [PEP 257](https://www.python.org/dev/peps/pep-0257/).  [Astropy's docstring guidelines](http://docs.astropy.org/en/stable/development/docrules.html) are also worth checking.  We should try to be reasonably consistent with Astropy and SunPy since there's significant overlap among our communities.

Many of the checks can be done automatically using [pydocstyle](http://www.pydocstyle.org/en/latest/) (see also #272).  One recommendation from PEP 8 is to limit docstring lengths to 72 characters to improve readability of plain text, though this has not yet been implemented in [pydocstyle](http://www.pydocstyle.org/en/latest/) or [pycodestyle](http://pycodestyle.pycqa.org/en/latest/intro.html), to the best of my knowledge.  The docstring style guide should be consistent with the pydocstyle defaults set in [`setup.cfg`](https://github.com/PlasmaPy/PlasmaPy/blob/master/setup.cfg).

Thanks!
-Nick

**Comment by StanczakDominik** [comment]
possibly solve this with a bot that tests docstyle
