### ISSUE TITLE
Clarify code style guidelines in development guide

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#274]
Maintaining a consistent coding style makes code much more readable.  We need to improve PlasmaPy's [style guide for Python code](http://docs.plasmapy.org/en/latest/development/code_guide.html) in our [development guide](https://github.com/PlasmaPy/PlasmaPy/tree/master/docs/development).  As in #273, we should strive for general consensus on these guidelines, so whoever undertakes this should bring these questions up on [Matrix](https://riot.im/app/#/room/#plasmapy:matrix.org).

For the most part, we have been using the [PEP 8](https://www.python.org/dev/peps/pep-0008/) style guide.  However, there are some guidelines suggested by [PEP 8](https://www.python.org/dev/peps/pep-0008/) but that are not strictly enforced.  Plus, there are other stylistic choices that we can make to help improve consistency.

Many of the checks may be done using [pycodestyle](http://pycodestyle.pycqa.org/en/latest/intro.html) in conjunction with [pep8speaks](https://pep8speaks.com/).  We will need to make sure the code style guide is consistent with the pycodestyle defaults set in [`setup.cfg`](https://github.com/PlasmaPy/PlasmaPy/blob/master/setup.cfg).

It would probably also be helpful to split our [code guide](https://github.com/PlasmaPy/PlasmaPy/blob/0dbd56b3977b3eb84619cb7e88aa7e711006576b/docs/development/code_guide.rst) into two files.  The sections on how to get PlasmaPy and set it up for development could perhaps go into `getting_started.rst`, while the remaining sections could go into `code_style.rst`.  

This is related to #272 (which set defaults for pycodestyle and pydocstyle) and #273 (which is on clarifying our docstring style guide).

Thanks!
-Nick

**Comment by StanczakDominik** [comment]
Same as #273
