### ISSUE TITLE
Run pydocstyle in tests for each pull request

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#276]
The [pydocstyle](http://www.pydocstyle.org/en/2.1.1/usage.html) package checks that docstrings meet the style guidelines for a package (see #272, #273).  It would be really helpful to run pydocstyle as part of our suite of continuous integration tests.  I'm wondering if CircleCI would be the most appropriate place, and if the tests could be separate from the other tests to make it easier to narrow down what the problem is.

One common source of error in docstrings is backslashes (`\`).  These can mess up doc builds when the docstrings are not raw docstrings.  I've been using beginning docstrings with `r"""` pretty religiously just to avoid the chance that someone else will add a backslash and cause errors that are hard to track down, but this is probably much more than is needed.  If we have pydocstyle raise an error when there are backslashes in regular docstrings, then we can help people track down this sort of error more quickly. 

I'm wondering if it would be best to check only the `*.py` files that were changed by the pull request rather than the whole package, but if we got the whole package to comply with the docstring style guide, then perhaps this wouldn't cause problems.

We might consider having pycodestyle be part of this too, though pep8speaks mostly fills that role.

**Comment by StanczakDominik** [comment]
After some thought, this way of approaching this stuff seems like a workaround that's not even going to lead to a comfortable way of checking it. It would probably be better to suggest this or contribute back to pep8speaks. I'll raise an issue over at their repository.

**Comment by namurphy** [comment]
It'd be fantastic if pep8speaks enabled pydocstyle checks.  I'll label this as "on hold" pending upstream changes.  Thank you for raising this issue!
