### ISSUE TITLE
Create an online_help function?

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#277]
Astropy has an [`online_help`](https://github.com/astropy/astropy/blob/v3.0/astropy/__init__.py#L293) function that lets users query their online documentation from the command line.  This then opens the results in their default web browser.  We may wish to create such a function for PlasmaPy, which could go in our main `__init__.py` or perhaps somewhere in `plasmapy/utils`.

We could use much of the machinery that has already been developed for Astropy's function, and just change it to suit our needs.  We've already put Astropy's BSD license in our `licenses` directory so we have fulfilled the requirements to use any of their code (yay open source!), though we should put a link to the license in any files that include code directly from Astropy.  

One special case worth thinking more about is when users query about units.  In those cases, it may end up being most worthwhile to bring up the documentation for astropy.units within Astropy's documentation.

Thanks!
-Nick

**Comment by manasbedmutha98** [comment]
@namurphy, I'd like to take this if it's still on.

**Comment by StanczakDominik** [comment]
Go for it, nobody's working on it!

**Comment by manasbedmutha98** [comment]
Hi. I've made the function. I've added it to the main __init__.py 
It's my first issue on Github and I'm not sure how and where to push the code. I read a few tutorials. One way I found was to fork it and update which I've done in the [Forked Repository](https://github.com/manasbedmutha98/PlasmaPy/tree/master/plasmapy)
Please help me out on how to go about it.

**Comment by StanczakDominik** [comment]
This is getting closed by #438 (and #446 :) ) so I'll pull the trigger now.
