### ISSUE TITLE
Allow Roman numeral spectroscopic notation to represent ions

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#286]
In astronomy it is common to use Roman numerals to represent the ion species responsible for the emission from a particular spectral line.  The Roman numeral is the charge state of the ion plus one (e.g., Fe I corresponds to Fe<sup>0+</sup> and Fe X corresponds to Fe<sup>9+</sup>).  

Some examples:
```Python
>>> from plasmapy.atomic import *
>>> integer_charge('Fe X')
9
>>> Particle('O VI').ion
'O 5+'
```
It would be worth looking for already existing packages that parse Roman numerals so that we do not need to reinvent this functionality.

I personally dislike this notation because the off-by-one difference is confusing and using Roman numerals greatly decreases readability for high charge states, but it is used commonly enough that we should allow it.

**Comment by ritiek** [comment]
I'll give this a go. The [roman](https://pypi.python.org/pypi/roman) package looks good enough to me.
```python
>>> roman.fromRoman('LXI')
61
```
There are also other packages like [numeral](https://pypi.python.org/pypi/numeral) but I think they are a bit of overkill. What do you think?

**Comment by ritiek** [comment]
> The Roman numeral is the charge state of the ion plus one (e.g., Fe I corresponds to Fe⁰⁺ and Fe X corresponds to Fe⁹⁺).

By the way, is there a reason for doing this? Why can't Fe I correspond to Fe¹⁺? (Fe without any charge specified could just correspond to Fe⁰⁺)
```python
>>> integer_charge('Fe II')
2
>>> integer_charge('Fe')
0
```

**Comment by namurphy** [comment]
I completely agree that it would make much more sense to have Fe I correspond to Fe¹⁺ and so on, but the Roman numeral notation has been a standard notation for spectroscopy that has been used like this for the better part of a century (e.g., [this abstract from ~1930](http://adsabs.harvard.edu/abs/1931ApJ....74..225S)).  I've been trying to use notation like Fe¹⁺ when describing spectra since that's much clearer.

I wonder if the source of the problem was that the roman numeral system doesn't have a symbol that represents zero.

**Comment by StanczakDominik** [comment]
> I personally dislike this notation because the off-by-one difference is confusing and using Roman numerals greatly decreases readability for high charge states

Just wanted to ping and say that I've just started using this functionality, that it is great to have it, and that I fully agree with the above. 😅
