### ISSUE TITLE
Link to open/free references on plasma physics from README.md

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#288]
There have been a few occasions when someone interested in PlasmaPy has asked for recommendations of good resources for learning about plasma physics.  We should link to ~2-4 resources from our main README file.  These should be free and openly available resources, preferably under a CC BY or CC BY-SA license.  One possibility is [edX's introductory course on plasma physics](https://www.edx.org/course/plasma-physics-introduction).  It would also be helpful for there to be a very general overview that would be helpful for someone who doesn't have much background in physics (perhaps something like the [Wikipedia article on plasma](https://en.wikipedia.org/wiki/Plasma_(physics))).  Does anyone have suggestions for other resources?

Thanks!
-Nick

**Comment by lemmatum** [comment]
MIT opencourseware has a bunch of [lecture notes](https://ocw.mit.edu/courses/nuclear-engineering/22-611j-introduction-to-plasma-physics-i-fall-2003/lecture-notes/) on introductory plasma physics by Ian Hutchinson.

We could also link to the [NRL Plasma Formulary](https://www.nrl.navy.mil/ppd/content/nrl-plasma-formulary) for general reference.

Archive.org seems to have some notes/books as well, though I haven't looked through them:
[Introduction to Plasma Physics I - Collated Notes](https://archive.org/details/flooved3263)
[Plasma Physics by Richard Fitzpatrick](https://archive.org/details/flooved3041)
