### ISSUE TITLE
Add documentation on astropy.units

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#292]
Since PlasmaPy makes heavy use of [`astropy.units`](http://docs.astropy.org/en/stable/units/), we need documentation that introduces them and links to Astropy's main documentation on the subpackage.  We should be able to adapt [SunPy's documentation on units](http://docs.sunpy.org/en/stable/guide/units-coordinates.html#units-in-sunpy) (while putting SunPy license information directly in the file if we decide to do so).

We will need a discussion about eV and equivalencies in there too.  While eV are units of energy, they are used extremely frequently in plasma physics as a measure of temperature.  The `astropy.units.temperature_energy` equivalency allows eV to be converted to temperature (essentially by dividing by k<sub>B</sub>), but it is not enabled automatically.  Problems will arise should any of us try to directly use eV as units of temperature without enabling that equivalency (see also #131).

Thanks!

**Comment by StanczakDominik** [comment]
We have some Units docs over at http://docs.plasmapy.org/en/master/development/code_guide.html#units

How urgently do you think we need this? I mean, we've got `astropy.units` references plastered literally in every single docstring. Perhaps it's fine to keep it that way for now?

The temperature energy equivalency does pose problems.

**Comment by StanczakDominik** [comment]
There's some docs for units under constants now. Do you think this will suffice for 0.1, with astropy and sympy docs being awesome?

**Comment by StanczakDominik** [comment]
Sunpy! I love sympy too, though.

**Comment by namurphy** [comment]
All of the above packages are great! :smile_cat:  The release notes in #405 have a paragraph on `astropy.units` with a link to Astropy's documentation, so that should be enough.  The only other thing might be to add a sentence to `docs/index.rst` that points readers to the `astropy.units` documentation.  

Time for bed for me. :zzz:  Hope you have a good day! :sunny:

**Comment by namurphy** [comment]
I added a link to `astropy.units` documentation in the getting started section of the doc index in #405, so I think that's all we need for 0.1.0.  We can save the rest for later versions.
