### ISSUE TITLE
Add mass_energy as a new atomic function and a Particle attribute

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#294]
The nuclear binding energy of a nucleon may be found from the [`nuclear_binding_energy`](https://github.com/PlasmaPy/PlasmaPy/blob/e7912ef7a32487c8193a3f880874b40aa1e4cf7a/plasmapy/atomic/nuclear.py#L18) function of the `atomic` subpackage or with the [`binding_energy`](https://github.com/PlasmaPy/PlasmaPy/blob/e7912ef7a32487c8193a3f880874b40aa1e4cf7a/plasmapy/atomic/particle_class.py#L898) attribute from a [`Particle`](https://github.com/PlasmaPy/PlasmaPy/blob/e7912ef7a32487c8193a3f880874b40aa1e4cf7a/plasmapy/atomic/particle_class.py#L99) instance.  It would be really helpful to have a `mass_energy` function in [`nuclear.py`](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/atomic/nuclear.py) as well as a `mass_energy` attribute of the Particle class in [`particle_class.py`](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/atomic/particle_class.py).  The [`@particle_input`](https://github.com/PlasmaPy/PlasmaPy/blob/e7912ef7a32487c8193a3f880874b40aa1e4cf7a/plasmapy/atomic/particle_input.py#L66) decorator will likely be helpful so that the `mass_energy` function can instead just get the result from the appropriate `Particle` instance.  

Thanks!
-Nick

**Comment by namurphy** [comment]
Also, lease let me know if there is anything missing or there are any mistakes in the `@particle_input` docstring, since few people besides me have read it.

**Comment by Griffintaur** [comment]
Hi , I would like to take this issue. Is it still open for contribution?

**Comment by StanczakDominik** [comment]
Pretty sure it is! Go for it! :)
