### ISSUE TITLE
Allow reduced_mass to accept Quantity arguments

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#295]
The newly created `reduced_mass` function was designed to accept particle representations as well as instances of the `Particle` class (see #262 and #265).  Upon further thought, it would be helpful for `reduced_mass` to accept `Quantity` objects with units of mass.  Reduced masses are used not just in Coulomb collisions but also in orbital mechanics, for example.  A sample use case is:

```Python
>>> import astropy.units as u
>>> mass1 = 5.6 * u.kg
>>> mass2 = 3.5 * u.kg
>>> reduced_mass(mass1, mass2)
<Quantity 2.15384615 kg>
```

Thanks!
-Nick

**Comment by StanczakDominik** [comment]
Actually, yeah, it's already done. Thanks for pointing this out, @ritiek! Closing.
