### ISSUE TITLE
Add narrative documentation for transport.py

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#298]
There is an incredibly extensive amount of functionality in `transport.py`.  We will need to have narrative documentation in our `docs` directory that goes over how to use this module.  Given the difficulty of the subject, the transport documentation will need to be written by people who have a good understanding of plasma transport theory.  The documentation should be useful and understandable to someone who is taking their first class in plasma physics.  We will need this for our v0.1.0 release.

Thanks!
-Nick

**Comment by lemmatum** [comment]
I'll get on the `collisions.py` documentation once #303 is done.

**Comment by lemmatum** [comment]
Look at [atomic narrative doc](https://github.com/PlasmaPy/PlasmaPy/tree/master/docs/atomic) for example. Place transport narrative docs [here](https://github.com/PlasmaPy/PlasmaPy/tree/master/docs/physics/transport)

**Comment by lemmatum** [comment]
- [ ] Check if `collision_rate_electron_ion` docstring in `collisions.py` compiles correctly. Especially `* nu_e\i_S from ref [2]_ eqn (1) pp. #,`
