### ISSUE TITLE
Set up and automate documentation builds using Read the Docs

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#30]
One of the things that we should probably do sooner rather than later is to set documentation up for PlasmaPy on Read the Docs.  We have a choice between [reStructuredText](http://docutils.sourceforge.net/rst.html) (reST) and [Markdown](https://daringfireball.net/projects/markdown/).  For reST we would be using [Sphinx](http://www.sphinx-doc.org/en/stable/rest.html).  Astropy appears to be mostly using reST and Sphinx so I'd vote for mostly using that also since we can then ask them for help. :-)  We'll also need to set up extraction of docstrings for the different methods within PlasmaPy.  

These instructions look very helpful: [Getting started with Read the Docs](https://docs.readthedocs.io/en/latest/getting_started.html)

Thank you!

**Comment by SolarDrew** [comment]
I have a little experience with Sphinx and easy access to people with more, so I'm happy to have a go at this.

**Comment by colbych** [comment]
I took a crack at this and I got something pretty to drop out.

Here is a ReadTheDocs for PlasmaPy: http://plasmapy.readthedocs.io/en/docs/
I set it up using Sphinx and reST and I used autodocs to read in the docstring.

Right now it is built based off of my docs branch on my fork, that is now in the pull request section as well (#43 to be exact).

**Comment by Cadair** [comment]
I would highly recommend using the automodapi Sphinx extension developed by astropy. https://github.com/astropy/sphinx-automodapi it has some nice improvements over the top of autodoc

**Comment by colbych** [comment]
I'll give astropy autodo a go and see what it does.

**Comment by StanczakDominik** [comment]
#43 closed this one :)
