### ISSUE TITLE
Create benchmarks

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#305]
Optimizing code is hard if you don't know what's running slowly and how your changes affect execution time. We should create some scripts to benchmark important, frequently run functions (especially with respect to simulations). 

I assume that at the lowest level we would use [cProfile](https://docs.python.org/3.6/library/profile.html), though I think there are some libraries which make the output from cProfile prettier.

Some questions:
* Should profiling be integrated into testing? (will likely slow things down a lot)
* Should we track benchmarks over time and is there a convenient way to automate profiling, saving, and visualizing profiling history?

**Comment by lemmatum** [comment]
A good first effort would be to work in tandem with #304 and profile `parameters.py` vs. `parameters_cython.pyx`

**Comment by lemmatum** [comment]
Useful [podcast with links](https://talkpython.fm/episodes/show/28/making-python-fast-profiling-python-code) on profiling/visualization.

**Comment by StanczakDominik** [comment]
> Should profiling be integrated into testing? (will likely slow things down a lot)

It will, and during development you most likely want quick feedback on whether you broke stuff *first*, and feedback on how much you slowed your code down only then (though really large slowdowns will be visible through slower tests anyway). However, another job, like we have for docs and latex, could be a good way of solving this. 

Or we could assume doing stuff that requires benchmarks is rare enough that we could run them locally, maybe via predefined function (sort of like the `plasmapy.test()` we wanted to implement a while ago). 

> Should we track benchmarks over time and is there a convenient way to automate profiling, saving, and visualizing profiling history?

Good questions! I haven't heard of solutions for these yet.

**Comment by lemmatum** [comment]
I imagine there is a way to make profiling part of our pipeline for each minor release, that way we only have to do it once in a while. And we can also have some script for manually exposing it when we are working on optimizations locally. I think this would avoid the problem of slowing things down on each PR.

**Comment by StanczakDominik** [comment]
We have benchmarks now! http://www.plasmapy.org/plasmapy-benchmarks/
