### ISSUE TITLE
Getting started docs

### ISSUE THREAD

**Issue by SolarDrew** [PlasmaPy/PlasmaPy#31]
We should have some introductory documentation for new users. This should cover:

- Creating and using Plasma objects
- Brief introduction to Astropy units (or whatever, if we end up switching to another package)
- Overview of available plasma parameters

This (and other narrative docs) should be in addition to the autogenerated docs from Sphinx (#30).

**Comment by SolarDrew** [comment]
ping @PlasmaPy/plasmapy-community . Feel free to add anything I've forgotten to that list.

**Comment by antoinelpp** [comment]
Hi,
Is there already something that parse the doc-strings and generate docs ?
I'm not sure if Sphinx can do that...

**Comment by StanczakDominik** [comment]
I think what we have right now could be considered sufficient to close this issue. @SolarDrew, whatcha think?
