### ISSUE TITLE
Diagnostic class

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#313]
In the same vein as the Plasma blob class, there ought to be a class for describing diagnostics. This can then be inherited by specific diagnostics, e.g., spectrometer, interferometer, Langmuir probe, B-dot probe, polarimeter, etc.

If we want to model a measurement we can then feed a plasma blob, plus diagnostics (and geometry), to a function, for example BICEP2 + dusty plasma :smirk: 

My current thinking is that the `Diagnostic` class will contain some abstract information, such as, `position`, `orientation`, and possibly `dimensionality` of the data the diagnostic records. 
* 1D: spectrometer without spatial or temporal resolution, time-resolved Langmuir probe
* 2D: emission photo, spatially or temporally resolved spectrometer
* 3D: holographic measurement
* 4D: for a light field measurement

We would have to implement the `dimensionality` property in a flexible way, as many diagnostics can readily change their `dimensionality` (usually reducing via integration, but sometimes increasing via the addition of a component, such as a microlens array)

Question: if we implement `dimensionality` as a property, should "intensity" of the signal be considered when counting dimensions? For example, is a time-resolved voltage measurement from a probe 1D (just time) or 2D (time and voltage)? I normally hear these diagnostics referred to as 1D. I also normally hear CCD images referred to as 2D.

**Comment by namurphy** [comment]
In [PySat](https://github.com/rstoneback/pysat), there is the [`Instrument`](https://github.com/rstoneback/pysat/blob/8cb88aeff8f3ec913b6296bc7fba43d4b1428d11/pysat/_instrument.py#L27) class which might give us some insight in how to build a `Diagnostic` class.
