### ISSUE TITLE
Expand coverage for `PlasmaBlob` tests

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#315]
Most of the work here is just adding multiple plasma configurations to hit the various possible regimes for coupling and degeneracy.

**Comment by ritiek** [comment]
I'll give this a shot. :)

**Comment by not7cd** [comment]
#320 resolved this issue

**Comment by StanczakDominik** [comment]
That it did. Thanks, @not7cd!
