### ISSUE TITLE
Generalize `ion_sound_speed`

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#316]
Currently `ion_sound_speed` under `parameters.py` only works in the limit `alpha = 1 / (k * lambda_De)` is large(?), such that the plasma is not dispersive. This should be generalized for all values of `alpha` and the docstring should be edited to reflect this generalization.

The general equation is on pg 2 of this [Google Doc](https://docs.google.com/document/d/1EcuxYoSzy-MpjjjqBE3E6zE8g6xYU2BH1MorU7_DQQA/edit#heading=h.88burrsgujyu). Please note that this equation is for `omega`, whereas what we want is `v = omega / k`, so just drop the `k` on the right hand side.

**Comment by featTheB** [comment]
I'm taking the issue.

It seems to also have an issue with the `check_quantity` decorator. I'm receiving `check_quantity() got an unexpected keyword argument 'B'`

**Comment by tvarnish** [comment]
I'll work on this!

**Comment by tvarnish** [comment]
@lemmatum (and/or @StanczakDominik): do we want to define `alpha` as a new parameter, or should `k` and `lambda_D` be passed into `ion_sound_speed` (or would you rather we called the `Debye_length` function inside `ion_sound_speed` instead)?

**Comment by StanczakDominik** [comment]
Go for it, and feel free to call debye length from within it!

**Comment by tvarnish** [comment]
I've written a basic implementation of the updated function, but I've realised I'll need to update the examples and tests for `ion_sound_speed` since it's now got a couple of new input parameters. 

@StanczakDominik are there any tips/pointers (or rules) for choosing some example/test values for `n_e` (for `Debye_length`) and `k` (wavenumber)?

**Comment by StanczakDominik** [comment]
To be honest, I usually just put in some reasonable physical values - if I
have existing values I can compare test results to, I use those.
