### ISSUE TITLE
Create "shot sheet" interface in HDF5

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#319]
It's common to have what is known as a "shot sheet" on experimental runs. These are meant to track the shot number, date, time, diagnostics fielded, data acquired, calibration/setup, as well as comments (such notes on failed shots/diagnostics).

Unfortunately many groups use spreadsheets, such as Excel, to track this information. None of the information is linked to the actual raw data, and it is generally poorly managed. If we want to help push the notion of open science we should help standardize the practice of managing experimental data.

One small step would be to create a couple of functions to manage experimental data using HDF5 via [h5py](http://www.h5py.org/). This should include:
* a function to create a new HDF5 database
* a function/UI to interactively enter data while on experiment (features include: preventing overwrites of previous data, automatically adding a time stamp  for when data is entered)
* automatically generated logs to summarize data entry/modification (to easily check if something goes wrong as well as have a report summarizing progress on the experiment)
* functions to easily read and iterate through data of a certain kind (e.g. fetch all non-failed interferograms)

The functions for data entry would be in a hierarchy, starting from the top:
1. Create database
2. Create shot within database
2a. Enter comment on shot
3. Create instrument within shot
3a. Enter instrument attributes (e.g. position, orientation, voltage, and other configuration parameters)
3b. Enter comment on instrument
4. Enter data within instrument
4a. Enter calibration data
4b. Enter experimental run data

My questions:
* Are there any such toolsets out there already (and in common use)?
* Are those tools as easy/flexible to use as what I am proposing here?

**Comment by lemmatum** [comment]
If people think this would be valuable addition to PlasmaPy, I would be happy to take this issue on as I need to do it for my data anyway. (two birds with one stone)

**Comment by jasperbeckers** [comment]
I feel like this would be branching out too far. I like the idea very much but I do not see the immediate, specific relevance to plasma physic. Maybe it could be the basis of a distinct experimental data handling package.

**Comment by lemmatum** [comment]
@jasperbeckers that's fair. My thought was that if we implemented it here we can get the seed started without having to go through the efforts of making a separate package and then if it does indeed grow large enough it can be forked into it's own repo.
Also, one could integrate plasma physics analysis with the shot sheet data structure, though this could be done just as well by making a generalized data handling package and then importing/inheriting into Plasmapy.
