### ISSUE TITLE
Create Coulomb collision cross-section function

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#327]
Create a cross-section function for Coulomb collision under `collisions.py`. This should effectively be `sigma` under `collision_frequency`. Replace instance of `sigma` with this new function.

**Comment by ritiek** [comment]
> Note that the `sigma ~ pi * b_perp ** 2` definition of the Coulomb collision cross-section is only valid for large angle collisions

Just wanted to clear some confusion. This definition matches [the one in the docs](http://plasmapy.readthedocs.io/en/latest/api/plasmapy.physics.transport.collision_frequency.html) but is there a reason for `(2 * bPerp)` in the source code?

https://github.com/PlasmaPy/PlasmaPy/blob/166747196434232946086a36ae916fbfc65d6bc6/plasmapy/physics/transport/collisions.py#L717

**Comment by lemmatum** [comment]
@ritiek Note that `sigma ~ pi * b_perp ** 2` is using `~` (similar) rather than `=` (equals). When we use `~` in physics the tendency is to keep variables but drop coefficients, and equations written in this form are there to give an idea of what are the important effects/parameters rather than to be precise.

`sigma = pi * (2 * b_perp) ** 2` is correct, and it follows the general definition for a collisional cross-section between two particles. `b_perp` is essentially the radius of a particle, but one must account for the radii of both particles in the interaction, as [illustrated here](https://en.wikipedia.org/wiki/Cross_section_(physics)#Collision_among_gas_particles).

**Comment by lemmatum** [comment]
@ritiek we can of course replace the equation in the docs with the more precise version, to eliminate any ambiguity.

**Comment by lemmatum** [comment]
If we have time, we should do this for 0.1 (as it is quite easy), if not it can easily be put off until later.

**Comment by StanczakDominik** [comment]
This is what I actually closed in #388.

Holy wow, we're at 389 already?!
