### ISSUE TITLE
Create a CouplingWarning

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#330]
Create a `CouplingWarning` similar to `RelativityWarning`. This should raise a warning for functions that rely on the weakly coupled regime to be valid.

- [x] Create `CouplingWarning`
- [x] Add this warning under `Coulomb_logarithm` and related functions for when `ln_Lambda < 2` (consistent with floor on `"GMS-3"`) for `"classical"`, `"GMS-1"`, `"GMS-2"`, and possibly `"GMS-3"`methods.
- [x] Add this warning for functions that rely on the weak coupling assumption, making sure to calculate the coupling parameter and testing if `coupling > 0.01`, consistent with `PlasmaBlob`. (Or the relevant coupling/validity check for that function if it has a different one - like `Coulomb_logarithm`).

**Comment by StanczakDominik** [comment]
> Add this warning under Coulomb_logarithm and related functions for when ln_Lambda < 2 (consistent with floor on "GMS-3") 

Won't that just warn always? Shouldn't we skip the warning in there?

**Comment by lemmatum** [comment]
@StanczakDominik yea I think it makes sense to skip the warning for GMS-3. Whoever is using that function should know what it is doing.
