### ISSUE TITLE
Check that correct velocity is used in collision_frequency

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#342]
`collision_frequency` uses the Coulomb logarithm, but in [most places](https://github.com/PlasmaPy/PlasmaPy/blob/28156768b242564265e33b3baf8ae231f1a7c166/plasmapy/physics/transport/collisions.py#L664) the argument for velocity to `Coulomb_logarithm` is `np.nan`. I'm not sure that this is correct.

``` Python
        cou_log = Coulomb_logarithm(T,
                                    n,
                                    particles,
                                    z_mean,
                                    V=np.nan * u.m / u.s,
                                    method=method)
```

We should check if just passing the velocity would be more efficient and correct.

**Comment by lemmatum** [comment]
Related to #348

**Comment by StanczakDominik** [comment]
Let's do this for 0.2
