### ISSUE TITLE
Resolve DeprecationWarnings associated with Quantity comparisons

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#345]
When running our tests on Travis CI, we are getting a bunch of warnings associated with something like `astropy.units.Quantity` objects.  We should track down the reason why we are getting this `DeprecationWarning` so frequently, and resolve it if possible.  If it's something in Astropy itself that hasn't been addressed in the development version, then we could contribute an upstream fix or just ignore it until something breaks.
```
plasmapy/atomic/atomic.py::plasmapy.atomic.atomic.common_isotopes
 /home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/units/quantity.py:1016:
DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
    return super().__eq__(other)
```

To get each `DeprecationWarning` to show up in pytest, we can put the following lines under the `[tool:pytest]` in `setup.cfg` (though we don't want these enabled by default):
```
filterwarnings =
    once::DeprecationWarning
    once::PendingDeprecationWarning
```

**Comment by StanczakDominik** [comment]
After much deliberation, I have come to the conclusion that I dunno.

It's something between `common_isotopes`, `isotopic_abundance` and `known_isotopes`, but at the same I haven't been able to pinpoint exactly where they happen. They also pop up in multiple places in `test_atomic`.

**Comment by lgoenner** [comment]
I took a look at this and the biggest issue is [here](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/atomic/particle_class.py#L428): 
`if attributes['half-life'] == np.inf * u.s`
Sometimes `attributes['half-life']` is a string (see [here](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/atomic/isotopes.py#L974) or [here](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/atomic/isotopes.py#L407)), which causes the comparison with a Quantity to raise a warning.

Most of the `AstropyDeprecationWarning `come from implicit boolean casts such as [this one](https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/classes/sources/tests/test_openpmd_hdf5.py#L53).

**Comment by lgoenner** [comment]
Currently creating a PR with some example fixes
