### ISSUE TITLE
Describe our standard way to represent tensors in contributor guide

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#355]
For better or for worse, plasma physics tends to involve a lot of tensors.  This includes frequent usage of dyadic tensors with notation that isn't used that frequently outside of our field.  We should figure out a standard way of representing tensors, both for symbolic manipulation and for situations where we need numerical values.  These objects should be able to be operated upon, including with double dot products (which, from what I understand, aren't always defined the same way).  

We will also need good, easy-to-understand documentation on the tensor calculus used in plasma physics, especially for notations that are not frequently used outside our field.  

Does anyone know of any libraries that can be used to represent and work with tensors, including dyadic tensors?

Do any of you have favorite references on tensor calculus as used in plasma physics?  One of my favorites is lecture 2 of Dalton Schnack's book on Lectures in Magnetohydrodynamics.

Are there any particularly good references on tensor calculus as used in plasma physics?

**Comment by lemmatum** [comment]
Aren't tensors just linear algebra? I would think numpy and scipy cover most of the operations we need for this.
scipy seems to have a [tensordot function](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tensordot.html) and here is scipy's [linear algebra library](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html). There also seems to be an initial implementation for a [scikit-tensor library](https://github.com/mnick/scikit-tensor). Perhaps we can contribute to that one as the need arises.

There are some more exotic things, like quaternions, which may be a bit more complex (pun intended), but they can be implemented as a class with numpy arrays under the hood. I've actually got a quaternion class that I made for a raytracer, I can push it here if we ever need it.

**Comment by tulasinandan** [comment]
I agree with @lemmatum that scipy's linear algbera should suffice. However there is a related discussion to be had about tensors.

I have been thinking about it for a long itme now. Not the "tensor implementation" per se, but the organization of simulation data around these ideas. Right now in TurbPlasma I simply have each component loded as a scalar (for vectors as well as tensors like pressure) but it would be nice to have a convenient interface to scipy's linear algebra library.

It's more a problem of data organization than anything else. Should we take it up here itself or should I open a new issue?
