### ISSUE TITLE
improve auto pep 8 style suggestions

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#357]
https://github.com/PlasmaPy/PlasmaPy/pull/356#comment-181546823

There's a bunch of stylistic issues we possibly could check automatically that we aren't. For starters, checking that we have multiple arguments on separate lines could be nice!

**Comment by namurphy** [comment]
There was a command for pep8speaks to create a PR that has suggestions on PEP8ifying the code by using autopep8.  I tried this once, and though we decided on a 99 character line limit, it suggested shortening lines to 79 characters.  It'd be helpful to make sure that autopep8 in conjunction with pep8speaks allows lines up to 99 characters.
