### ISSUE TITLE
Coulomb_logarithm raises RelativityError instead of RelativityWarning

### ISSUE THREAD

**Issue by ritiek** [PlasmaPy/PlasmaPy#359]
The [docs mention that](http://plasmapy.readthedocs.io/en/latest/api/plasmapy.physics.transport.Coulomb_logarithm.html#coulomb-logarithm) `physics.transport.Coulomb_logarithm` raises a `RelativityWarning` if the input velocity is greater than 5% of the speed of light.

But in actual it results in `RelativityError` instead of `RelativityWarning`:

```python
>>> from plasmapy.physics.transport.collisions import Coulomb_logarithm
>>> import astropy.units as u
>>> n = 1e19*u.m**-3
>>> T = 1e6*u.K
>>> V = 4e8*u.m/u.s
>>> particles = ('e', 'p')
>>> Coulomb_logarithm(T, n, particles, V=V)
```
```
RelativityError: V is yielding a velocity that is 1.334 times the speed of light.
```

**Comment by StanczakDominik** [comment]
Working as intended! Check relativistic is supposed to warn at speeds from 0.05 to 1 c and raise an error above that. Perhaps the error message could be reworded to say it's, for example, 7% c for a warning and 120%c for an error.

**Comment by ritiek** [comment]
Ah, I see. Yep, I think it would be nice to add `RelativityError` along with `ValueError`, `UnitConversionError`, etc. in errors raised.

**Comment by StanczakDominik** [comment]
I remember wondering why we didn't have one! Wanna try? That should be the only place it's going to pop up right now.

**Comment by ritiek** [comment]
This seems to be the case with most functions in [`collisions.py`](https://github.com/PlasmaPy/PlasmaPy/blob/166747196434232946086a36ae916fbfc65d6bc6/plasmapy/physics/transport/collisions.py). I'd be happy to make a PR!
