### ISSUE TITLE
Get onto the Python Package Index

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#36]
You can do `pip install astropy`. The rest seems self-explanatory.

It's nothing urgent, if we want to wait until this is somewhat feature-stable, that's completely fine. I suppose we're going to want to be out there eventually, though.

**Comment by namurphy** [comment]
Yes, getting on PyPI will be important!  My vote would be to wait until we have version 0.0.1 which will have better feature stability, as you brought up.  Hopefully we can do that in the next few months, though we still need to decide what our first micro release will include!  I would also be okay with getting on PyPI sooner if we decide there are good reasons to do so.  Thank you for bringing this up!

**Comment by SolarDrew** [comment]
I'm happy to do this, there were some sessions at Python in Astronomy on exactly this process that I've been meaning to go back over.

**Comment by namurphy** [comment]
I tentatively put this as part of the v0.1 milestone since that's the latest we'd want to do this, but I'm curious if we would want to put a development version up on PyPI sooner than that.  Part of the reason is that I'm worried that a group of hematologists will decide to name something "PlasmaPy" on there before us!

**Comment by colbych** [comment]
I am just copying this over for the HipChat, cause I thought it was cool and I wanted to keep track of it even if we stop using hipchat:

you can now download PlasmaPy  0.1dev1 from here: https://testpypi.python.org/pypi/plasmapy/0.1.dev1156
and install it with `pip install -i https://testpypi.python.org/pypi plasmapy`
```pip install -i https://testpypi.python.org/pypi <yourpkgname>```

**Comment by thakkardharmik** [comment]
@StanczakDominik  I would like to help on this. Please guide me on what needs to be done.

**Comment by StanczakDominik** [comment]
Hey @thakkardharmik, nice to see you being interested in helping out with this! I may have been mistaken with the Help wanted label though, as I forgot @colbych has already gotten this mostly done though :( @colbych, is there anything you need help with to port this to PyPI proper?

**Comment by colbych** [comment]
Hey @thakkardharmik and @StanczakDominik! I did not actually do this. If I remember right @SolarDrew did this and posted this on hipchat back when we were using that. I wanted to archive the information somewhere, so I added it here.

**Comment by SolarDrew** [comment]
It was indeed me :) I can't remember exactly what needed to change for setting up on proper PyPI, but it's not a lot. @thakkardharmik, I'll look into it tomorrow and put a list here of the things that need doing and you can take your pick. And thanks for getting involved :)

**Comment by Cadair** [comment]
It is probably worth registering the plasmapy name on pypi proper even if you don't upload a package yet.

**Comment by thakkardharmik** [comment]
@SolarDrew Can you please update if there is anything I can get involved with? Thanks.

**Comment by StanczakDominik** [comment]
It seems to be working nicely, so I'll close this one!

@thakkardharmik please check back with us on the Gitter/Matrix room, we'll find you something to get involved with!
