### ISSUE TITLE
Contribute a paper to scipy proceedings before May 21st

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#362]
> Congratulations on having your abstract "PlasmaPy: beginning a community Python package for plasma physics" accepted for this
year's event -- we look forward to seeing your poster or presentation! As in
the past, SciPy 2018 will release a conference proceedings prior to the
start of the conference, and you are invited to contribute a full-length paper
(up to 8 pages) expanding on your abstract.

> The proceedings are aimed at highlighting significant contributions to 
scientific computing in Python, such as:

> - new software packages that support the Scientific Python Stack
> - domain-specific applications of Python in any field of research
> - significant improvements to existing software packages
> - hardware systems designed to support the Python stack
> - applications of scientific computing in education

> To submit a paper to the proceedings, submit a pull request to https://github.com/scipy-conference/scipy_proceedings.

> Papers must be submitted as pull requests by May 21st, 2018. 

> At that point, the six-week open review period begins. During this time, members
from the program committee and the scientific Python community at large will
provide feedback, which should be addressed through discussion on GitHub and by
updating the pull request.

> When submitting a paper to the proceedings, you may be contacted by the
Proceedings Chairs to assist in reviewing at least one paper.

> Further instructions can be found here:
  https://github.com/scipy-conference/scipy_proceedings#instructions-for-authors

> You can see all the papers that have been submitted so far at this site: 
  http://procbuild.scipy.org

> Sincerely, the SciPy 2018 Proceedings Chairs,

**Comment by lemmatum** [comment]
Should we make a repo or directory for this (and perhaps all future papers)? We could then have circle-ci or similar run over it to compile the LaTeX, have everyone contribute/review, etc.

**Comment by StanczakDominik** [comment]
That's a sick idea. I'll try to set that up if I have time before Sunday. If I don't manage to do it, I'd appreciate somebody setting up either this solution, a google doc, share latex

**Comment by StanczakDominik** [comment]
Crossposting an email:

Registration
------------
All SciPy presenters must be registered for the conference!
You can register here: https://scipy2018.scipy.org/ehome/299527/648109/

Bio and Picture
---------------
All speakers are encouraged to send along a brief bio and picture to accompany
their talk. If you have not yet done so, please email them to
scipy@enthought.com

Talk and poster guidelines
--------------------------
Information about schedules, aspect-ratios, dongles, and more can be found on
our Info for Presenters page.
https://scipy2018.scipy.org/ehome/299527/648134/

Proceedings
-----------
You should have received an email from the proceedings committee inviting you
to submit a paper to the SciPy2018 conference proceedings (participation in the
conference proceedings is awesome, but not required). If you did not you can
find submission information and instructions on the conference proceedings
GitHub repo.
https://github.com/scipy-conference/scipy_proceedings#instructions-for-authors

**Comment by lemmatum** [comment]
I was able to setup such a system in gitlab - so it shouldn't be too hard to setup autocompilations here. It's just a matter of how we want to organize it within the project directory structure.

**Comment by lemmatum** [comment]
@namurphy thoughts?

**Comment by lemmatum** [comment]
Decided to forgo in favor of PoP publication as per #159
