### ISSUE TITLE
Numerical type bounds

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#367]
Numerical types (floats, integers, etc) can have different bit lengths and therefore different minimum and maximum bounds across platforms. We've already encountered this with Appveyor having a different integer length than Travis, and with Travis having a different float size from local tests when designing tests.

We should implement a way to handle, or at least warn, about these issues. I would suggest starting with a module that fetches the bounds on different numerical types for the specific platform that PlasmaPy happens to be running on. This module can then be used to implement some generic test which checks for values exceeding these bounds. This would be most immediately relevant for testing modules, but we also need to keep such bounds in mind when designing our code. it's just good practice for cross-platform compatibility.

How to packages like numpy and scipy handle this?

**Comment by StanczakDominik** [comment]
This was mostly an issue for `mpmath`. For now, it seems mostly out of scope, but we can revisit it if needed.
