### ISSUE TITLE
Move Langmuir visualization into separate functions

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#372]
Simple enough issue, just clean up the code a bit by moving the visualization functionality, for example [here](https://github.com/PlasmaPy/PlasmaPy/blob/eb01d257d06765eeb54bb7a1032b66511803f25d/plasmapy/diagnostics/langmuir.py#L323), into separate function(s).

**Comment by wgibson15** [comment]
I'm willing to work on this issue if help is still needed

**Comment by StanczakDominik** [comment]
Sure @wgibson15, go right ahead!

**Comment by anthony-vo** [comment]
Is this still needed to be done?

**Comment by StanczakDominik** [comment]
Yeah, I reckon the code would be quite a bit cleaner if those `if` blocks were pulled into separate functions!

**Comment by anthony-vo** [comment]
So you mean putting all of them in _helper functions? Each block is specific to the function it's already in so I guess it is a bit confusing as to what one can do to refactor them. I'm working on this.

**Comment by StanczakDominik** [comment]
If I remember correctly, those plots had a bunch of common features -
perhaps it would be possible to combine them into a single function that
does general plotting of this kind of data, with flags to toggle
functionality.

But I guess if you think that makes no sense, you may well be right and we
could close this issue...

**Comment by anthony-vo** [comment]
I'll see what I can do til the end of this week.

**Comment by MGedney1** [comment]
Is this still open?

**Comment by StanczakDominik** [comment]
I'd call it *open but not entirely certain if necessary*. I think it'd be
better to close this...
