### ISSUE TITLE
Add references in plasmapy.langmuir docstrings

### ISSUE THREAD

**Issue by jasperbeckers** [PlasmaPy/PlasmaPy#374]
At the moment the `plasmapy.langmuir` docstrings lack references altogether. These need to be added ASAP. A small part of the functions (namely initial fitting parameters and electron temperature-based offset of the exponential region extraction) are empirical. Is that fine?

**Comment by StanczakDominik** [comment]
It's absolutely fine! That needs to be written down and available right there in the docs though.
