### ISSUE TITLE
Improved ion saturation current method

### ISSUE THREAD

**Issue by jasperbeckers** [PlasmaPy/PlasmaPy#380]
The current implementation - very naively - assumes that the ion current will, given a sufficiently negative bias, saturate perfectly so that the minimum current of the characteristic is the best approximation of the ion saturation current. This neglects sheath expansion; a better method would be to obtain the intersection of a linear fit to the ion current in log space with the floating voltage `V_F`. This implies that current ion saturation currents, and therefore ion densities, are to some extent overestimates.

**Comment by lemmatum** [comment]
And here I was about to open an issue on sheath expansion and saturation currents that are never quite saturated because they can gradually increase with voltage :smile:
