### ISSUE TITLE
Add doc page on authors and credits

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#402]
It would be really helpful to have a page in our `docs` directory that lists the Coordinating Committee members and a full list of authors of the code, along with other credits.  Some examples are Astropy's [Authors and Credits page](http://docs.astropy.org/en/stable/credits.html), and SunPy's [The Project](http://sunpy.org/team.html).  The list of code contributors can already be accessed from our GitHub repository and the commit log; however, this often does not include full names.  We might be able to find a way to automate this, though that's low priority.  We should do this prior to our 0.1 release.

To help with the organization, we should probably create an `about` subdirectory that will include pages about the PlasmaPy project as a whole, including this one.  The `docs/stability.rst` page could go in this directory too.

**Comment by ritiek** [comment]
Just for future reference, full names of contributors can be accessed via the GitHub API using this Python wrapper https://github.com/PyGithub/PyGithub:
```python
from github import Github

# Generate a token at https://github.com/settings/tokens
token = "XXX"

g = Github(token)

repo_name = "PlasmaPy/PlasmaPy"
repo = g.get_repo(repo_name)
contributors = repo.get_contributors()

for contributor in contributors:
    if contributor.name:
        print(contributor.name)
    else:
        # Fallback to login name if user has not
        # set up their real name on GitHub
        print(contributor.login)
```
