### ISSUE TITLE
Discuss release schedule

### ISSUE THREAD

**Issue by SolarDrew** [PlasmaPy/PlasmaPy#419]
It might be useful to consider having a (semi?-)regular release schedule, at least for minor/bugpatch/dev releases, so we should talk about that in the near future and decide if that's something that would work for us.

**Comment by namurphy** [comment]
Good idea!  I suspect that it would be good to plan on a patch release about a month after each minor release, and then after that as needed.  For `0.*.*` versions, I think we should only do patch releases for a version until the next minor version comes out.  It would be good to plan on a minor release no less frequently than every six months, since that way users aren't waiting unnecessarily long.

We should incorporate what we decide here into https://github.com/PlasmaPy/PlasmaPy-PLEPs/pull/8.

**Comment by SolarDrew** [comment]
That all seems reasonable to me. Specifically in the context of 0.1, we found quite a lot of things during the release process that could be improved upon, and since I'm at pyastro this week I can probably get a lot of them sorted. So we may be able to have 0.1.1 sooner than a month, if we want to.

**Comment by lemmatum** [comment]
Also what sort of release schedule do we want for major releases? Do we want `x` number of minor releases per major release?

We should avoid eternally being in minor release versions (like some other python projects... *cough* flask *cough*).

**Comment by SolarDrew** [comment]
I don't know that it's necessarily worth deciding ahead of time how many of any particular release type we want. I figure we'll generally just release bug fixes until we have enough new features for a minor release, and then we'll have even more bugs to patch :P

As for sub-1.0 releases, I think there is a reasonable argument for doing that but I agree we probably shouldn't.

**Comment by StanczakDominik** [comment]
Given that 0.2.0 is afoot and we've sort of decided that yes, we want more frequent, smaller releases, what's left is deciding on frequency.

Ideas?

Does 6 months, as a baseline, sound okay? In which direction do we want to adjust from that?

**Comment by namurphy** [comment]
I'd be happy with a baseline release frequency of `(6 * u.month) ** -1`.  If we have a period of a lot of updates, then we could perhaps try something like `(4 * u.month) ** -1` instead.

**Comment by Tiger-Du** [comment]
From recent discussion, it seems that 3-4 minor releases per year is what has been agreed on at the moment.

Also, it was mentioned that date-based versioning is under consideration for versions after 1.0.0.

**Comment by StanczakDominik** [comment]
Thanks for documenting these notes, @Tiger-Du, that's really helpful!

To be more explicit - the current idea seems to be that we go with good old zero-ver until we decide we're satisfactorily stable; then switch to date based versioning for what would be 1.0. Might change in the future.

**Comment by namurphy** [comment]
Yes, thank you!  If we ultimately do go with date based versioning, we would need to update [PLEP 5](https://github.com/PlasmaPy/PlasmaPy-PLEPs/blob/master/PLEP-0005.rst).
