### ISSUE TITLE
Test against minimum versions of required packages

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#424]
We have defined minimum versions for many of our required packages in our `requirements` directory.  However, to the best of my knowledge we do not explicitly test against the minimum versions to make sure that PlasmaPy works with them.  It would be really helpful to add a test to Travis CI or AppVeyer that specifically tests the minimum supported versions as listed in those files.

One thing that we should be careful of is that the version on PyPI for the `roman` package differs from the `roman.__version__` attribute.

It would be most helpful to set things up so that the minimum versions are taken directly from `automated-code-tests.txt` rather than us having to type in and update the minimum versions somewhere else manually.

Thanks!

**Comment by StanczakDominik** [comment]
I think this is best solved by specifying the minimal versions for the Travis env, so it downloads those, and then running another test suite on current latest releases. I'll deal with that once I'm back.

**Comment by StanczakDominik** [comment]
It's probably better to just bump it up for now. Not a priority thing.
