### ISSUE TITLE
add axis labels to ITER parameters plot

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#428]
The ITER parameters plot [here](http://docs.plasmapy.org/en/stable/auto_examples/plot_physics.html#sphx-glr-auto-examples-plot-physics-py) could use some labels and units in said labels.

**Comment by manasbedmutha98** [comment]
I would like to take this.

**Comment by lemmatum** [comment]
go for it @manasbedmutha98

**Comment by manasbedmutha98** [comment]
I have added the labels. Should I also label the data point in the scatter plot differently?
Another thing I didn't understand is where this is being used.
https://github.com/PlasmaPy/PlasmaPy/blob/a452dadd51d612120588c6551dbca7a958b45ea5/plasmapy/examples/plot_physics.py#L12

**Comment by manasbedmutha98** [comment]
@lemmatum Should the data point in the scatter plot be labelled separately?

**Comment by lemmatum** [comment]
I think that's a question for @StanczakDominik - what are you trying to show with the scatter point in relation to the plotted line?

**Comment by StanczakDominik** [comment]
Nah, no need! We're not comparing our results to any particular ITER data, though that could be, I suppose, arranged. Also, the `Axes3D` import is indeed useless for now. We could get rid of it for now.
