### ISSUE TITLE
add dusty plasma functions

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#439]
Dusty plasmas are interesting! Apparently having large particles with charges much larger than a typical ion can change dynamics significantly! We should add some functions for handling such plasmas (and encourage astronomers to always consider dust in their line of sight).

[P. K. Shukla](https://en.wikipedia.org/wiki/Padma_Kant_Shukla) wrote a good intro on this topic called [Introduction to Dusty Plasma Physics](https://books.google.com/books/about/Introduction_to_Dusty_Plasma_Physics.html?id=WR5pAYrdQ9cC), so I'm sure we can snag most of the equations from there. I personally have this book sitting on my bookshelf and have been itching to read it.

**Comment by namurphy** [comment]
This sounds great!  I've checked out that book from the library too.  We should think about other functionality that would be applicable to the interstellar medium as well, since galaxies tend to be dusty places.  

Tangentially, there is a [newsletter on astrophysical polycyclic aromatic hydrocarbons (PAHs)](http://astropah-news.strw.leidenuniv.nl/) that I've been subscribing to for a while.

**Comment by lemmatum** [comment]
Never heard of PAHs, looks like more to learn! :stuck_out_tongue: 
On the diagnostic side of things: non-plasma dust (like ice) may be important. Also accounting for the Earth's atmosphere is critical for ground-based observations. Perhaps there are some equations/models we can include in the diagnostics module for compensating for these things.

**Comment by lemmatum** [comment]
Some equations to start with:
- [ ] Dusty plasma Debye length
- [ ] Dusty plasma frequency
- [ ] Dusty collision rate (and associated transport eqs)
- [ ] Dusty coupling parameter
- [ ] Attractive/repulsive currents relative to dust grains (this will overlap with some Langmuir probe theory since Langmuir probe tips and dust grains produce similar electrostatic effects on plasma distribution functions).

**Comment by lemmatum** [comment]
@namurphy thinking about this dust grain problem... it may be valuable to make a method that allows the creation of custom particles within the `Particle` class. Pass it a mass and an ionization and you get a dust grain!

**Comment by namurphy** [comment]
> a method that allows the creation of custom particles within the Particle class

That sounds like a good idea too!  Maybe a subclass of `Particle`?  Or allow a particle's name to be `custom` and then set stuff manually?  I should create an issue but :sleeping:

**Comment by StanczakDominik** [comment]
I like the subclass idea. CustomParticle, a subclass of Particle with basically a simpler constructor?

**Comment by lemmatum** [comment]
Just created #447 for the custom particle idea.
