### ISSUE TITLE
Should we include more general physics functionality?

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#44]
Plasma physicists occasionally need to make use of more general areas of physics, including electromagnetism, mechanics, thermodynamics, relativity, and quantum mechanics.  Many of the expressions that we occasionally use would be straightforward to include, though writing useful tests and detailed docstrings do take quite a lot of time.  We can use this issue to brainstorm and plan different functionality.  

With regards to organization, a possibility would be have files like `quantum.py`, `relativity.py`, `thermodynamics.py`, and so on.  We use electromagnetism really frequently, so we probably want to split that up into multiple files.  Some things may already be included in astropy or elsewhere.

Some ideas on things to include are:
- `Lorentz_factor`
- Relativistic momentum, rest energy, Doppler effect?
- `de_Broglie_wavelength` plus other stuff I can't remember because I avoid quantum mechanics even more than I avoid displacement current
- Bremsstrahlung
- Inductance, etc.
- Blackbody radiation (already in astropy, I think)
- Maxwellian distribution functions (plus kappa, Bose-Einstein, Fermi, other distributions?)
- Biot-Savart law to go from static currents or current density to magnetic fields, plus the forces on current carrying elements.  Something similar for electrostatics.
- Magnetic field of a dipole

Any more thoughts and ideas would be appreciated!

**Comment by StanczakDominik** [comment]
We PhysicsPy now.

Would simply trying to abstract physical formulas we actually use in writing code here into functions that can be stored in a few common files and reused be enough? Otherwise it seems to me we really do risk becoming a jack of all trades physics package.

Not that it'd be a bad thing to have one like that, but let's perhaps focus on plasmas for now. :D

**Comment by namurphy** [comment]
These are good points.  I agree that anything we include should have a reasonably strong link to plasma physics, and that we should prioritize based on how strong the connection to plasma physics is and how useful it would be.  I'll rephrase my question to: **What aspects of general physics are most essential to include in a plasma physics package?**  Having this question be included in the "Future" milestone seems more appropriate than assigning this to a release right now.

Maxwellian and non-Maxwellian distribution functions come up a lot, and quantities like the Lorentz factor and de Broglie wavelength would be useful to help us determine what regime we're working in (i.e., if relativistic or quantum effects are important).  Electromagnetism stuff is ubiquitous in plasmas, so things like magnetostatics will be helpful (but maybe for a 0.2 or 0.3 release instead of 0.1).  Functions to calculate radiative losses are also important, but often require specialized packages like ChiantiPy or pyatomdb if line emission becomes important.

PhysicsPy sounds like an interesting idea but, yes, let's focus on plasmas for now!
