### ISSUE TITLE
Create custom particle subclass

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#447]
As per discussion on #439 it'd be useful to have a method for generating custom particles as part of the `Particle` class. In particular, we want to be able to pass a mass and a charge to create custom dust grain particles.

**Comment by namurphy** [comment]
Now that #404 has been merged, one possibility for this issue would be to create a composite `Particle` from an `IonizationState` instance.  From that we would be able to get the mean and rms integer charge.  I don't think this should be the only way to create a custom `Particle`, but it would provide at least one way.
