### ISSUE TITLE
Think about Cython implementations of functions and Astropy units

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#455]
As seen here, static typing may be too strict for Cython reimplementations of parameters:
https://github.com/PlasmaPy/PlasmaPy/pull/454#issuecomment-388266228

But the question is whether we actually need to cythonise those. I think cython will be more useful for more computationally intensive stuff (solvers for simulation, etc).

**Comment by lemmatum** [comment]
My current impression is that functions in `parameters.py` will be used quite frequently to build simulations as they evaluate fundamental plasma properties. Of course we shouldn't optimize before we see a problem, so I think we shouldn't cythonize functions until they become necessary for computationally intensive calculations.

I can't think of a good way to use astropy to manage units for cythonized code (without a bunch of python overhead). So I think for the cythonized code we should have disclaimer in the docs stating that the user will have to handle unit conversions by hand when calling cython functions.

**Comment by namurphy** [comment]
I very much appreciate the hard (and occasionally frustrating!) work to get Cython working in PlasmaPy.  It will be really valuable to have that framework set up.  

> Of course we shouldn't optimize before we see a problem, so I think we shouldn't cythonize functions until they become necessary for computationally intensive calculations.

Agreed!  I'd add that for the time being, it would probably be more effective for us to increase functionality rather than optimize existing functionality.  

I'm not sure about how to do Cython stuff with `Quantity` objects either...

**Comment by namurphy** [comment]
Oh, and we should also definitely keep following the development of [Cython](http://cython.org/), [Numba](https://numba.pydata.org/), and [pythran](https://pythran.readthedocs.io/en/latest/).  In [one benchmark](https://flothesof.github.io/optimizing-python-code-numpy-cython-pythran-numba.html), Pythran ended up being the fastest.

**Comment by StanczakDominik** [comment]
As a quick update, based on my recent tinkerings with Numba:

* leave those functions as they are
* if they're needed in simulations, wrap them with numba and *drop the units* for computationally heavy parts (at least for now)
* use numba for the simulations
* numba
* numba everything

**Comment by StanczakDominik** [comment]
Closed in favor of numba. We may come back to wrapping stuff with Cython, but probably not for new functionality.
