### ISSUE TITLE
What are representative openly available sample plasma data sets?

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#458]
In order to develop the general purpose `Plasma` class factory (see https://github.com/PlasmaPy/PlasmaPy-PLEPs/pull/14 by @SolarDrew), we will need a couple of representative data sets that describe different types of plasmas.  The plan is to allows users to call `Plasma` with a filename or directory name as an argument, and `Plasma` will select and instantiate the class/subclass that corresponds to the data set.  The idea behind this comes from [SunPy's Map object](http://docs.sunpy.org/en/v0.9.0/code_ref/map.html).  

Can any of you recommend plasma data sets that can be used to help development of `Plasma`?  

The first data sets that we use should be freely and openly available so that they can be downloaded directly and reliably from the internet and used in tests and tutorials.  If would be greatly helpful if the data set had a digital object identifier (DOI), and perhaps archived on sites sites such as Zenodo.  The easiest format to begin with will probably be HDF5.  It would probably make sense to start out with fluid simulation data at first, and then try out experimental data (in HDF5 and MDSplus format) and particle-in-cell (PIC) simulations later on.  

Thanks!

**Comment by namurphy** [comment]
One possibility is the [Johns Hopkins Turbulence Database](http://turbulence.pha.jhu.edu/).

**Comment by lemmatum** [comment]
The Murillo group is working on a [database for dense plasmas](https://github.com/MurilloGroupMSU/Dense-Plasma-Properties-Database).

**Comment by lemmatum** [comment]
yt has a [datahub](https://girder.hub.yt/#collections) - there may be some plasma data of value in there.

**Comment by namurphy** [comment]
There are some openly available [example data sets](https://github.com/openPMD/openPMD-example-datasets) that use the [OpenPMD standard](https://github.com/openPMD/openPMD-standard).

@ritiek and @SolarDrew - perhaps this would be a good subclass to set up since it is very well defined and definitely needed for PlasmaPy.  The potential difficulty is that this will not be the simplest data set that we might use.

Cross-references: #167 and #459.

**Comment by SolarDrew** [comment]
All good arguments. I think perhaps the fact that it's not simple is good too, since we've found ourselves with a decent amount of extra time in this GSoC project it would be good to handle it now and leave the easier ones for later.

**Comment by ritiek** [comment]
Sounds good to me! I've been messing with those example datasets using OpenPMD standard but I am still not sure what really do we want our subclass to do with the datasets?
