### ISSUE TITLE
[Meta] Tidy up issues?

### ISSUE THREAD

**Issue by SolarDrew** [PlasmaPy/PlasmaPy#471]
Someone mentioned [in the matrix room](https://matrix.to/#/!hkWCiyhQyxiYJlUtKF:matrix.org/$1526038146917981ZrCib:matrix.org) that we have a few issues that are resolved and some stale PRs, etc. Could be worth doing a review of the current status and making sure the repo is nice and tidy by closing, tagging or reassigning anything that's got away from us.

**Comment by namurphy** [comment]
I went through and closed some issues that were discussions from several months ago.

**Comment by SolarDrew** [comment]
Perfect, thanks 😀 Since we've actually not got many PRs open at the moment I'd say that's good enough for now and we can revisit this issue if it crops up again.
