### ISSUE TITLE
Patch release workflow

### ISSUE THREAD

**Issue by SolarDrew** [PlasmaPy/PlasmaPy#474]
I'm reasonably sure that other projects maintain a separate branch for released versions so that changes which are specifically patches to that release can be pushed there rather than to master, but I'm not entirely sure on the details of this. We should figure this out (i.e. ask someone from one of those projects) and consider how to arrange/enforce this.

**Comment by dstansby** [comment]
In Matplotlib, everything is merged into the master branch, and then individual PRs can be manually backported to other branches (e.g. at the moment our master branch will turn into `3.0`, but we have a `2.2.x` branch open that we backport bug fixes to)

**Comment by StanczakDominik** [comment]
Yeah, having released 0.1.1 and seeing how easy it would be to just *git magic* everything I think it's fine to do what @dstansby said.

**Comment by StanczakDominik** [comment]
While I continue to agree with the idea, I think it's fine to delay backporting bug fixes to a later, more stable version.

**Comment by namurphy** [comment]
Closing this since we now have branches like `v0.9.*` from which we are able to perform patch releases.
