### ISSUE TITLE
Improve functionality of atomic subpackage

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#48]
Thus far in the atomic routines, there are a few ways to represent ions in the form of a string: `'p'`, `'proton'`, `'H-1+'`, `'H-1 1+'`, and `'H-1 +1'` all represent protons.  Another possibility would be to represent them as a tuple or class that contains the ion species and the ionization state: e.g., `('H-1', 1)` would also represent a proton.  Perhaps `(1, 'H-1')` could be treated as equivalent to `('H-1', 1)`, if we wanted to maximize flexibility.  This is similar to but much simpler than the `ParticleSpecies` class that was thoughtfully suggested in issue https://github.com/PlasmaPy/PlasmaPy/issues/40 for a particle stepper.  

Also, I found another issue for isotopes with plus or minus signs to indicate the charge state:
```Python
>>> charge_state('H-1+')  # this works fine
1
>>> charge_state('H-1-')  # this should be -1 but instead just makes my computer sad
ValueError: The following input does not have valid charge state information: H-1-
```
If the first syntax works, then I was thinking that the second syntax should also work, except if there is a chance of ambiguity.  An additional like in `test_atomic.py` to test that would be:
```Python
assert charge_state('H-1-') == -1
```
I'm still thinking about this, as there is a chance of ambiguity.  Another possibility would be to allow syntax like `'H-1 +'` where there is a space between the isotope and the plus sign.  

Now to see if I can figure out a checklist:
- [ ] Allow ions to be represented as a tuple like `('H-1', 1)`.
- [ ] Allow ions to be represented like `'H-1-'` and act the same way as `'H-1+'`
- [ ] Allow ions to be represented like `'H-1 +'` or `'H-1 -'`

**Comment by namurphy** [comment]
Here are some antimatter matters with inconsistent or undesirable behavior:
```Python
>>> charge_state('p-')
-1
>>> charge_state('e+')
ValueError: Invalid element or isotope information in charge_state
>>> charge_state('positron')
ValueError: Invalid element or isotope information in charge_state
>>> charge_state('antiproton')
ValueError: Invalid element or isotope information in charge_state
```

**Comment by namurphy** [comment]
We may want `charge_state` to allow electrons, even though it was intended for ions.
```Python
>>> charge_state('electron')
ValueError: Invalid element or isotope information in charge_state
>>> charge_state('e-')
ValueError: Invalid element or isotope information in charge_state
```

**Comment by namurphy** [comment]
Some more thoughts while I'm talking to myself:   :smile_cat: :speech_balloon:
- It would probably helpful to have a function called `charge` that would give the physical value of the charge for various particles.  This would be easy to add.
- I'm wondering if it would be worth considering particles like muons, pions, etc.  These do not come up that often for most plasma physicists, but may come up if people are studying cosmic rays and things like that and would also be straightforward to add.
- There are still lots of half-lives for different isotopes that are missing.

**Comment by StanczakDominik** [comment]
It would be pretty handy to have `charge_state` and even `ion_mass` to allow electrons and perhaps more exotic particles - as it stands with `Species` in #54 , I would like to permit initializing those with a string and avoid having special cases for electrons. This seems like a better place for that.

A `charge` function seems trivial to pull off, as most of the exceptions are already in `charge_state` (did anybody say, *low hanging fruit*? :smiley: )

**Comment by namurphy** [comment]
One more bug:
```Python
>>> plasmapy.constants.ion_mass('He-3 2+')
<Quantity 6.64465723e-27 kg>
>>> plasmapy.constants.ion_mass('He-4 2+')
<Quantity 6.64465723e-27 kg>
```
`'He-3 2+'` is giving the wrong mass, since it's interpreting it as an alpha particle.

**Comment by namurphy** [comment]
Of the bugs I mentioned, I believe all have been fixed except for this one:
```Python
>>> charge_state('H-1-')
```

**Comment by namurphy** [comment]
This was resolved in: https://github.com/PlasmaPy/PlasmaPy/pull/122

The original title of this issue (to allow ions to be represented as a tuple) did not get implemented since something like `('H', 1)` would leave it ambiguous about whether the `1` meant the charge state or the isotope.  The `Species` class is an improvement over this idea.
