### ISSUE TITLE
Create functionality for calculating dimensionless plasma parameters

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#49]
We will soon need functionality to calculate dimensionless plasma parameters.  Obvious ones to include are:

- [ ] `Lundquist_number` (my favorite!)
- [ ] `magnetic_Reynolds_number` (note: similar to Lundquist number)
- [x] `Reynolds_number`
- [ ] `Prandtl_number`
- [x] `plasma_beta` (went in as `beta`)
- [ ] `Mach_number`
- [x] `Coulomb_logarithm`
- [ ] `Debye_number` (this may be better here than with `Debye_length` in the plasma parameters file)

There are a bunch more in the NRL Plasma Formulary.  Please add suggestions, as I'm undoubtedly missing lots of dimensionless numbers!  I'm also not sure what the best names are for things like the ratio of the gyroradius to the system size (`relative_gyroradius`?).

This functionality will need to be added after pull request https://github.com/PlasmaPy/PlasmaPy/pull/34 on plasma parameters and issue https://github.com/PlasmaPy/PlasmaPy/issues/35 on transport coefficients.  A possible file name would be `dimensionless.py`.  The docstrings for these functions should include descriptions of the physics behind them as well as caveats and considerations in using them.

Side note: an annoyance I have with the names of most of these dimensionless parameters is that they provide little insight into the physics that is being represented by them.  That said, I guess that the standard names are the ones most people are familiar with, so it's probably still best to go with them rather than use `turbulentness_number` instead of `Reynolds_number`.  However, I still think we should change "Rayleigh-Taylor instability" to "swirly mushroom instability".

**Comment by namurphy** [comment]
```Python
def Douglas_Adams_number():
    return 42
```

**Comment by LukeRoantree4815162342** [comment]
Unless somebody has already started work on this, I'd like to contribute here. I'll update each time I add functionality and be happy to coordinate with anyone else working on this to avoid duplication.
I'll be starting with ```Mach_number``` unless someone is already working on it

**Comment by StanczakDominik** [comment]
Hey, I believe Nick has already done some work on this in #34 , #60 and possibly some others. I don't think we have the Mach number just yet, though, so if you could look over there, that'd be amazing! Thanks for the heads up!

**Comment by namurphy** [comment]
I haven't worked on `Mach_number` yet so it would be great if you could!  I'm in the middle of working on `Coulomb_logarithm` at the moment.

**Comment by lemmatum** [comment]
Some other ones:
* Knudsen number
* Degeneracy parameter (theta = thermal kinetic energy / Fermi energy)
* coupling parameter ( Gamma = Coulomb potential between two particles / thermal kinetic energy)

Also it would be cool to have a Plasma object where one defines the temperature, density etc, and then call a method on the object which then calculates all the dimensionless parameters and let's you know what regimes your plasma is in.

**Comment by StanczakDominik** [comment]
Yeah, we were thinking about having a `PlasmaBlob` object that would include those quantities without bothering with spatial data. That'd fit that.

**Comment by lemmatum** [comment]
I've sort of started this by adding a module with coupling parameter function in PR #191 . Once I finish and merge that we can add more dimensionless parameter functions.

**Comment by lemmatum** [comment]
We should be careful with which functions we put in here... For example, the quantum degeneracy parameter is often used in calculating other quantum functions, but it depends on the Fermi energy. So placing `ideal_chemical_potential` in `quantum.py` which depends on `degeneracy_parameter` in `dimensionsless.py`, which depends on `Fermi_energy` in `quantum.py` is a no go due to circular dependencies.

**Comment by diego7319** [comment]
is Prandtl_number available? If the answer is yes I would like to be sure if https://en.wikipedia.org/wiki/Prandtl_number is the correct formula so I can start to code this new function in PlasmaPy/plasmapy/formulary/dimensionless.py file

**Comment by namurphy** [comment]
Closing this since we have the bulk of these now in `plasmapy.formulary.dimensionless`.  If we decide to add more, it'd probably be most sensible to have a separate issue for each additional dimensionless parameter.
