### ISSUE TITLE
Find our missing coverage

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#495]
Based on this:

https://codecov.io/gh/PlasmaPy/PlasmaPy/src/master/plasmapy/_base_init.py

And this:

https://codecov.io/gh/PlasmaPy/PlasmaPy/src/master/plasmapy/diagnostics/langmuir.py#L1220

I don't think Codecov sees this:

https://github.com/PlasmaPy/PlasmaPy/blob/master/plasmapy/tests/coveragerc#L10

so we might need a yaml in the base directory of the repo to point Codecov to the coveragerc file somehow. We might also need to compare with this https://github.com/sunpy/sunpy/blob/master/sunpy/tests/coveragerc

**Comment by StanczakDominik** [comment]
Geez I do bad issue names in a hurry. @ritiek this is what I just realized you were tinkering with in matrix! It should solve the pragma issue.

**Comment by StanczakDominik** [comment]
Actually I'm probably wrong in that first guess. The tool we need to point at coveragerc is coveragepy itself, so we probably need to grep sunpy files for references to coveragerc and fill in any missing ones.

**Comment by ritiek** [comment]
Couldn't we just move `plasmapy/tests/coveragerc` to plasmapy's root directory? That should fix things I believe.

**Comment by StanczakDominik** [comment]
I thought there was something in setup.py test that broke when I did that... I'm not sure. I'll check later.
