### ISSUE TITLE
Add an `isotope_name` attribute on `Particle` class

### ISSUE THREAD

**Issue by ritiek** [PlasmaPy/PlasmaPy#503]
> We could definitely add an `isotope_name` attribute as well, which for isotopes in general would return something like `'iodine-131'` plus `'deuterium'` and `'tritium'` for those special cases. The `element` and `element_name` attributes just return the name of the element without respect to the isotope. I'll try to remember to create a separate issue for this.

[as mentioned here](https://github.com/PlasmaPy/PlasmaPy/pull/468/files#r189747292) by @namurphy.

**Comment by ionwyn** [comment]
I'm working on it!

**Comment by ritiek** [comment]
@ionwyn Sorry, I already made a PR for this in #510. This issue was open for a little while and no one approached, thought I'd fix it myself. I guess I should have waited a bit more. :(

**Comment by StanczakDominik** [comment]
These things inevitably happen, nobody should worry about it. Thanks for being eager to do this one, @ionwyn!

**Comment by ionwyn** [comment]
@ritiek good stuff!

@StanczakDominik interesting project here.  If I have more time I'd definitely come back to contrib to this repo for other issues!

**Comment by StanczakDominik** [comment]
Awesome, glad you like it and looking forward to it! :)
