### ISSUE TITLE
How should we organize the main subpackages?

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#51]
Before our first minor release, we'll need to think more about how to organize the subpackages that we are creating.  Right now we have the following subpackages:
- `analytic`
- `classes`
- `constants`
- `io`
- `utils`
- `visualization`
Additionally, there will probably be new subpackages for the simulation capabilities that are being implemented (https://github.com/PlasmaPy/PlasmaPy/pull/33).  Presently `io`, `utils`, and `visualization` don't have much in them but we will likely need them in the future.  

Are there ways that we should rearrange these subpackages?  An important point from Colby is to think of where it would make the most sense for a user to import certain functionality from (e.g., what subpackage names are most intuitive).  

Some thoughts that came up during today's telecon were:
- Move atomic functionality from constants into `atomic` since there is a good chance we will need a lot more atomic functionality sooner or later (e.g., if someone wants collisional cross sections for tungsten, for example).
- Remove `analytic` and put the plasma dispersion function in `math` and plasma parameters into something like `physics` or `plasma` (or whatever name suits it best or is most intuitive).

**Comment by StanczakDominik** [comment]
I have little experience in this regard, but as for the name for the subpackage storing parameters... simply `parameters`, perhaps?
