### ISSUE TITLE
PyPI distribution does not include license file

### ISSUE THREAD

**Issue by msarahan** [PlasmaPy/PlasmaPy#512]
It appears to include several older licenses in the licenses folder, but the current license is nowhere to be found.  This cause the conda recipe at https://github.com/conda-forge/staged-recipes/pull/4793/files#diff-4998bddc7ce3e9e8b1d20f70c9eb7379R56 to fail.

To remedy this, you probably need a change like this: https://github.com/google/oauth2client/pull/694/files

**Comment by ritiek** [comment]
If this is the case, do you mind making a PR to fix this in PlasmaPy? :)

**Comment by msarahan** [comment]
That won't happen on any reasonable timescale, I'm afraid.  I was helping some folks at the SciPy sprints, but I have too many other things to do in "my" time.

**Comment by ritiek** [comment]
No problem! That's perfectly fine. I'll do it myself then. :D
