### ISSUE TITLE
Reduce number of warnings issued during tests

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#515]
Right now our tests are getting a lot of warnings that we can safely ignore.  These warnings are often a `RelativityWarning` or a `CouplingWarning`, and they don't need to show up when running our test suite because we are testing values for regimes where those warnings are issued.  Example warnings are:

```
  plasmapy/physics/transport/tests/test_collisions.py::Test_Knudsen_number::()::test_symmetry
  /tmp/plasmapy-test-72pekk_1/lib/python3.6/site-packages/plasmapy/physics/transport/collisions.py:284: CouplingWarning: Coulomb logarithm is 3.4858100325145664, you might have strong coupling effects
    utils.CouplingWarning)
  /tmp/plasmapy-test-72pekk_1/lib/python3.6/site-packages/plasmapy/physics/transport/collisions.py:284: CouplingWarning: Coulomb logarithm is 3.4858100325145664, you might have strong coupling effects
    utils.CouplingWarning)

plasmapy/physics/transport/tests/test_transport.py::Test_classical_transport::()::test_resistivity_units
  /tmp/plasmapy-test-72pekk_1/lib/python3.6/site-packages/plasmapy/utils/checks.py:433: RelativityWarning: V is yielding a velocity that is 6.256% of the speed of light. Relativistic effects may be important.
    RelativityWarning)
```
It would be helpful to [suppress the warnings using a context manager](https://docs.python.org/3.7/library/warnings.html#temporarily-suppressing-warnings), for example like:

```Python
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    ...
```

The `DeprecationWarnings` are covered by a previous issue (#345).  Thanks!

**Comment by ritiek** [comment]
We could also pass additional arguments to pytest to [disable all warnings](https://stackoverflow.com/questions/40710094/how-to-suppress-py-test-internal-deprecation-warnings). Something like
```
python setup.py test --coverage -a --disable-pytest-warnings
```
should work and maybe edit our pytest config file to set it as defaults. Though, this would suppress all kinds of warnings, not sure if that's okay to us.

**Comment by namurphy** [comment]
My philosophy is that warnings should continue to be issued for problems that will need to be addressed, and not issued during the tests for things that are not problems.  For example, I would prefer to have deprecation warnings continue to be issued since we'll have to deal with them eventually since they'll eventually become exceptions.  

For my local workflow, I think I will start using the `--disable-pytest-warnings` flag when I'm working on stuff related to those warnings.  Thanks for the reminder about that!

**Comment by schambers** [comment]
Hello,

I'd like to take a stab at this. Can you assign the issue to me? Thank you!
