### ISSUE TITLE
What are our atomic data needs?

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#52]
Over the last few years, I have gradually learned that plasmas tend to contain atoms.  Hence, we will need to include some degree of atomic physics within PlasmaPy.  The atomic data needs in plasma physics are very broad.  For example, temperatures of interest range from ~10 K in molecular clouds to ~30-40 MK in solar flares.  Astronomers tend to care about the dozen or so most abundant elements in the universe, while laboratory plasma physicists care a lot about impurities leeching in from the plasma-facing wall which is often from different materials.  Dust also plays important roles in laboratory and astrophysical plasmas.

Including the ability to access all of the information any plasma physicist might ever need would be a never-ending project that would increase the size of this package by orders of magnitude.  However, the ability to access important atomic data will be extremely useful for numerous plasma physicists across sub-disciplines.  Hence we will need to do a lot of strategizing about what the most important needs are and how best to fill them.  Some questions are:
* What atomic data sets are most broadly needed by plasma physicists?
* How and to what extent should PlasmaPy fulfil atomic physics needs?
* What are the existing databases, and how would it be best to partner with them?
* Are there atomic data needs that are not being fulfilled by any databases?
* What should we include in the core package in our version 0.1 release?

A subset of the atomic data needs are:
* Ionization and recombination rates
  - Collisional ionization, photoionization, etc.
  - Radiative recombination, dielectronic recombination, etc.
* Cooling rate coefficients (e.g., for a given ion at a given temperature)
* Collisional cross sections
* Charge exchange cross sections
* Photoionization cross sections
* Everything associated with plasma spectroscopy and radiative transfer (which would be huge amounts of data and would undoubtedly be too much)
* Ability to work with both Maxwellian and non-Maxwellian distribution functions

Occasionally there are nicely behaved functions that would be easy to implement such as the radiative recombination rate.  Things like that are definitely worth including.

I am not sure what the best ways to proceed are.  Some of our many options are:
* Include the most important atomic data within the core package (or not)
* Have an affiliate package that would be responsible for atomic data needs
* Have query or bridge routines within the core package that would get the requested atomic data from websites or the local directories that contain the databases
* Or instead, not include much in the way of atomic data within PlasmaPy and instead just put up some documentation that lets users know how/where to access atomic data using other databases/Python packages.

I am imagining that this will be a long-term conversation, but I figured it would be worth bringing up sooner rather than later.  Any thoughts or ideas?

(see also https://github.com/PlasmaPy/PlasmaPy/issues/18 and https://github.com/PlasmaPy/PlasmaPy/pull/24)

**Comment by namurphy** [comment]
Existing atomic databases or spectral modeling codes used in astrophysics include:
* [Chianti](http://www.chiantidatabase.org/) and [ChiantiPy](https://github.com/chianti-atomic/ChiantiPy) - Atomic data mostly for solar spectroscopy
* [AtomDB](http://www.atomdb.org/) and [pyatomdb](https://github.com/AtomDB/pyatomdb) - Atomic data mostly for X-ray astronomy
* [Cloudy](http://www.nublado.org/) - Spectral models including photoionization in astrophysics
* [XSTAR](https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/xstar/docs/html/xstarmanual.html)
* [Dmitri Vernor's atomic data for astrophysics page](http://www.pa.uky.edu/~verner/atom.html)

Fusion databases include:
* [OPEN-ADAS](http://open.adas.ac.uk/)
  - See also [Summers & Mullane](http://aip.scitation.org/doi/abs/10.1063/1.3585817?journalCode=apc)

Other databases include:
* [NIST atomic spectra database](https://www.nist.gov/pml/atomic-spectra-database)
* [NIFS database](https://dbshino.nifs.ac.jp/)
* [General Internet Search Engine for Atomic Data](https://nucleus.iaea.org/Pages/genie.aspx)

ORNL Redbooks
* [ORNL Redbooks](http://www.cfadc.phy.ornl.gov/redbooks/redbooks.html)
  - * [Atomic Data for Fusion - Vol. 1 - Collisions of H, H_2, He, and Li atoms and ions with atoms and moleculres](http://www.iaea.org/inis/collection/NCLCollectionStore/_Public/22/011/22011031.pdf)

Potentially interesting references and websites
* Atomic and plasma-material interaction data for fusion ([Volume 2](http://www.iaea.org/inis/collection/NCLCollectionStore/_Public/23/077/23077467.pdf?r=1), [Volume 4](http://www.iaea.org/inis/collection/NCLCollectionStore/_Public/25/024/25024274.pdf?r=1))
* [Survey of Atomic and Molecular Data Needs for Fusion](http://www.iaea.org/inis/collection/NCLCollectionStore/_Public/07/264/7264096.pdf?r=1)
* [Atomic and Molecular Data Needs for Fusion](https://pdfs.semanticscholar.org/3dbb/fab5323a15a27301448e1e82e4c98fa75211.pdf)
* [Atomic Data for Fusion](https://hal.archives-ouvertes.fr/file/index/docid/249760/filename/ajp-jp4199101C122.pdf)
* [IAEA INIS Repository search page](https://inis.iaea.org/search/default.aspx)

**Comment by namurphy** [comment]
[Astroquery](http://astroquery.readthedocs.io/en/latest/) has some really helpful functionality in terms of retrieving atomic data from places like NIST.

**Comment by antoinelpp** [comment]
Concerning Cross sections (Elastic, excitation, ionization) [LXcart](https://fr.lxcat.net/home/) is a quite well known data base.

**Comment by lemmatum** [comment]
I think a good chunk of this overlaps with [SpectroscoPy](https://github.com/PlasmaPy/SpectroscoPy). In particular, [this issue](https://github.com/PlasmaPy/SpectroscoPy/issues/4) aims to create atomic state classes as an easy to use interface for fetching information from various databases. We just need to be careful about creating circular dependencies, in case SpectroscoPy will need to import plasma functions from PlasmaPy in the future.

**Comment by namurphy** [comment]
Cross-reference: #404

**Comment by namurphy** [comment]
It seems reasonable to close this issue since it's been quiet and there are no tasks associated with it.  However, if anyone finds this issue in the future, please comment if you have atomic data needs that are missing!
