### ISSUE TITLE
Create Plasma subclass for VPIC simulation results

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#534]
[VPIC](https://github.com/vpic/vpic) is a fully relativistic particle in cell (PIC) code that was released under an open source license a couple of years ago.  It has been used for some of the most intensive PIC simulations that have been performed.  We should create a `Plasma` subclass for VPIC simulation results.  

My suggestion would be to put the functionality for reading in the data into `plasmapy/io/vpic.py` and then call functions/classes from that file from the `Plasma` subclass.  

I'm also not sure where to find documentation on VPIC, especially for how ouput files are structured.

@tulasinandan mentioned that data from the largest VPIC simulations are huge, and would probably require optimized/compiled code in order to process.

**Comment by tulasinandan** [comment]
https://github.com/PrincetonUniversity/pyvpic

possible candidate.

**Comment by tulasinandan** [comment]
I'll be learning about VPIC next week and can try this package out when I start using it.
