### ISSUE TITLE
Return namedtuples in dielectric.py functions

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#539]
There are a few functions in [`plasmapy/physics/dielectric.py`](https://github.com/PlasmaPy/PlasmaPy/blob/1511167bfb7631b0b54d1e4919d0adaf001c59aa/plasmapy/physics/dielectric.py) that return three values, e.g.
```Python
def cold_plasma_permittivity_SDP(B, species, n, omega):
    ...
    return S, D, P
```
It would probably be helpful if we could return these as `collections.namedtuple` objects (or perhaps a new class) since that would group the values together in a convenient object.  If it is returned as a `namedtuple`, then it should preserve existing behavior when doing: 
```Python
>>> S, D, P = cold_plasma_permittivity_SDP(B, species, n, omega)
```
Thanks!
-Nick

**Comment by jhillairet** [comment]
I've never used `namedtuple`, so I wonder if this is compatible with Numpy array workflow like the following?

```
ns = np.logspace(17, 19, 50)/u.m**3 
B0 = 4*u.T
omega_RF = 2*pi*50e6*(u.rad/u.s)

S, D, P = cold_plasma_permittivity_SDP(B=B0, species=['e', 'D+'], n=[ns, ns], omega=omega_RF)
```

**Comment by StanczakDominik** [comment]
@jhillairet I'm like 90% sure it's going to work, I don't see why it wouldn't. `namedtuple` only extends the tuple. I'll add your example to tests later today and we'll see for sure :)

**Comment by namurphy** [comment]
Tuple unpacking works for `namedtuple` objects too, so I don't foresee any problems.  Here's a test I just ran:
```Python
>>> from collections import *
>>> NT = namedtuple("NT", ["a", "b", "c"])
>>> nt = NT(1, 2, 3)
>>> a, b, c = nt
>>> a
1
>>> b
2
>>> c
3
```

**Comment by StanczakDominik** [comment]
Yeah, but I think the special use case here was that `ns` was passed as a numpy array. That doesn't seem to bother `namedtuple` thougs, as https://github.com/PlasmaPy/PlasmaPy/pull/540/commits/afa8919a14e944db01cdc791536febd21b55136d will probably pass (it did so on my machine).
