### ISSUE TITLE
Invalid type annotation in physics/dielectric.py  omega: u.rad / u.s

### ISSUE THREAD

**Issue by BTaskaya** [PlasmaPy/PlasmaPy#546]
https://github.com/PlasmaPy/PlasmaPy/blob/c03024e2dee3827be6ad8180339265b1f33049a5/plasmapy/physics/dielectric.py#L121

In this line mypy gives error because `u.rad / u.s` is not a valid type annotation.
```
plasmapy/physics/dielectric.py:121: error: invalid type comment or annotation
```

**Comment by namurphy** [comment]
One difficulty here that I don't know how to address is that the `@check_quantity` decorator that operates on `cold_plasma_permittivity_LRP` uses the `astropy.units.rad / astropy.units.s` annotation to check the units of `omega`.  Unfortunately, this usage is inconsistent with how [mypy](http://mypy-lang.org/) uses type hint annotations for static type checking (which would want an annotation of `astropy.units.Quantity`).

I am definitely open to ideas on how to address this.  I've been wondering if `@check_quantity` would be able to change the annotations from units to `astropy.units.Quantity` in a way that would be compatible with what mypy needs to do static type checking, or if there is a way to do an upstream fix in Astropy.

Thank you for bringing this to our attention!

Cross-reference: #268

**Comment by StanczakDominik** [comment]
Of course, rad/s is not a type annotation. It doesn't aim to be - it's supposed to document the units for the calculation and help our decorators automate conversions. Sure, this breaks mypy - but that's not much of a problem here.

I would vote to close this issue and possibly look into whether astropy wants to be mypy compatible.
