### ISSUE TITLE
Use Optional explicitly for type hints when arguments default to None

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#553]
I just looked up [PEP 484 -- Type Hints](https://www.python.org/dev/peps/pep-0484) again in response to a comment from @StanczakDominik in #385.  PEP 484 now says:

> A past version of this PEP allowed type checkers to assume an optional type when the default value is None, as in this code:
> ```Python
> def handle_employee(e: Employee = None): ...
> ```
> This would have been treated as equivalent to:
> ```Python
> def handle_employee(e: Optional[Employee] = None) -> None: ...
> ```
> This is no longer the recommended behavior. Type checkers should move towards requiring the optional type to be made explicit.

There are a lot of places in PlasmaPy where we use the first format above (from when that format was recommended), but explicit is better than implicit, so we should change everything to the second format.

It would probably also be good to consistently use `from` imports for the `typing` package, like `from typing import Optional, Dict, List`. Using `typing.Optional` rather than just `Optional` in annotations really reduces readability, especially if we have multiple type hint annotations in the same function/method call.  All of this would be good to add to the code guide in our development guide too.

Thanks!
-Nick

**Comment by lgoenner** [comment]
I'd like to work on this!

**Comment by StanczakDominik** [comment]
Sure, go right ahead!
