### ISSUE TITLE
Improve discussion of physical concepts in plasma parameter function docstrings

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#56]
The functions to calculate plasma parameters in `physics/parameters.py` should have a discussion of physical concepts in their docstrings.  Some of the functions sort of do, while others like `ion_inertial_length` presently have little more than the formula.  These docstrings should be improved to have a concise and easily understandable discussion of the physics involved.  The docstrings should also be consistent with each other, using the numpydoc style.  

These modifications would be great for new contributors who would be making their first pull request (see https://github.com/PlasmaPy/PlasmaPy/blob/master/CONTRIBUTE.md).  If you'd like to work on a particular function, please comment below to avoid duplication of effort.  The original pull request (https://github.com/PlasmaPy/PlasmaPy/pull/34) has some brainstorming on possible ways to structure the docstrings.  

Thank you!

**Comment by namurphy** [comment]
@nickmmain - That would be great!  The "notes" section would probably be the best place, and a length/complexity similar to Debye length and number would be good.  Ideally we like to have documentation that would be understandable by someone who is taking their first course on plasma physics, but would still be useful to experienced plasma physicists.  Thank you!

**Comment by StanczakDominik** [comment]
Hey @nickmmain, how's this going? Any progress?

**Comment by namurphy** [comment]
This issue has been superseded by #935.
