### ISSUE TITLE
Test instructions on how to contribute by making a small pull request

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#57]
As suggested in https://github.com/PlasmaPy/PlasmaPy/pull/43, we should add `.swp` files to `.gitignore`.  These are files created when using the vim text editor that shouldn't be part of the repository.  This is a great, straightforward issue for a first time contributor to work on.

**Comment by namurphy** [comment]
An additional motivation in raising this as an issue is to see if anyone who has not made a pull request before would simultaneously check to make sure that our [instructions on how to contribute](https://github.com/PlasmaPy/PlasmaPy/blob/master/CONTRIBUTE.md) are helpful and don't have any mistakes in them.  That would be a great help!

**Comment by jhillairet** [comment]
One additional comment could be made on the documentation, on a aspect which I find is poorly documented elsewhere: how do deal with and what should we do of the specific branches which have been created on our own fork after successful PR?

**Comment by StanczakDominik** [comment]
I think there's no harm in either removing them or keeping them. If you like to have your repos tiny, remove away :)
