### ISSUE TITLE
Remove skeleton subpackages

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#575]
At the telecon today we decided it'd make sense to remove our yet-unused subpackages:
* `plasmapy.io`
* `plasmapy.visualization`
* `plasmapy.constants`
    * this one will probably require replacing a bunch of imports with straight up `astropy.constants.si` style imports in places.

I'll probably get that done around Sunday, but if anyone wants to do it first, go for it! :smiley:

**Comment by EternalLearner42** [comment]
My greetings. Given the length of time that has passed, I assume this is already done? Or is it still ripe for the picking? I happen to be looking for a good contribution to make
