### ISSUE TITLE
Expand documentation for ionization state classes

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#577]
The `IonizationState` and `IonizationStates` classes were created in #404 to represent what fraction of an element's population was in what ionization level.  The docstrings for these classes are not yet sufficient, and in particular do not talk about the effects of the different dunder methods, like `__iter__`/`__next__`, `__getitem__`, and `__setitem__`.  Additionally, narrative documentation has not been written for any of this.  The remaining steps will be to:

 - [ ] Expand docstring of `IonizationState` 
 - [ ] Write narrative documentation for `IonizationState`
 - [ ] Expand docstring of `IonizationStates`
 - [ ] Write narrative documentation for `IonizationStates`

**Comment by StanczakDominik** [comment]
Let's revisit this for 0.3.0 :smiley:

**Comment by StanczakDominik** [comment]
@namurphy I think this just about got done a while ago, no? :)
