### ISSUE TITLE
Change State namedtuple to a class

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#580]
`State` is a `namedtuple` in `plasmapy/particles/ionization_state.py` which contains information on a particular neutral or ion.  `State` instances are created, for example, when trying to get an item or iterating over an `IonizationState` instance.

Since it is a `namedtuple`, it does not contain checks that the ionic fraction is between 0 and 1, the integer charge is valid, the number density is positive and has the right units, and so on.  It would be worthwhile to change it into a class so that it can be more flexible, though it should be simpler than the `IonizationState` class.  Some of the arguments to `State` contain redundant information, so we could reduce the number of arguments too, and then change the calls that show up in `IonizationState` and `IonizationStates`.

Cross-reference: #404

**Comment by Jac0bDeal** [comment]
Hello, I'd like to get involved in this project and think I might take a crack at this issue :)

**Comment by StanczakDominik** [comment]
Awesome, go right ahead - I'm looking forward to reviewing that! :)
