### ISSUE TITLE
Discuss when to merge, squash, or rebase pull requests in development guide

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#582]
Most of our pull requests have been incorporated into PlasmaPy via merge commits.  There has been a lot of discussion over the last few months on when it is appropriate to merge, squash, or rebase.  We should describe our process for deciding between these different possibilities in the development guide.  

This would definitely be worthwhile to bring up at a community meeting to get more people to bring up their priorities.  In the meantime, please feel free to comment on this issue with your opinions.

It would be good to include a one-sentence definition of each of the three types of merging, and then summarize the advantages and disadvantages (or link to a resources that do this).

Some of the considerations are:

 * Merges
   * Advantages
     - Keep track of full development history
     - Credit for different commits is retained
     - Detailed commit messages can be written for particular segments of code
   * Disadvantages
     - Messier commit log (e.g., lots PEP 8 fix commits)
     - Difficult to select which commits go into, e.g., a bug fix release
 * Squashes
   * Advantages
     - Cleaner development history
     - Easier to select which changes go into different branches
   * Disadvantages
     - Sometimes credit for contributions is not given to the original author by GitHub (so for multi-person PRs, we should state co-authors) 
     - Can end up with a long commit log in a single fix
 * Rebases
   * Advantages
     - Can clean up development history while maintaining most important commits
     - Can create optimal compromise between squashing vs regular merging
   * Disadvantages
     - Can be horrible to go through
     - Git expertise is required
     - Lose the original development path

**Comment by namurphy** [comment]
My own preference would be to reserve squashes for:
 - when the development history is messy;
 - the changes are minor enough that it would be appropriate to include them in a single commit;
 - doing a rebase would be horrible; or
 - when there are plans to pull the changes into a bug fix branch.

I like the rebase option for experienced developers so that commit messages can focus on a particular section of code or one specific change.  My opinions on this are changing, so I'll probably have something different to say a month from now. :smile_cat:

**Comment by ritiek** [comment]
Those are some very good points but my personal opinion would be to not include this stuff in the *how to contribute* docs. This would probably introduce additional confusion to developers new to Git and GitHub going through the contribution process. Experience developers usually plan their commits ahead, so reading through this would be unncessary waste of time for them. And maintainers can always guide new contributors when an actual PR has been made in real-time. :)

However, another section in the docs specially devoted to *how we merge pull requests* would be a pretty nice place for this to make in.

**Comment by namurphy** [comment]
Closing since we've converged on almost always squash merging.
