### ISSUE TITLE
How do we incorporate data science capabilities into PlasmaPy?

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#583]
Machine learning and data science provide ways to find patterns that depend on a lot of variables that have lots of nonlinear interactions with each other (to paraphrase a quote from a panel at the APS DPP mini-conference on data science and machine learning that I'm sitting in right now).  It's going to be pretty vital that we include machine learning and data science capabilities into PlasmaPy.  I do not know enough yet about how to best approach this problem.  What capabilities should we include, and how do we facilitate their use?  

Another question that came up is: How do we build in physical constraints like conservation on energy into, e.g., neural networks?

A review article that looks really relevant is: [Deep learning: A guide for practitioners in the physical sciences](https://doi.org/10.1063/1.5020791) by Brian Spears et al., Physics of Plasmas, 25, 080901 (2018), doi: 10.1063/1.5020791

**Comment by StanczakDominik** [comment]
I have finally gotten through that article and wow, that was neat. :ok_hand:

Still, this will probably have to come after some developments for the plasma class - I'm not aware of any generic run-of-the-mill universal problems that are data independent.

**Comment by namurphy** [comment]
> this will probably have to come after some developments for the plasma class

Agreed.  This will definitely a much longer term discussion.  In any case, it'd be good to keep data science in the back of our minds while we're working on `Plasma` to help us plan how we develop it.  For me, at the very least, this will require taking some time to learn more about it.

**Comment by lemmatum** [comment]
As mentioned in the chat room, I think image processing and computer vision as applied to diagnostic images could be major areas for applying data science techniques in PlasmaPy.

From what I've seen, most people rely on feature engineering or manually/interactively selecting the features or regions of interest. Which means lack of reproducibility. If we can use openCV or scikit-image to do edge, blob, shape detection of shocks, image windows, spatial calibration grids, etc. I think it would be an incredibly valuable tool to the community. And I know that I would use it frequently in my own work (and therefore be motivated to code some of this stuff).

And of course, deep learning excels in image processing/classification applications.

**Comment by tulasinandan** [comment]
Interestingly one of the students who will work on PlasmaPy, Samuel Fordin, is working on Machine learning applications to data from Wind spacecraft. He is trying to identify whistler waves in wind data. 

One generic application is to apply machine learning to "clean" data sets by identifying obvious bad data points. I am discussing this with some computer scientists in my new university and will start working with them as soon as I join there in January. We will contribute as much of the functionality to plasmapy as possible.

Identification of correlations between various quantities in multi-variate data sets would be another one. I am working on a project myself in which I am trying to find correlations between two physical terms using wind data. I keep wishing that someone with machine learning capabilities could tell me a better way of studying that problem.

**Comment by tulasinandan** [comment]
Another popular and obvious application is the prediction of dst index. 
https://en.wikipedia.org/wiki/Disturbance_storm_time_index

Apparently AGU has a session on data science this year. I'll not be able to go but whoever among us ends up going should make a trip to that session.

**Comment by samfordin** [comment]
I'm a new contributor whom Tulasi mentioned in his previous post, studying machine learning with the intent of identifying whistler waves in Wind data. Currently, I'm in the early stages; my knowledge is mostly limited to some intermediate coursework. With that said, I will be getting a lot of hands-on experience with time-series analysis over the next several months. I'll keep this project in mind moving forward.
