### ISSUE TITLE
Broken link to Coulomb Logarithms

### ISSUE THREAD

**Issue by ehsteve** [PlasmaPy/PlasmaPy#584]
The `Collisions` documentation page under the `Coulomb Logarithms` heading refers to documentation on `Coulomb Logarithms` which does not seem to exist. Perhaps it is supposed to link to the [function definition](http://docs.plasmapy.org/en/stable/api/plasmapy.physics.transport.collisions.Coulomb_logarithm.html)?

**Comment by StanczakDominik** [comment]
Hi, thanks for pointing this out! It is indeed supposed to link to the location you linked. Got a fix ready :)
