### ISSUE TITLE
Add more comprehensive testing

### ISSUE THREAD

**Issue by bsipocz** [PlasmaPy/PlasmaPy#589]
Would you consider adding more jobs to the test matrices? E.g. test against more numpy versions you support, or astropy versions.

Also, preferably also against the dev versions of these to issues like #587 would surface much earlier, still in the development cycle.

**Comment by namurphy** [comment]
You're right, that definitely would have helped with catching things like #587 much earlier.  We did try testing against astropy-dev a while ago in #172 and #264 but ran into some problems and weren't able to figure it out.  Thanks!
