### ISSUE TITLE
Create prototype for calling Julia from PlasmaPy

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#595]
Python is an interpreted language and therefore does not achieve the high performance of a compiled language.  However, we will run into many applications of PlasmaPy where performance is critical.  The most commonly used methods are to call C (or sometimes Fortran) code, use a just-in-time compiler with [Numba](http://numba.pydata.org/), or generate C code from [Cython](https://cython.org/).  We already have some Cython code in PlasmaPy (#222, #223), though we found Cython to be difficult to work with (as we had trouble including it in 0.1.0; see #418).  

An alternative that we have not yet investigated is using [Julia](https://julialang.org/) for performance-critical parts of PlasmaPy.  Julia can be called from Python using [pyjulia](https://github.com/JuliaPy/pyjulia).  This issue is to try out using Julia 1.0 for some functionality within PlasmaPy (e.g., a function call).  That way, we can evaluate the pros and cons of Julia and Cython and if we would prefer going with one of these over the other.

I've noticed that it has been taking some time for Julia packages to be updated to be compatible with Julia 1.0, which was just released a few months ago with some backward incompatible changes.  My suspicion is that it would be better to wait a little while longer before trying this, so I'll set this to "on hold" for the time being, especially since we will need to prioritize our 0.2.0 release.  But, if anyone wants to work on this in the meantime, you're welcome to!

**Comment by StanczakDominik** [comment]
I was at a Julia tutorial on Thursday (hypeee!), this seems to be as simple as using https://github.com/JuliaPy/PyCall.jl ...

**Comment by StanczakDominik** [comment]
I tried my hand at running [this StackOverflow example](https://stackoverflow.com/questions/49750067/running-julia-jl-file-in-python). If this is the state of the art, then support for running Julia from Python seems a bit clunky right now. With this julia file:
```julia
for i in 1:10
    println(i)
end
1+2
```

I got the following output:

```ipython
(base) 11:31:00 dominik: ~ $ ipython
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.
i
[ins] In [1]: import julia                                                                                                  

[ins] In [2]: jul = julia.Julia()                                                                                           
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
 ...
RuntimeError: It seems your Julia and PyJulia setup are not supported.

Julia executable:
    julia
Python interpreter and libpython used by PyCall.jl:
    /usr/bin/python3
    /usr/lib/libpython3.7m.so.1.0
Python interpreter used to import PyJulia and its libpython.
    /progs/miniconda3/bin/python
    /progs/miniconda3/lib/libpython3.7m.so.1.0

Your Python interpreter "/progs/miniconda3/bin/python"
is statically linked to libpython.  Currently, PyJulia does not fully
support such Python interpreter.

The easiest workaround is to pass `compiled_modules=False` to `Julia`
constructor.  To do so, first *reboot* your Python REPL (if this happened
inside an interactive session) and then evaluate:

    >>> from julia.api import Julia
    >>> jl = Julia(compiled_modules=False)

Another workaround is to run your Python script with `python-jl`
command bundled in PyJulia.  You can simply do:

    $ python-jl PATH/TO/YOUR/SCRIPT.py

See `python-jl --help` for more information.

For more information, see:

    https://pyjulia.readthedocs.io/en/latest/troubleshooting.html


[ins] In [3]:                                                                                                               
Do you really want to exit ([y]/n)? 
(base) 11:31:25 dominik: ~ $ ipython
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

[ins] In [1]: import julia                                                                                                  

[ins] In [2]: jul = julia.Julia(compiled_modules=False)                                                                     

[ins] In [3]: x = jul.include("test.jl")                                                                                    
1
2
3
4
5
6
7
8
9
10

[ins] In [4]: x                                                                                                             
Out[5]: 3

```
Two things to note:

1. I think this may play badly with anaconda environments; I had to enable the option `compiled_modules: {True, False, 'yes', 'no'} - Enable or disable incremental precompilation of modules.`, which may (or may not) cause performance drops.

**Comment by namurphy** [comment]
Tentatively closing this since it's been seeming like we're going in the direction of Numba (more likely) and/or Cython (less likely).  We could re-open this in the future if it becomes important for `plasmapy.simulation`.
