### ISSUE TITLE
Pytest deprecation of "message" parameter to raises

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#601]
Followup to #599. https://github.com/pytest-dev/pytest/issues/3974 is a thing, thus we need to do something like https://github.com/PlasmaPy/PlasmaPy/pull/600/commits/e9cd7c593ed1e766993d3daaf7994e046a768242 except without blowing all of pytest-helpers up.

**Comment by namurphy** [comment]
I believe the way we used the `message` keyword was consistent with the intended use and should not be replaced with the `match` keyword, so I think we need to do something like [this](https://github.com/pytest-dev/pytest/issues/3974#issuecomment-453994294):
```
with pytest.raises(SomeException):
    something_that_raises_that_exception()
    pytest.fail("SomeException should have been raised")
```

**Comment by namurphy** [comment]
Correction: We're using both usages.  I'm attempting to fix them now.
