### ISSUE TITLE
Packages depending on PlasmaPy can use interfaces to protect against our unstable API

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#609]
PlasmaPy is still in the early stages of development, and we are still making changes to our application programming interface (API).  Despite plasma physicists' interest in instabilities, an unstable API can cause headaches for early adopters who want to write packages that depend on PlasmaPy.  A useful strategy for packages depending on PlasmaPy would be to program to interfaces (as suggested by Robert Martin in _Clean Architecture_).  

Suppose `package` needs to calculate plasma parameters.  The most commonly used strategy would be to import `plasmapy.physics` everywhere it is needed in `package`.  However, if the API of `plasmapy.physics` changes, then that would mean that the developers of `package` would have to change calls to `plasmapy.physics` functions throughout the code.  This would be a headache.

An alternative strategy would be for `package` to have a subpackage called `plasma_parameters`.  In the beginning, `package.plasma_parameters` could import `plasmapy.physics` functions directly into that namespace.  The rest of `package` could then import the plasma parameter functions from `package.plasma_parameters`.

Now suppose that the API to `plasmapy.physics.func` changes so that `old_func(a, b)` now needs be called as `new_func(b, a)`.  Without an interface approach, all calls to `old_func` throughout the code would need to be changed to `new_func`.  With the interface approach, the call would only need to be changed in one place, for example by creating a new function in `package.plasma_parameters`:
```Python
from plasmapy.physics import new_func
def old_func(a, b):
    return new_func(b, a)
```
This strategy helps make the code more maintainable.  The resources I've read talk about how this strategy can really help for situations where, e.g., we need to change the database schema but don't want to have the change the high level structure of the code.

**Comment by namurphy** [comment]
As another example, suppose we wanted to change our units package from `astropy.units` to `pint`.  In order to do this now, we would have to change like 80% of PlasmaPy.  If we programmed from an interface, the only changes that we would need to make would be the interface.

**Comment by StanczakDominik** [comment]
I feel queasy about stacking higher and higher levels of supportive infrastructure while the actual functionality is not even properly designed yet.

I also think writing an interface to unit packages is a bit too closely related to writing another unit package...

**Comment by namurphy** [comment]
To follow up on this, my thinking was that this strategy would be appropriate for situations where the design is mostly in place, but for which the API is still being refined.  What you said definitely makes sense for the `Plasma` class at present, but I was thinking more of things like `transport` in its current state.  We know we're going to keep transport coefficient functionality, but we also know that the API will evolve and improve.  In that situation, an interface would be a wiser decision.  

With respect to writing an interface to `astropy.units`, that would prepare us for the (increasingly unlikely) situation where the different unit package developers come together to create a unified units package.  In that case, we could maintain the `astropy.units` API that we've been using within the code, but allow us the possibility of having a different units package underneath.  This is purely a hypothetical example...I am by no means suggesting that we do this, however!

This issue doesn't have any actual tasks associated with it, and I prefer having the number of open issues be a prime number, so I'll go ahead and close it.
