### ISSUE TITLE
Create a CodeMeta instance file

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#622]
The [CodeMeta Project](https://codemeta.github.io/) is an effort to standardize metadata for different software projects that I learned about recently from the head librarian where I work.  As I understand it, we create a JSON file in our top-level directory using the tools provided on the website.  This file will contain the metadata describing PlasmaPy.  The CodeMeta standard is changing and our metadata will keep changing too, so we'll probably need to include updates to this in our release guide.

I'll tentatively assign myself to this since I can ask the librarian here for help, but the resulting file should be double checked by several of us.  We can schedule this for 0.2 since it shouldn't be too much extra effort and metadata is important.

**Comment by owlice** [comment]
This example might help get you started: https://ascl.net/1503.001/codemeta.json

You can add "/codemeta.json" to any ASCL entry URL. This is still in beta but has already been through several rounds of vetting; we'll roll it out later this year.

**Comment by StanczakDominik** [comment]
Given the existence and proximity of deadlines, I think this can be safely bumped up to 0.3.0.
