### ISSUE TITLE
Put examples on top of documentation front page

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#630]
From the feedback box, by @jhillairet who also gets the award for first feedback box usage - thanks! I'm also assuming that by putting in your contact details you're fine with tagging you here. If not, please say so and I'll refrain from doing that in the future.

> Clearly describe what kind of calculations/tools the package allow.. This is currently not clear from documentation, unless go through the documentation and associated examples. Why not a gallery of examples, like for Matplotlib.

The way matplotlib does this is that when you go to https://matplotlib.org/ , you immediately see examples:

![image](https://user-images.githubusercontent.com/11289391/58687831-12bf6b80-8383-11e9-910d-331a22d70bb6.png)

Compared to this on http://docs.plasmapy.org/en/stable/ :

![image](https://user-images.githubusercontent.com/11289391/58688815-c3c70580-8385-11e9-90c3-e84643826a6a.png)

It is, indeed, pretty bad and we should put the examples front and center. This would probably be the core of this issue.

That, of course, will require us to have better, more interesting examples - but for now, let's make do with what we have.

**Comment by jhillairet** [comment]
I agree. The point is, assuming you want to talk about PlasmaPy to colleagues that are not aware of it, what would you promote? How PlasmaPy can be used on a daily use? How does it facilitate plasma scientist work? 

For example, when one want to plot plasma dielectric properties, instead of rebuilding the wheel, PlasmaPy offers (validated/tested) functions for that.

**Comment by singha95** [comment]
@StanczakDominik Hi. I am new and was hoping to work on this issue. So far I have used some of the image from the example section. 
![Capture](https://user-images.githubusercontent.com/22158514/60402877-64663c00-9b63-11e9-836c-ad69ceb0d9f0.PNG)

**Comment by StanczakDominik** [comment]
Oh hey, that looks great! Please submit that as a PR :)
