### ISSUE TITLE
Compile use cases for plasma research and educational activities

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#632]
As we are updating our development roadmap, creating software requirements specifications, and formalizing our software architecture, it would be really helpful to be able to draw upon future potential use cases from across the plasma physics community.  These use cases could include analyzing experiments, performing data science activities, introducing plasma physics concepts to students, first research projects by students, studying the same physics process in both experiment and in situ space observations, theoretical analyses, and so on.  The use cases would be particularly helpful if they were provided by plasma physicists across disciplines, and we could also construct them by looking through research papers and figuring out what steps were needed in order to accomplish the tasks at hand.  

I have already begun constructing use cases for plasma simulation while working on a PLEP on next generation plasma simulation capabilities in https://github.com/PlasmaPy/PlasmaPy-PLEPs/pull/24.

Here are some resources that provide advice on how to write use cases for software engineering:
 - [Five tips for writing use cases](http://casecomplete.com/lessons/writing-use-cases)
 - [UML Use Case Diagram Tutorial](https://www.lucidchart.com/pages/uml-use-case-diagram)
 - [Use cases: what every project manager should know](https://www.pmi.org/learning/library/use-cases-project-manager-know-8262)
 - [Use case examples](http://www.gatherspace.com/use-case-examples/)

**Comment by namurphy** [comment]
One extremely helpful way for plasma physicists to make a good first contribution to PlasmaPy would be by adding use cases from your own research as comments below.  Don't worry about making them perfect, since we will probably be refining use cases as we create software requirements specifications and get feedback from members of the community.  

If you do provide a use case that we end up using in this issue, then we may incorporate it into one or more versioned documents to be uploaded to the PlasmaPy Community on Zenodo under a Creative Commons Attribution 4.0 International license, with you as one of the authors (if your name and/or ORCID is available).

**Comment by jhillairet** [comment]
My use case consists in using plasma parameters (plasma and cyclotron frequencies) and derived cold plasma dielectric parameters for cold plasma wave dispersion relation calculations.

**Comment by bbussell** [comment]
My use cases are primarily focused on the analysis of industrial plasma's for thin film and surface modification applications. Apologies in advance if these aren't immediately relevant

Read in experimental optical emission spectroscopy atomic spectra for a plasma
Measure peak intensities of transition lines 
Use intensity-ratio method to calculate excitation temperature of plasma 
Compare with Langmuir probe measurements of electron temperature (if present)
Verify if plasma is in local thermodynamic equilibrium and has Boltzmann distribution
