### ISSUE TITLE
Implement decorator adding to_radians

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#645]
Presently many of the functions in `plasmapy.physics` return angular frequencies with units of radians per second.  
```Python
>>> from plasmapy.physics import plasma_frequency
>>> from astropy import units as u
>>> plasma_frequency(1e19 * u.m ** -3, 'e-')
<Quantity 1.78398636e+11 rad / s>
```
Radians are dimensionless (#29); radians are units like meters per meter.  By default, `astropy.units` does not treat radians as dimensionless (though you can use the `u.dimensionless_angles()` equivalency).  Many plasma physics formulae treat angular frequencies as having units of inverse seconds, such as the electron inertial length which is dₑ = c / ωₚₑ.  If we return frequencies in units of radians per second then the problem is it's often necessary to include a new unit conversion with that equivalency enabled.
```Python
>>> (c / omega_pe).to(u.s ** -1, equivalencies = u.dimensionless_angles()).
```
After using `plasmapy.physics` to calculate various things, having to deal with the extra conversion factor has been a bit cumbersome.  I propose that we change functions that calculate angular frequencies to be in units of `1 / s` instead of `rad / s`.  The downside is that there may be confusion between regular frequencies and angular frequencies since there's a factor of 2π difference.  However, angular frequencies come up much more often than regular frequencies in plasma physics, in my experience.  

If we make this change, we should note this convention clearly in the documentation and update our development guide.

#29

**Comment by rocco8773** [comment]
@namurphy I ran into this issue not too long ago.  My two cents...`1/s` and `rad/s` are too easily confused, especially when something is returned as `1/s`.  You're relying on the user to search for the correct answer, and that's assuming they are aware that this might be an issue.  The solution I came up with, something like `plasma_frequency()` would, by default, return `rad/s` second.   Then it is clear that the value is an angular frequency.  However, I provide a keyword, like `to_Hz=True`, that would apply the `1/2(pi)` and unit conversion to `1/s`.  Then the ambiguity between the two is mitigated.

**Comment by StanczakDominik** [comment]
I agree with @rocco8773, I had the same kind of solution in mind. With the ecosystem of unit packages engulfed bigger turmoil than the Galactic Republic, I don't think we have the right to introduce more confusion, as in, `plasmapy-flavored astropy.units`.

Do you think a decorator would be a good choice here? ;)

**Comment by rocco8773** [comment]
Especially since the definitions for plasma frequency, gyrofrequency, etc. are defined as `rad/s`.

@StanczakDominik if there's enough use cases, then I don't see why not make a decorator.

**Comment by StanczakDominik** [comment]
okay, let's go with the simple decorator wrapper solution :) i'll try to handle this next week
