### ISSUE TITLE
TypeError while running `python setup.py test`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#672]
I've been trying to run `python setup.py test` to run our tests, and I've been getting a `TypeError` that `plasmapy.atomic.particle_input` is thought to be a test during test selection, and the exception says that it isn't a test, but in actuality it shouldn't be selected as a test.  I tried it on a Mac and in CentOS.  I'm not sure why this is happening, since I'm not so familiar with what's happening behind `python setup.py test`.  

```
TypeError: calling <function particle_input at 0x7fea16937b70> returned <function particle_input.<locals>.decorator at 0x7fea27c12268>, not a test
```
Here's the full output and traceback:
```
running test
running egg_info
writing plasmapy.egg-info/PKG-INFO
writing dependency_links to plasmapy.egg-info/dependency_links.txt
writing requirements to plasmapy.egg-info/requires.txt
writing top-level names to plasmapy.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'plasmapy.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    setup(extras_require=extras, use_scm_version=True)
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/site-packages/setuptools/command/test.py", line 250, in run_tests
    exit=False,
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/unittest/loader.py", line 347, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/unittest/loader.py", line 404, in _find_tests
    full_path, pattern, namespace)
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/unittest/loader.py", line 481, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/media/Scratch/namurphy/envs/pldev/lib/python3.7/unittest/loader.py", line 212, in loadTestsFromName
    (obj, test))
TypeError: calling <function particle_input at 0x7fea16937b70> returned <function particle_input.<locals>.decorator at 0x7fea27c12268>, not a test
```

**Comment by StanczakDominik** [comment]
Removing `astropy_helpers` took `python setup.py test` with it, I've been following a discussion on the AH removal APE - people are concerned about it as well. For now, since we aren't compiling anything... just use `pytest` and its multitude of flags?

**Comment by StanczakDominik** [comment]
There's also `tox` for full, isolated environment tests. It's a bit harder to run a test for a single piece of functionality with that, though.

**Comment by namurphy** [comment]
> Removing `astropy_helpers` took `python setup.py test` with it, I've been following a discussion on the AH removal APE - people are concerned about it as well. For now, since we aren't compiling anything... just use `pytest` and its multitude of flags?

Good to know that there's discussion happening on this already!  And yep, I'll use pytest with abundant flags for the time being.

**Comment by diego7319** [comment]
Getting this on windows as well
`  File "setup.py", line 30, in <module>                                                                                     setup(extras_require=extras, use_scm_version=True)                                                                    File "d:\soft\python\lib\site-packages\setuptools\__init__.py", line 145, in setup                                        return distutils.core.setup(**attrs)                                                                                  File "d:\soft\python\lib\distutils\core.py", line 148, in setup                                                           dist.run_commands()                                                                                                   File "d:\soft\python\lib\distutils\dist.py", line 955, in run_commands                                                    self.run_command(cmd)                                                                                                 File "d:\soft\python\lib\distutils\dist.py", line 974, in run_command                                                     cmd_obj.run()                                                                                                         File "d:\soft\python\lib\site-packages\setuptools\command\test.py", line 229, in run                                      self.run_tests()                                                                                                      File "d:\soft\python\lib\site-packages\setuptools\command\test.py", line 251, in run_tests                                exit=False,                                                                                                           File "d:\soft\python\lib\unittest\main.py", line 93, in __init__                                                          self.parseArgs(argv)                                                                                                  File "d:\soft\python\lib\unittest\main.py", line 117, in parseArgs                                                        self._do_discovery(argv[2:])                                                                                          File "d:\soft\python\lib\unittest\main.py", line 228, in _do_discovery                                                    self.test = loader.discover(self.start, self.pattern, self.top)                                                       File "d:\soft\python\lib\unittest\loader.py", line 341, in discover                                                       tests = list(self._find_tests(start_dir, pattern))                                                                    File "d:\soft\python\lib\unittest\loader.py", line 398, in _find_tests                                                    full_path, pattern, namespace)                                                                                        File "d:\soft\python\lib\unittest\loader.py", line 475, in _find_test_path                                                tests = self.loadTestsFromModule(package, pattern=pattern)                                                            File "d:\soft\python\lib\site-packages\setuptools\command\test.py", line 55, in loadTestsFromModule                       tests.append(self.loadTestsFromName(submodule))                                                                       File "d:\soft\python\lib\unittest\loader.py", line 190, in loadTestsFromName                                              return self.loadTestsFromModule(obj)                                                                                  File "d:\soft\python\lib\site-packages\setuptools\command\test.py", line 55, in loadTestsFromModule                       tests.append(self.loadTestsFromName(submodule))                                                                       File "d:\soft\python\lib\unittest\loader.py", line 211, in loadTestsFromName                                              (obj, test))                                                                                                        TypeError: calling <function particle_input at 0x054ED228> returned <function particle_input.<locals>.decorator at 0x04553078>, not a test `

**Comment by namurphy** [comment]
Closing this since #1163 removes the recommendation to use this command to run our tests.
