### ISSUE TITLE
Update acknowledgements to include NSF CSSI grant

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#679]
Good news, everyone!  The NSF CSSI proposal that we submitted has officially been awarded!  At the request of NSF program manager Slava Lukin, we should update our acknowledgements to include this grant and reflect the support from NSF.  I'll assign myself to do this when the grant officially starts (which appears to have been moved up to October 1, 2019).  The things that we need to do include:

 - [x] Revise the sentence that we ask people to include in the acknowledgements section of their papers to reflect funding from NSF 
 - [x] Add an acknowledgements section at the end of `README.md`
 - [x] Update `CITATION.md`
 - [x] Update `docs/about/credits.rst`
 - [x] Update `plasmapy.__citation__`

Another thing peripherally related to this issue is to:

 - [x] Update the [proposal](https://doi.org/10.5281/zenodo.2633286) that we archived on Zenodo to include the answers to questions we had to send in and the panel's comments

I'll assign this to myself.

**Comment by StanczakDominik** [comment]
🎉 

It would probably make sense to have that ready as a PR to be merged at the crack of October dawn ;)

**Comment by namurphy** [comment]
> It would probably make sense to have that ready as a PR to be merged at the crack of October dawn ;)

Coincidentally, I never stay up on New Year's Eve until past midnight to submit a PR that updates that copyright dates for our license.  Nope, I have not done that at all.
