### ISSUE TITLE
Optimize `add_magnetostatic`

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#684]
I'm pretty sure there are ways to optimize what we have for it in `plasma3d`. I didn't find (yet) easy ways of doing it with numba, but I think a numpy broadcasting solution is likely possible.

_Originally posted by @StanczakDominik in https://github.com/PlasmaPy/PlasmaPy/pull/675_

**Comment by StanczakDominik** [comment]
https://github.com/PlasmaPy/PlasmaPy/blob/8f7f2c578799e9f9708f42ea107a5de5c23b5510/plasmapy/classes/sources/plasma3d.py#L118-L126 this, for reference, is the code I'm referring to.

**Comment by adityamagarde** [comment]
Is this still open?
I think I can improve this.

**Comment by StanczakDominik** [comment]
Sure is! Go right ahead :)

**Comment by StanczakDominik** [comment]
Fixed by #703
