### ISSUE TITLE
Implement a basic 2D MHD code

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#7]
One possibility for future development in PlasmaPy is adding basic simulation capabilities.  At first, the codes can be simple (e.g., 2D resistive MHD on a rectangular grid using finite differences and a straightforward time-advance).  Later, the project could include more sophisticated options and numerical methods (finite element, spectral element, finite volume, etc.).  Some thoughts on 2D MHD simulation capabilities are:
- The code should be easy to set up and use so that it can be used for educational purposes
- The code should be extremely well documented, with unit tests and test cases
- The output should be in a standard format, probably HDF5
- Following best practices for scientific computing, the code should work before it is optimized. Possibilities for optimization include:
  - Using numpy arrays and cython/numba
  - Developing it in Fortran or C/C++
- When figuring out how to develop this, we should keep in mind possibilities for longer-term development
- Related possibilities for development include
  - A basic 2D particle-in-cell code for kinetic simulations
  - Reduced MHD simulation capabilities

**Comment by SolarDrew** [comment]
I have a lot of previous work I can put towards this, which I'm porting onto my fork in bits when I have time, so I've assigned myself to this for now.

**Comment by namurphy** [comment]
Thank you!  In terms of the interface, I've been thinking a lot a lot about [Dedalus](http://dedalus-project.org/) which is a flexible spectral code in Python/Cython and seems to be really intuitive.  I'm really impressed with their [problem file for 3D Rayleigh-Benard convection](https://bitbucket.org/dedalus-project/dedalus/src/90d8b271bb66e24a32ca9b4b7b425d77b8813927/examples/ivp/3d_rayleigh_benard/rayleigh_benard.py?at=default&fileviewer=file-view-default) which is really readable and only 147 lines long including comments and docstrings!  Likewise, one of the things I would really like for us is to have the interface be as readable, understandable, and intuitive as possible.

**Comment by lemmatum** [comment]
@namurphy note that "kinetic" and "PIC" are actually two different simulation methods (though I think they can sometimes be brought together to bear upon a problem).
Somewhat useful [wikipedia page](https://en.wikipedia.org/wiki/Plasma_modeling)

**Comment by lemmatum** [comment]
Also perhaps we can take some inspiration from and compete with [FLASH](http://www.flash.uchicago.edu/site/)
