### ISSUE TITLE
Replace "code" with "software" in readme

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#70]
It turns out Fortran lingo is mighty confusing.

Please see the attached Reddit thread and the related discussion:

https://www.reddit.com/r/Python/comments/6qa11t/comment/dkw3hfu

**Comment by ministrike3** [comment]
The reddit comment is actually talking about the vision statement and I'm currently working on it!

**Comment by StanczakDominik** [comment]
@ministrike3 oh right, yeah. I misread that. Thank you for the PR, closing this one!
