### ISSUE TITLE
Add docstrings to decorator `angular_freq_to_hz`

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#723]
Decorator [`plasmapy.utils.decorators.converter.angular_freq_to_hz`](https://github.com/PlasmaPy/PlasmaPy/blob/9ba3f4eb5dbbb1a3d7b25527e0d5eb62c5086edf/plasmapy/utils/decorators/converter.py#L13) needs docstrings.

**Comment by JvPy** [comment]
I would like to take that

**Comment by rocco8773** [comment]
@JvPy Have at it! Let us know if you have any additional questions.

**Comment by rocco8773** [comment]
closed by #729
