### ISSUE TITLE
`plasmapy.formulary.quantum.chemical_potential` bug with powers

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#726]
The current doctest error for `plasmapy.formulary.quantum.chemical_formula()` is a result of a floating point arithmetic error...

<img width="805" alt="image" src="https://user-images.githubusercontent.com/29869348/69690641-5d474980-1081-11ea-95fc-86d0d29e34fa.png">

There is a large difference in `n_e` when we convert from `cm ** -3` to `m ** -3`...

```python
>>> (1.e27*u.m**-3) - (1.e21*u.cm**-3).to(u.m**-3)
<Quantity 1.37438953e+11 1 / m3>
```

Thus, even though the inputs are essentially identical, the following yields...

```python
>>> chemical_potential(1.e27 ** u.m ** -3, 11000 * u.K)
<Quantity 2.00039985e-12>

>>> chemical_potential(1.e21 ** u.cm ** -3, 11000 * u.K)
<Quantity 5.1487703e-12>
```

@namurphy @StanczakDominik Thoughts???  If we can't figure out a quick fix, then I feel like we should exclude this code from the source until we determine a solution.

_Originally posted by @rocco8773 in https://github.com/PlasmaPy/PlasmaPy/pull/722#issuecomment-558917491_

**Comment by rocco8773** [comment]
This issue has been raised on AstroPy ([#9721](https://github.com/astropy/astropy/issues/9721)).

**Comment by JaydenR2305** [comment]
@StanczakDominik I think this is working now, I get identical outputs for your given example case

**Comment by StanczakDominik** [comment]
Huh! Can you try removing `@pytest.mark.xfail` from the related tests in `quantum` to trigger CI runs for this?

**Comment by JaydenR2305** [comment]
I'm getting an assertion error for the known test case... Was the test case itself calculated incorrectly?

**Comment by StanczakDominik** [comment]
Could be! Can you post that as a PR?
