### ISSUE TITLE
What is missing from plasmapy.formulary?

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#734]
The [`plasmapy.formulary`](http://docs.plasmapy.org/en/latest/formulary/index.html) subpackage contains a whole bunch of functions from the [NRL Plasma Formulary](https://www.nrl.navy.mil/ppd/content/nrl-plasma-formulary) and other sources, but there are many functions that or missing or need improvements in the documentation or implementation.  This issue will be a place for us to discuss what we still need to do in `plasmapy.formulary`.  **If you notice anything missing from `plasampy.formulary`, please post a comment below!**

**Comment by namurphy** [comment]
An old open issue (#49) is to implement functions for dimensionless parameters like `Lundquist_number`, `Reynolds_number`, and `Prandtl_number`. For these functions, we need to reduce viscosity/resistivity to a scalar, and we should think carefully about which of the tensor components we should use.  For example, should we use the perpendicular or parallel Spitzer resistivity in `Lundquist_number`?  

Also, #730 would be a good place to discuss transport coefficients since we need to do a major refactoring of that anyway.

Some additional plasma formulary references include:
 - [Plasma Formulary for Physics, Astronomy, and Technology](https://onlinelibrary.wiley.com/doi/book/10.1002/9783527653256) by Declan Diver (2nd ed.)
 - A. Anders, A Formulary for Plasma Physics, Akademie-Verlag, Berlin Germany (1990)
 - [Magnetic Fusion Energy Formulary](https://github.com/MFEFormulary/MFEFormulary)

**Comment by KhalilBryant** [comment]
I have a list of functions/equations in the NRL formulary that I could not find in the PlasmaPy formulary. Here's a few:
Stokes' Number
Mach number
magnetic Debye Length
electron/ion trapping rates
Plasma dispersion function
Fokker-Planck equation
frictional/thermal gradient heat fluxes
relativistic energy
Saha equation

**Comment by rocco8773** [comment]
Creating aliases (#856) for the most common formulary functions.
