### ISSUE TITLE
Add units to Magnetostatics reprs

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#740]
Objects from the Magnetostatics module currently show up in reprs without units, because they're being cast to floats on class construction. It would be nice to have them save the input units, or at the very least, to display the units they're saving their inputs to, in their reprs and strs.

**Comment by Ishinomori** [comment]
Would like to work on it. Do we want to have e. g. `FiniteStraightWire(p1=0.01m, p2=2.0m , current=3.0A)` or with with more code compatible format like `FiniteStraightWire(p1=0.01 * u.m, p2=2.0 * u.m , current=3.0 * u.A)`?

**Comment by Ishinomori** [comment]
What is case of `CompositeUnit` which is dimensionless? Should we have `isinstance` check on attribute assignment or something else?
