### ISSUE TITLE
Move plasmapy.examples into the repository root directory [PLEP7]

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#745]
As part of the changes associated with the forthcoming PLEP 7 (PlasmaPy/PlasmaPy-PLEPs#26), we decided to move ``plasmapy.examples`` out from `plasmapy`'s top-level and into the repository's root directory.  Examples are primarily used for documentation and, thus, do not need to be packaged with the ``plasmapy`` distribution.

**Comment by namurphy** [comment]
For this issue, we'll need to make sure that the examples still show up in the documentation build (which we can preview with Giles, which should show up in the list of tests that are run).  We'll need to change [this line](https://github.com/PlasmaPy/PlasmaPy/blob/f7a4a86922fb91afcab845fba8aa0c160fad329f/docs/conf.py#L219), which I think should do it hopefully.

**Comment by StanczakDominik** [comment]
This would be handled by #792
