### ISSUE TITLE
Create plasmapy.tests [PLEP7]

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#746]
As part of the changes associated with the forthcoming PLEP 7 (PlasmaPy/PlasmaPy-PLEPs#26), we decided create a ``plasmapy.tests`` sub-package.

Tasks:

- [ ] Create ``plasmapy.tests``
- [ ] Move ``plasmapy.utils.pytests_helpers`` to ``plasmapy.tests.pytest_helpers``

**Comment by namurphy** [comment]
Update: #919 is creating `plasmapy.tests.helpers`.
