### ISSUE TITLE
Make test order deterministic so we can use `pytest-xdist` in `plasmapy.particles`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#750]
The order that tests are run in (what will soon be) `plasmapy.particles` is not deterministic.  Some of the functionality in that subpackage uses [set](https://docs.python.org/3/tutorial/datastructures.html#sets) operations, which do not preserve order.  Since the order of our tests sometimes depends on set operations, the order of tests changes.

Nominally, unit tests should be able to be run in any order.  However, I ran into a problem when trying to use [`pytest-xdist`](https://docs.pytest.org/en/3.0.1/xdist.html) to run tests in parallel, as this package currently requires test order to be deterministic when figuring out which tests to send to which processor.  Since our test order will only get bigger with time, it would be helpful to make our test order deterministic so that we have the capability of running tests in parallel.

The two possibilities that I can think of are:
 - Use [OrderedSets](https://pypi.org/project/ordered-set/) instead of regular sets (with the disadvantage that this would require adding another dependency to PlasmaPy)
 - Use sorting in the operations in which tests get selected (probably using `sorted`).  

The files that are affected include:

 - [ ] `test_ionization_state.py`
 - [ ] `test_ionization_states.py`
 - [ ] `test_parsing.py`
 - [ ] `test_particle_class.py`
 - [ ] `test_special_particles.py`

The quick way to test this is to install `pytest-xdist`, go to the tests directory, and then try running in the command prompt: 

```pytest -n 4 test_parsing.py```  

Thanks!

**Comment by StanczakDominik** [comment]
Oh, so that's what was causing me trouble when adding pytest-xdist to tox! I think I was able to dodge using this line

https://github.com/PlasmaPy/PlasmaPy/blob/da2aaeeca87b1ee2c63a954e37a9c72471671e1e/tox.ini#L13

where `--dist=loadfile` means, AFAIK, the tests are parallelized by file. Thus, the order of tests in a single file doesn't matter.

**Comment by wang-ories** [comment]
Hi @namurphy can I take this up?

**Comment by namurphy** [comment]
> Hi @namurphy can I take this up?

Yes, please do!

**Comment by wang-ories** [comment]
> > Hi @namurphy can I take this up?
> 
> Yes, please do!

Okay

**Comment by namurphy** [comment]
It looks like we're still having some problems running `pytest-xdist`, specifically for `plasmapy.particles`, since the order of collected tests is different.  The first thing I'd check look into is the use of `.keys()` and `.values()` for dictionaries when parametrizing tests.

The beginning of the output that I got was:
```
$ pytest numprocesses=8
====================================================== test session starts ======================================================
platform linux -- Python 3.10.4, pytest-7.1.3, pluggy-1.0.0
rootdir: /home/namurphy/Projects/PlasmaPy, configfile: setup.cfg, testpaths: plasmapy
plugins: datadir-1.3.1, forked-1.4.0, hypothesis-6.54.5, regressions-2.3.1, xdist-2.5.0, anyio-3.6.1
gw0 [4217] / gw1 [4217] / gw2 [4217] / gw3 [4217] / gw4 [4217] / gw5 [4217] / gw6 [4217] / gw7 [4217]
collecting 0 items / 1 error                                                                                                    
============================================================ ERRORS =============================================================
_____________________________________________________ ERROR collecting gw0 ______________________________________________________
Different tests were collected between gw2 and gw0. The difference is:
--- gw2

+++ gw0

@@ -3224,21 +3224,21 @@

 plasmapy/particles/tests/test_parsing.py::test_parse_InvalidParticleErrors[Rh XXXX-kwargs29]
 plasmapy/particles/tests/test_parsing.py::test_parse_InvalidParticleErrors[Li -II-kwargs30]
 plasmapy/particles/tests/test_parsing.py::test_parse_InvalidParticleErrors[B +IV-kwargs31]
+plasmapy/particles/tests/test_parsing.py::test_parse_InvalidElementErrors[tau-]
+plasmapy/particles/tests/test_parsing.py::test_parse_InvalidElementErrors[e-]
+plasmapy/particles/tests/test_parsing.py::test_parse_InvalidElementErrors[mu+]
+plasmapy/particles/tests/test_parsing.py::test_parse_InvalidElementErrors[n]
+plasmapy/particles/tests/test_parsing.py::test_parse_InvalidElementErrors[p-]
```
(it goes on quite a while longer after that)
