### ISSUE TITLE
Check for and remove any mutable arguments in functions & methods

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#752]
Callable objects [should not have mutable default values](https://florimond.dev/blog/articles/2018/08/python-mutable-defaults-are-the-source-of-all-evil/) (like lists, sets, and dictionaries) for functions and methods because unexpected behavior like this can happen:
```
In [2]: def f(a=[]): 
   ...:     a.append(0) 
   ...:     print(a) 
   ...:

In [3]: f()
[0]

In [4]: f() 
[0, 0]
```
We should check for mutable arguments in functions and methods, and then remove any that we do find.  The most likely place for this is in what will soon be `plasmapy.particles` (`plasmapy.atomic` until #742).  It may show up a bit also in `plasmapy.formulary`, perhaps `plasmapy.utils`, and maybe elsewhere.

Thanks to @Ishinomori for bringing this up and making a fix to this in #751!

**Comment by Ishinomori** [comment]
I can take it as well.
To search for similar issues in the future you can run `pylint plasmapy --disable=all --enable=dangerous-default-value` from top-level dir.

**Comment by namurphy** [comment]
Thank you again!  Running the command you gave shows this happening in the following files.

- `plasmapy/atomic/particle_input.py`
- `plasmapy/atomic/parsing.py`
- `plasmapy/utils/datatype_factory_base.py`
- `plasmapy/utils/pytest_helpers/pytest_helpers.py` (ignore this one for now, as it's getting heavily refactored in #728)
- `plasmapy/utils/pytest_helpers/error_messages.py` (ignore this one too, same reason)
- `plasmapy/formulary/tests/test_collisions.py`
- `plasmapy/formulary/tests/test_parameters.py`
```
