### ISSUE TITLE
Fix plasmapy.version

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#758]
After deleting `plasmapy/version.py` in PR #739, `plasmapy.version` no longer works.  This needs to be removed from `plasmapy/__init__.py` or another scheme needs to be developed to broadcast the current PlasmaPy version via `plasmapy.version`.

**Comment by StanczakDominik** [comment]
This is meant to be handled by setuptools_scm... I'll try to explain more later.

**Comment by rocco8773** [comment]
ok...I missed the `plasmapy.__version__` and thought `plasmapy.version` was suppose to work like before. 🤦🏻‍♂️

**Comment by StanczakDominik** [comment]
Right! :)

I'm not 100% sure I didn't break some workflows for pip installing from github if the user happens not to have setuptools_scm installed, or something. We'll have to watch this and reopen if necessary.
