### ISSUE TITLE
Create 3D null point finders

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#764]
Issue #47 includes a broad request tools for analyzing 3D magnetic topology.  The first step is to create 2D and 3D null point finders.  In particular, the goal is to find the locations where the 2D or 3D magnetic field vector (which is itself a function of 2D or 3D space) is zero.  

[Haynes & Parnell (2007)](https://doi.org/10.1063/1.2756751) describe a trilinear interpolation scheme that should work on a grid.  We will also need to be able to find null points for analytically specified magnetic fields, and for different geometries (i.e., cylindrical/toroidal, & spherical).  There's some more information in #47.

This should go in a subpackage in `plasmapy.analysis`.  There might be helpful functionality in `scipy.optimize` and/or `scipy.interpolate`.  If the relevant functionality isn't already in SciPy, then it would be worth considering adding it there to make this contribution most broadly available.  A 3D root finder will probably need to be optimized...eventually.  I'd suggest waiting for a different pull request to optimize it.  The implementation of this will probably depend on our base data structures.

**Comment by StanczakDominik** [comment]
scipy.optimize.minimize on B^2 for the rough neighborhood, then interpolate to find 0 semi-exactly?

**Comment by namurphy** [comment]
Closed by #1383.  See also #1384, #1425, and #1526.
