### ISSUE TITLE
Classify 2D and 3D null points

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#765]
After #764 is finished, the next step toward creating 3D magnetic topology analysis tools (#47) is to classify the 2D and 3D null points.  The classifications are described by [Parnell et al. (1994)](https://doi.org/10.1063/1.871810), who went through the process of linearizing the magnetic field around the null point.  Some of possible classifications include potential nulls, improper/proper radial nulls, and spiral nulls.  The classification depends on the eigenvalues of the linearized magnetic field at the null point.  Users will sometimes need to access the eigenvalues and eigenvectors, as well as some other values/vectors associated with the null point.

**Comment by StanczakDominik** [comment]
Sounds like the classification of critical points in nonlinear dynamics - attractors, repellers, etc! A cool project, then.

**Comment by namurphy** [comment]
> Sounds like the classification of critical points in nonlinear dynamics - attractors, repellers, etc! A cool project, then.

Yep!  This is a project that's highly relevant to my own research on magnetic reconnection...or at least it would be if I actually did any research these days. :joy_cat:

**Comment by namurphy** [comment]
Closed by #1383.  See also #1384, #1425, and #1526.
