### ISSUE TITLE
Fix definition of `version` and `release` in docs conf.py

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#775]
Update the the definition of sphinx project info `version` and `release`, such that they are automatically updated with package versions.  A good example of how to do this can be seen in Astorpy's `conf.py` [here](https://github.com/astropy/astropy/blob/f6a9846b5e7c054878080ba49212a961bab2ff78/docs/conf.py#L111-L114).

```python
# The full version, including alpha/beta/rc tags.
release = pkg_resources.get_distribution(project).version
# The short X.Y version.
version = '.'.join(release.split('.')[:2])
```

This method does create a documentation dependency on `setuptools`.

**Comment by StanczakDominik** [comment]
Everyone has setuptools nowadays. Isn't it a dependency for pip?

**Comment by rocco8773** [comment]
`pip` probably does depend on `setuptools`, so it's unlikely that `setuptools` won't be installed.  This is more of a FYI and that we should indicated the dependency in any *"requirements"*.

**Comment by StanczakDominik** [comment]
On an unrelated note, every time I see an issue of this kind I think it would have been more global-work-time-efficient to write the description here as a commit message and just send a lightning-fast PR ;)

**Comment by StanczakDominik** [comment]
But of course that's probably just my chaotic good alignment manifesting via grumpiness about your orderly way of doing things, so don't mind me :laughing:
