### ISSUE TITLE
CircleCI docs build failing on master

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#778]
https://app.circleci.com/pipelines/github/PlasmaPy/PlasmaPy/64/workflows/0dbf9222-a93e-4040-8ec7-890385b78174/jobs/5471 is failing, seemingly due to a new warning in https://www.sphinx-doc.org/en/master/changes.html#id14. RTD on the other hand is building nicely https://readthedocs.org/projects/plasmapy/builds/10782778/, but that's probably because we don't set it to raise on warnings. I'll fix it as time allows.

**Comment by rocco8773** [comment]
I've looked into this a little bit and it appears the error is coming from duplicate docstrings on `kinetic_energy_history` [here](https://github.com/PlasmaPy/PlasmaPy/blob/8ade13ccc99161ed50889c7987b3254490c41503/plasmapy/simulation/particletracker.py#L54-L55) and [here](https://github.com/PlasmaPy/PlasmaPy/blob/8ade13ccc99161ed50889c7987b3254490c41503/plasmapy/simulation/particletracker.py#L117-L125).  When I removed the duplicate from the class level docstring, then the error was fixed but a new one popped up.  I'm trying to figure the new error out before establishing a PR, but I'm at a bit of a loss.  The new error appears to be similar to the issue https://github.com/sphinx-doc/sphinx/issues/3350.

**Comment by StanczakDominik** [comment]
It'd be easier to discuss the errors themselves with an exploratory draft pr already out there ;)

**Comment by rocco8773** [comment]
Agreed, just haven't gotten around to it.  I'll have something up a little later.
