### ISSUE TITLE
Free up Sphinx version dependency (v2.4.4) to all versions

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#782]
PR #780 inacted the dependency `sphinx <= 2.4.4`, since `sphinx-automodapi` is currently incompaticle with `sphinx` `v3.0.0`.  When https://github.com/astropy/sphinx-automodapi/issues/99 is resolved, then we should free up the version dependency for `sphinx`.

**Comment by StanczakDominik** [comment]
Seems to have been resolved in a86e218aa :)
