### ISSUE TITLE
Add a Citation File Format file

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#794]
From the [Citation File Format](https://citation-file-format.github.io/) webpage:

> `CITATION.cff` files are plain text files with human- and machine-readable citation information for software. Code developers can include them in their repositories to let others know how to correctly cite their software.

This should be used in addition to the CodeMeta file (e.g., #793).

**Comment by StanczakDominik** [comment]
https://github.com/citation-file-format/doi2cff could this be of use?

**Comment by namurphy** [comment]
> https://github.com/citation-file-format/doi2cff could this be of use?

Yes, that really does look useful!

**Comment by namurphy** [comment]
Closed by #1640.
