### ISSUE TITLE
[PIC] Poisson solver

### ISSUE THREAD

**Issue by antoinetavant** [PlasmaPy/PlasmaPy#80]
task from #69 , for PIC simulation
For the Electrostatic PIC simulation, a Poisson solver will be needed.
- [ ] for 1D, Thomas Solver gives the exact solution. Boundaries have to be carefully set
- [ ] for 2D, a solver is needed. Multiples solvers could be implemented, starting from a homemade SOR, then libraries could be called. Boundaries again : careful
- [ ] Electric field calculation from Potential : warning the boundaries

We forget the 3D for Now. Boundaries can be : periodic, Dirichlet (Phi = Phi_0) or Neumann ( E = E_0) depending of the boundary.

**Comment by tulasinandan** [comment]
About the EM solvers, I was wondering if we should re-invent the wheel or use an exsting EM solver. For a modular framework we would want a separate Maxwell solver for the fields.

**Comment by tulasinandan** [comment]
I have been thinking about it a quite a bit and my idea would be to have a function that takes every possible thing (grid, physics parameters, field values, time step, number of steps, anything else...) as a parameter and updates the fields for the desired number of steps, and finally returns the updated fields. Inside the solver, we would have cases for cartesian, cylindrical, spherical and whatever grids, and maybe a few different algorithms. A pure function without any side effects.

Then, we can have wrappers on top of it for different cases we might want.

**Comment by StanczakDominik** [comment]
A reasonable object oriented structure would probably also work for code organization. I don't have strong opinions on how to organize the computation itself in a way that's parallelizable.

And with the direction we've been taking lately, I fear our code may soon approach 30% decorator applications. :smiley:
