### ISSUE TITLE
Changelog instructions -> docs, PR template?

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#811]
[From yesterday's meeting:](https://docs.google.com/document/d/1g2XDqZpDpLV3ubDza350bkxe4xgGThzZGuYy1NaR3dQ/edit#)

> Need to make instructions on changelog files more straightforward and easier to find

I imagine two places these could be added:

- [ ] [the code guide](https://github.com/PlasmaPy/PlasmaPy/blob/master/docs/development/code_guide.rst)
- [ ] [the pull request template](https://github.com/PlasmaPy/PlasmaPy/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by namurphy** [comment]
I forgot about updating the pull request template.  That's a really good idea.  Thanks!
