### ISSUE TITLE
Move `plasmapy.data` to `plasmapy.particles.data`

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#817]
> @rocco8773  will initiate PR on moving plasmapy.data to plasmapy.particles.data

https://docs.google.com/document/d/14ofIBJlXIoxYjtlGPiXeUWKIp7Ynull5Q5K8eeIDyWg/edit#

You signed up for it, mate :smile:

**Comment by rocco8773** [comment]
Thanks mate! At least it's now on my GitHub notification list. 🤣
