### ISSUE TITLE
Aliases for common formulary function

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#855]
We've decided [at the telecon](https://docs.google.com/document/d/1H_TiB3mv1UKRdi6PNGS7nNUh8SYnpk8rDpu07jVU5gk/edit#) it would be handy to built-in aliases to the formulary functions:

```python
def plasma_frequency(...):
    return 42

wp = plasma_frequency
"""Alias for :fund:`plasma_frequency`."""
```

Because apparently people at BAPSF use it that way, and we'd like to make canonical aliases a thing!

This will mean we'll have to come up with aliases for the following functions:

- [ ] List the relevant functions!

**Comment by rocco8773** [comment]
Whoops! Didn’t even see this here. You’re trigger finger is faster than mine.

**Comment by StanczakDominik** [comment]
Glad to see all that starcraft practice paying off! :D
