### ISSUE TITLE
Thumbnails missing/broken on plasmapy documentation webpage home

### ISSUE THREAD

**Issue by svincena** [PlasmaPy/PlasmaPy#874]
As the title suggests, and can be seen on the screenshot, two of the three thumbnails
are missing from the PlasmaPy documentation front page at https://docs.plasmapy.org/en/latest/
<img width="598" alt="Untitled" src="https://user-images.githubusercontent.com/7075058/88436433-2b75b680-cdb9-11ea-92a0-83ebd8d67880.png">

**Comment by rocco8773** [comment]
Arg!  Thanks for the notification.  I'm pretty sure I know what is causing this.
