### ISSUE TITLE
Would plasmapy.utils.roman be better as a file than a pkg?

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#882]
Looking over the `plasmapy.utils.roman` sub-package, it might be better served as just being a `roman.py` file than a sub-package.  If we don't convert it to a single file, then we should at least break the exceptions out into `plasmapy/utils/roman/exceptions.py`.

**Comment by StanczakDominik** [comment]
Yeah it probably should have been a single module come to think of it.

**Comment by rocco8773** [comment]
Whatever we decide, there is some cross-over with #881.

**Comment by namurphy** [comment]
Having it as a single module sounds good to me too.

**Comment by rocco8773** [comment]
Ok, I'll take this on.
