### ISSUE TITLE
Link to a primer on restructuredtext in development guide

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#904]
This can go in the documentation guide, probably.

**Comment by Tiger-Du** [comment]
Hi, Nick.

I'd be happy to take a swing at this one. I'm new to software development (and GitHub), so it'll be my first PR. A good link I found is [https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html](url) from the website of Sphinx.

In addition, I noticed that this link in the documentation guide, [https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt](url), to the "numpydoc standard for docstrings" no longer works and should be replaced with [https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard](url). Would it be alright if I replace this link in the same PR?

**Comment by namurphy** [comment]
@Tiger-Du — Yes, please do!  And thank you!
