### ISSUE TITLE
Python3 language in docs

### ISSUE THREAD

**Issue by cskinner74** [PlasmaPy/PlasmaPy#906]
## Feature request

When looking at the main README and digging through some of the doc pages, I noticed references to running scripts with python commands such as `python setup.py` or `pip install .`.

Since PlasmaPy runs on Python3, should these instructions be changed to `python3 setup.py` and `pip3 install`?

If this is something you think should be added, I can get started on it.

**Comment by StanczakDominik** [comment]
That's only true if you're using the system installation of Python on the particular Linux (can't speak for other OSs myself) distros that ship both legacy Python and Python 3.

It could be a good idea to add in there a note about that for users of those particular distros (which, besides Ubuntu?) though.

**Comment by wskinner74** [comment]
Ah gotcha. I primarily deal with Debian systems that come preloaded with both so I wasn't sure. Adding a note in there could be useful, but probably not urgent.

**Comment by namurphy** [comment]
Closing this, since we now state in our [installation instructions](https://docs.plasmapy.org/en/latest/install.html) that sometimes the installation requires `pip3` instead of `pip`.
