### ISSUE TITLE
Update `@particle_input` docstring on use of `Optional[Particle]` annotations

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#913]
In #535, we allowed annotations of `Optional[Particle]` to be used with `@particle_input`.  What this does is allow `None` to be passed as an argument, in addition to something particle-like.  However, the docstring for `@particle_input` does not include this yet.  We'll need to update the `@particle_input` docstring so that it describes this behavior.

Related to: #912

**Comment by rocco8773** [comment]
@namurphy I'm working on this now as I'm trying to address issue #912.
