### ISSUE TITLE
Cool projects plasma physics in PlasmaPy?

### ISSUE THREAD

**Issue by killah-t-cell** [PlasmaPy/PlasmaPy#916]
Hi y'all,

Please pardon me if this is not the appropriate place to ask this. I just started learning Plasma physics and I would love to do some PlasmaPy projects to deepen my knowledge. What are some cool beginner and intermediate projects you could recommend? 

Thanks!

**Comment by rocco8773** [comment]
Hi @killah-t-cell, thanks for your interest in the package!  This a good place to reach out, but if you have general questions our [chat room](https://app.element.io/#/room/#plasmapy:openastronomy.org) is a better, and preferred, place to discuss.  What kind of "project" are you thinking of, a coding project or a project to use PlasmaPy for?  For the former take a look at our issues marked with ["good first contribuiton"](https://github.com/PlasmaPy/PlasmaPy/labels/Good%20first%20contribution) and for the later take a look at the [notebooks we have in the documentation](https://docs.plasmapy.org/en/stable/examples.html).
