### ISSUE TITLE
Get onto Conda

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#93]
This is somewhat related to #36. We need to be accessible and most of the cutting edge scientific Python is on [Conda](https://conda.io/docs/), probably due to ease of downloading stuff like C extensions, Numba etc.

Anyway, this gets closed once we can do `conda install plasmapy` in a new environment and have it work out of the box.

I haven't been able to find a how-to on this yet. I'll update this issue if I find anything.

https://conda-forge.org/ this is at least 70% relevant.

**Comment by SolarDrew** [comment]
I'll sort this out if nobody objects. I've been meaning to learn how to do conda packaging anyway and unless anyone has a pressing desire to take on dealing with the pip installing it seems reasonable for me to deal with both.

**Comment by wtbarnes** [comment]
Relevant PR: conda-forge/staged-recipes#4793

What is the status of this? The problem (at least right now) with the staged recipe is that the `roman` package is not included, presumably because it was added as a dependency after this PR was opened

**Comment by StanczakDominik** [comment]
The necessary functionality of `roman` got absorbed into `plasmapy/utils/roman` in an earlier PR, so that seems to have been solved. I suppose it would be best to continue this discussion at conda-forge/staged-recipes#4793 and get this done.

**Comment by StanczakDominik** [comment]
I finally got the builds to pass - the waiting game begins now.

**Comment by StanczakDominik** [comment]
We are now on Conda-forge. :)

https://github.com/conda-forge/plasmapy-feedstock
