### ISSUE TITLE
Improvements to ParticleTracker

### ISSUE THREAD

**Issue by pheuer** [PlasmaPy/PlasmaPy#936]
With some improvements/additions, the ParticleTracker module could be really useful for the LineIntegratedDiagnostic project. I'm starting this issue as a place to keep track of some possible improvements. 

Here's a list of necessary changes:
- [x] Modify the ParticleTracker to  take `grid` objects that contain E and B fields. Make use of the interpolators built into those objects for the interpolation step.

- [x] Allow particles to be initialized with positions, velocities, and species specified by the user. Based on our discussion, we'll probably use a `ParticleSpecies` class that represents a bunch of particles all of the same species.

- [ ] Provide an alternative `boris_push` that's correct for relativistic particles (for example, protons in proton radiography are often moving at 20% c). 

- [x] Make recording the position and velocity histories optional: that's a big performance/memory hit for large numbers of particles that may not be necessary. Also have an option to write that stuff out to a file instead of RAM. Can we use `h5py` for that?

- [ ] Implement a more sophisticated auto-timestep function with conditions based on E, B, and the grid size. Also, the user should still have the ability to set their own timestep.

- [ ] Allow the push functions to take arrays of q and m (so that particles don't all have to be the same species)

Stretch goals (not necessary now, but would be really helpful in the future):

- [ ] Use cython or numba to improve performance of all the interpolator and particle_pusher methods.

- [ ] Provide an option to keep a log of any grid quantities that the particles encounter at each time step, Eg. record a time trace of the B-field felt by a particle. Should be an option to record either the full time series or a cumulative sum.

**Comment by StanczakDominik** [comment]
Quick note, haven't had much time to think about the rest yet:

>  Allow particles to be initialized with positions, velocities, and species specified by the user. I propose that species be a list of particle types (nspecies long) and the position and velocity arrays x,y,z,vx,vy,vz be of shape [nspecies, nparticles].

For a simulation I think I'd rather see it as this:

```python
electrons = Species('e', 500)
electrons.r = np.random.random((500, 3)
electrons.v = # likewise

# ions likewise

ParticleTracker([electrons, ions], ...)
```

**Comment by pheuer** [comment]
That sounds good too - is the `Species` class already defined somewhere? Maybe `Species` or `Population` or something could be a subclass of `BasePlasma` in the `Plasma` module?

**Comment by pheuer** [comment]
I began to sketch out a `ParticleSpecies` class (as an input form for the `ParticleTracker`) as well as a run cycle that includes a user-provided end condition to allow simulations to run until some state is reached (ex. all protons reach a detector...) rather than a fixed number of cycles. 

https://github.com/pheuer/PlasmaPy/blob/ParticleTracker_improvements/plasmapy/simulation/particletracker.py

**Comment by pheuer** [comment]
Closing this issue because it's very broad, and many of the improvements listed here have been added by @JaydenR2305 in his recent PR #2245
