### ISSUE TITLE
Create example notebook that lets users input plasma properties and get plasma parameters

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#939]
It's pretty common for plasma physicists to have a bunch of plasma properties (e.g., magnetic field strength, ion/electron number densities, etc.) and want to calculate a bunch of plasma parameters (e.g., Debye length, electron & ion inertial lengths, electron & ion gyroradii and gyrofrequencies, etc.).  It would be really helpful to add a notebook in our [examples](https://docs.plasmapy.org/en/latest/examples.html) that allows users to input different plasma properties and then get a whole bunch of these plasma parameters printed out.  This notebook would use functionality in [`plasmapy.formulary`](https://docs.plasmapy.org/en/latest/formulary/index.html).

It would probably help to provide the inverses of different frequencies to get the associated time scales (i.e. the inverse of the gyrofrequency will give the gyroperiod).  The different length scales and time scales should be placed near each other.  It'd also be helpful to sort the different length and time scales from shortest to longest.  

This notebook would complement the notebook on [calculating ITER parameters](https://docs.plasmapy.org/en/latest/notebooks/physics.html) (which could probably use some updates too, since its obsolete reference to the `physics` subpackage should be changed to a reference to the `formulary` subpackage).  

Thanks to @svincena for suggesting this idea!

**Comment by namurphy** [comment]
Functions in `plasmapy.formulary` to start out with include:
 - `Alfven_speed`
 - `thermal_speed`
 - `Debye_length`
 - `Debye_number`
 - `gyrofrequency`
 - `gyroradius`
 - `inertial_length`
 - `lower_hybrid_frequency`
 - `upper_hybrid_frequency`
 - `plasma_frequency`

**Comment by ashton77** [comment]
Hi @namurphy, my project team would like take up this issue.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hello seems like there are no development related to this issue for a long time. Can I give this a shot?

**Comment by namurphy** [comment]
@RAJAGOPALAN-GANGADHARAN — sure, please do!
