### ISSUE TITLE
Notebook for ExB drift

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#965]
A Jupyter notebook needs to be created in our documentation that not only shows how to use `plamsapy.formulary.drifts.ExB_drift()` but that also describes the physics behind the drift.  The notebook has to be placed in `/docs/notebooks/` or one of it's sub-directories.  Then the notebook needs to be properly reference in the documentation.

**Comment by StanczakDominik** [comment]
I don't think that needs to be a new notebook; I don't think we had that functionality when I was first drafting the particle tracker notebook, and I didn't add it there later on. How about I add that as part of #953 ?

**Comment by rocco8773** [comment]
I'm basically trying to come up with projects that new contributors could pick up to learn the mechanics of contributing and don't feel to daunting. This is not a high priority item, but it would be useful to have a notebook on drifts. This notebook would be more useful as educational material than to show how to use functionality.

**Comment by StanczakDominik** [comment]
Ah, in that case - sure, these two are not mutually exclusive :)

**Comment by kjmontes** [comment]
Hi everyone,
My name is Kevin, and I'm a graduate student at MIT. I took some time to work on this today and just submitted a corresponding pull request. This is my first contribution to PlasmaPy, so please let me know if there's anything I missed.
Thanks!
