### ISSUE TITLE
Diamagnetic Drift

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#966]
Add to `plasmapy.formulary.drifts` functionality for the diamagnetic drift.

![image](https://user-images.githubusercontent.com/29869348/102567260-fc2c5280-4095-11eb-9191-8041cb571cf4.png)

See eq. 3-65 in Chen, Francis F. *Introduction to Plasma Physics and Controlled Fusion.* 2nd ed. Springer, https://doi.org/10.1007/978-1-4757-5595-4.

**Comment by StanczakDominik** [comment]
Closed by #972 :)
