### ISSUE TITLE
Two fluid analytical solutions for different cases

### ISSUE THREAD

**Issue by qudsiramiz** [PlasmaPy/PlasmaPy#973]
## Feature request
Implementing package to compute the dispersion equation both analytically and numerically as mentioned in PR #932 

**Analytical methods:**
1. Solution based on analytical expression given in [Bellan2012](https://doi.org/10.1029/2012JA017856).
    **Note:** This method makes no assumption for the range of frequency or propagation angle and thus is valid for the whole  k-w space.

**Numerical Solutions:**
1. Solution based on equations given by [Hollweg1999](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/1998JA900132).
2. Solution based on 2 x 2 Matrix approach as derived in multiple papers ([Hasegawa1982](https://www.osti.gov/biblio/5259641), [Lysak1996](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/95JA03712))
3. Solution based on 3 x 3 Matrix method as used in [Hirose2004](https://ui.adsabs.harvard.edu/abs/2004PhLA..330..474H)
4. Solution based on the cold plasma assumption as derived by [Stix1992](https://ui.adsabs.harvard.edu/#abs/1992wapl.book.....S)
5. Solution based on full [XENON](https://github.com/liangwang0734/xenon) developed by Liang Wang.

**Comment by anthony-vo** [comment]
I studied with Dr. Lysak this semester and went through the entire derivation in the appendix of Lysak, 1996. I would be interested in writing some code to solve for Fig. 1 and 2 in there :)

**Comment by ahmadryan** [comment]
> I studied with Dr. Lysak this semester and went through the entire derivation in the appendix of Lysak, 1996. I would be interested in writing some code to solve for Fig. 1 and 2 in there :)

That would be great and so welcomed. We can talk more about it in the Element channel for Dispersion Relations. :)

**Comment by rocco8773** [comment]
I'm going to close this issue in favor of issue #1237 to provide a broader scope of the project.
