### ISSUE TITLE
Add check 'can_be_zero' to decorator class CheckValues

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#976]
There are some plasma parameters out there that can not have a zero value, for example density.  We should add an additional check to `plasmapy.utils.decorators.checks.CheckValues` to check against this.  The check should be named `'can_be_zero'` and the default value should be `True`.

Other points:

- The docstrings for `CheckValues`, `check_values()`, `ValidateQuantities`, and `validate_quantities()` will need to be updated.
- Tests for the above items will need to be updated too.

**Comment by davemus** [comment]
Hi! I am new to this project, but I'm willing to contribute. I would like to take this issue. Is any prerequisites required?

**Comment by rocco8773** [comment]
Welcome @davemus!  Thank you for you interest in the project.  There is no prerequisites for the project, but some familiarity with python anddecorators will be useful.  You'll especially want to look through the [`CheckValues` code](https://github.com/PlasmaPy/PlasmaPy/blob/b4683916a4d352bf97f2fe7e078a09fec1ae95ba/plasmapy/utils/decorators/checks.py#L67) and its [documentation ](https://docs.plasmapy.org/en/latest/api/plasmapy.utils.decorators.CheckValues.html#plasmapy.utils.decorators.CheckValues) to familiarize yourself with it's mechanics.  If you look at [these lines of code](https://github.com/PlasmaPy/PlasmaPy/blob/b4683916a4d352bf97f2fe7e078a09fec1ae95ba/plasmapy/utils/decorators/checks.py#L125-L136), I did comment how to add new checks and upon doing so the functionality should propagate out to all the functionality I mention in the issue summary.

If you run into issues, you can either post a question here or on our [chat room](https://app.element.io/#/room/#plasmapy:openastronomy.org).

**Comment by davemus** [comment]
Looks like I wrecked a check via `git push --force`. Here is the [comment](https://github.com/PlasmaPy/PlasmaPy/pull/999#issuecomment-773607472) with precise error.

Could it be fixed somehow, or should I reopen PR?

**Comment by davemus** [comment]
Should this be closed after merging [999](https://github.com/PlasmaPy/PlasmaPy/pull/999)?

**Comment by rocco8773** [comment]
closed by #999
