### ISSUE TITLE
Drop Python 3.6 support for version 0.6.0

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#980]
[NumPy Enhancement Proposal 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) suggests that scientific Python projects support versions of Python released in the last 42 months.  Python 3.6 was released more than 42 months ago, so this suggests that we no longer need to support Python 3.6.  Astropy 4.2 also requires Python 3.7+, so we'll need to go with a more recent version of Python anyway.  There are a few [new features in Python 3.7](https://docs.python.org/3/whatsnew/3.7.html) that look relevant, including dataclasses.  I propose we drop Python 3.6 support with PlasmaPy version 0.6.0.  I think this would require:

- [ ] Updating the requirements declarations
- [ ] Updating our test matrix
- [ ] Updating our documentation where it mentions
- [ ] Updating our website
- [ ] Updating the main `__init__.py` (I think)
- [ ] Discussing this in the changelog

...though it's probable I'm missing a few things.

(NEP 29 also suggests that projects support versions of NumPy from the last 24 months, which would mean that we should support NumPy 1.17+.  However, we've been supporting NumPy 1.18.1+ since #831, since there were apparently issues with units being dropped for some operations in older versions.  This seems to me like a good enough reason to support only more recent versions of NumPy.)

**Comment by StanczakDominik** [comment]
Let's!
