### ISSUE TITLE
Calculate vacuum magnetic fields from general static current distributions

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#99]
The [Biot-Savart law](https://en.wikipedia.org/wiki/Biot-Savart_law) describes the magnetic field resulting from currents throughout a volume.  It will eventually be useful for PlasmaPy to have a Biot-Savart law solver that is able to calculate the magnetostatic field associated with one or more current carrying wires or the current density throughout the volume.  Potential applications would be the coils that generate pre-existing magnetic fields prior to discharges in laboratory plasma devices.  There will probably need to be capabilities for both boundary conditions at infinity as well as conductor boundary conditions. 

It would probably be helpful to look for existing general Biot-Savart law solvers in Python or other languages as well as numerical methods described in the literature (perhaps in *[Principals of Magnetostatics](https://books.google.com/books?id=cj5yDAAAQBAJ&pg=PA6&lpg=PA6&dq=numerical+solution+of+the+biot-savart+law&source=bl&ots=X_x9lut79-&sig=mqNmqe4z-amzc3JDIncdpDilHvs&hl=en&sa=X&ved=0ahUKEwiwzcy0iZbWAhXk5YMKHXshBcU4ChDoAQgrMAE#v=onepage&q=numerical%20solution%20of%20the%20biot-savart%20law&f=false)* by Richard Fernow).  

I'm not sure where the best place to put this would be...perhaps a file named either `biotsavart.py` or `magnetostatics.py` in the `physics` subpackage?

A (probably unrealistic!) stretch goal would be to have a way to analytically solve the Biot-Savart law integral using SymPy when the currents are given by analytic expressions.

Thank you!

**Comment by StanczakDominik** [comment]
Actually, you know what I just remembered? Deep down in my list of repositories I have a script that, while pretty crude and brutish, does this very thing. I'll work on adapting it!

**Comment by namurphy** [comment]
Closed since we have `plasmapy.formulary.magnetostatics`, including (I think) `GeneralWire`.  See also #1688.
