### ISSUE TITLE
Add attributes to quantities returned from formulary that include semantic information

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#993]
When functions in `plasmapy.formulary` return `Quantity` objects, the result does not contain the semantic information — the meaning — of the result, apart from the units.  It'd be possible to stick one or more string attributes onto `Quantity` objects that indicate (1) the name, and (2) the standard symbol for what is being calculated (possibly as unicode or LaTeX).  

The code would do something like this:
```Python
    β = gas_pressure / magnetic_pressure
    β.name = "plasma beta"
    β.unicode = "β"
    β.latex_str = "\beta"
```
This could help with plotting, since we could use these attributes in labels/titles/etc.  It could also be used as a check.  Like...if a function is expecting a gyrofrequency, but it gets a plasma frequency, it could potentially use a warning.  This extra information could also be used to learn about the provenance of quantities and also create error messages.  Yay metadata!

As far as implementation goes, we would need to do this consistently.  I'm wondering if a decorator would be best.  It'd also be good to avoid duplicating the information in `unicode` and `latex_str` if we end up having multiple attributes for the symbol (e.g., use the LaTeX code to generate the corresponding unicode, or vice versa).  We should also make sure that the label(s) don't get propagated to new quantities after additional operations performed, though I believe that will create a new `Quantity` instance.  I'm also curious if there are established conventions for doing this (e.g., if something like this already exists in Astropy or perhaps matplotlib).

**Comment by namurphy** [comment]
Another possibility would be to also attach a string that can approximately reproduce a call (#920): 
```Python
>>> from plasmapy.utils.code_repr import call_string
>>> call_string("func", 1, {"a": 2})
'func(1, a=2)'
```
That would provide the origin story of the `Quantity`, and there are times it could potentially be useful.  There are some problems with this though: it would be more complicated to do, it might not work perfectly for complicated arguments that aren't completely handled by `call_string`, and it's not clear if or how this would end up being used.  Plus, @rocco8773 doesn't like the idea. 😿 😿 😿 😿 😿 😹  I think we can hold off on implementing this possibility unless there ends up being a good use case for it.

**Comment by namurphy** [comment]
Oh!  And there might be times when we would want to include the particle information too, like `"ion inertial length"` or `"proton inertial length"` or `"electron inertial length"`.  That could also make the symbols a bit more complicated too, but we could probably find a way to automate it.

**Comment by StanczakDominik** [comment]
Oh wow, that's way out there.

That's... a lot of code and computational overhead for fairly little gain, I think. Like you said, this kind of monkeypatched-in information would be lost on pretty much any operation; in your example, `2*β ` would drop all of that information.

Since, like you said, I really don't see a use case for this one, I think it'd be better to close it for now. We can come back to it if we stumble upon one.

**Comment by namurphy** [comment]
Oh, it was the second comment about `call_string` that I was saying to hold off on, not the issue itself. I edited that comment to clarify.  I was planning to add this as an agenda item for Tuesday, so I'm going to reopen the issue for the time being, and we can decide its fate then.  With respect to the first comment, the biggest potential use case would be to make it easier to automate creating labels in plots.  The simplest implementation of adding a `name` attribute would be one line of code per function.

**Comment by namurphy** [comment]
On ~~second~~ third thought, this seems like more of an issue for Astropy than for PlasmaPy, so perhaps it actually is best to close this here for the moment...

**Comment by StanczakDominik** [comment]
Definitely out of scope for us, come to think of it!

**Comment by namurphy** [comment]
On ~~second~~ ~~third~~ fourth thought...this need is largely filled by packages like xarray and pandas, isn't it?  😹
